#!/usr/bin/env bash
# Copyright (c) 2026 VitruvianSoftware
#
# SPDX-License-Identifier: MIT
#
# Remote-build (RBE) setup helper — run `bazel run //tools/remote:setup`.
#
# Points this repo's Bazel at a remote builder (BuildBuddy by default, or any
# Remote Execution API provider) for BOTH local builds and the GitHub Actions
# pipeline. It is dormant until you run it; see docs/remote-build.md.
set -euo pipefail

# `bazel run` executes from the runfiles dir; operate on the repo root instead.
cd "${BUILD_WORKSPACE_DIRECTORY:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"

PROVIDER="" ENDPOINT="" HEADER_NAME="" KEY="" DO_CI=1
SECRET_NAME="BUILDBUDDY_API_KEY"

usage() {
  cat <<'USAGE'
Usage: bazel run //tools/remote:setup -- [flags]
  --provider <buildbuddy|custom>   Remote builder provider (prompted if omitted)
  --endpoint <grpcs://host>        gRPC endpoint (custom provider)
  --header-name <name>             Auth header name (custom; default x-buildbuddy-api-key)
  --key <key>                      API key (NON-interactive/testing only; prefer the
                                   BUILDBUDDY_API_KEY env var or the hidden prompt)
  --yes                            Accepted for non-interactive callers (currently a no-op)
  --no-ci                          Configure local builds only; skip CI secret/snippet
  -h, --help                       Show this help
USAGE
}

while [ $# -gt 0 ]; do
  case "$1" in
    --provider)    PROVIDER="${2:?}"; shift 2 ;;
    --endpoint)    ENDPOINT="${2:?}"; shift 2 ;;
    --header-name) HEADER_NAME="${2:?}"; shift 2 ;;
    --key)         KEY="${2:?}"; shift 2 ;;
    --yes|-y)      shift ;;  # accepted; no interactive prompts to skip
    --no-ci)       DO_CI=0; shift ;;
    -h|--help)     usage; exit 0 ;;
    *) echo "unknown argument: $1" >&2; usage; exit 2 ;;
  esac
done

# --- Provider --------------------------------------------------------------
if [ -z "$PROVIDER" ]; then
  read -r -p "Remote builder provider [buildbuddy/custom] (buildbuddy): " PROVIDER || true
  PROVIDER="${PROVIDER:-buildbuddy}"
fi
BES_RESULTS=""
case "$PROVIDER" in
  buildbuddy)
    ENDPOINT="grpcs://remote.buildbuddy.io"
    BES_RESULTS="https://app.buildbuddy.io/invocation/"
    HEADER_NAME="${HEADER_NAME:-x-buildbuddy-api-key}"
    ;;
  custom)
    [ -n "$ENDPOINT" ]    || read -r -p "gRPC endpoint (e.g. grpcs://your.rbe.host): " ENDPOINT
    [ -n "$HEADER_NAME" ] || { read -r -p "Auth header name (e.g. x-api-key): " HEADER_NAME; }
    [ -n "$ENDPOINT" ] || { echo "An endpoint is required for a custom provider." >&2; exit 2; }
    ;;
  *) echo "unknown provider: $PROVIDER (use buildbuddy|custom)" >&2; exit 2 ;;
esac

# --- API key (never echoed/logged) -----------------------------------------
if [ -z "$KEY" ]; then
  if [ -n "${BUILDBUDDY_API_KEY:-}" ]; then
    KEY="$BUILDBUDDY_API_KEY"
  else
    read -r -s -p "API key for $PROVIDER (input hidden): " KEY || true; echo
  fi
fi
[ -n "$KEY" ] || { echo "No API key provided." >&2; exit 2; }

# --- Committed, non-secret config: tools/remote.bazelrc --------------------
mkdir -p tools
{
  echo "# Remote build execution (RBE) — generated by \`bazel run //tools/remote:setup\`."
  echo "# Non-secret + committed. The API key lives in the git-ignored user.bazelrc."
  echo "# Opt in per build with \`--config=remote\` (never breaks offline/local builds)."
  echo "common:remote --remote_executor=$ENDPOINT"
  echo "common:remote --remote_cache=$ENDPOINT"
  echo "common:remote --bes_backend=$ENDPOINT"
  [ -n "$BES_RESULTS" ] && echo "common:remote --bes_results_url=$BES_RESULTS"
  echo "common:remote --remote_timeout=10m"
  echo "common:remote --jobs=50"
  echo "common:remote --remote_download_outputs=minimal"
  echo "# Default Linux execution platform/container for RBE actions. Adjust the"
  echo "# container-image to match your toolchains. NOTE: macOS targets cannot run on"
  echo "# Linux RBE — keep them local (e.g. --strategy=...=local). See docs/remote-build.md."
  echo "common:remote --remote_default_exec_properties=OSFamily=linux"
  echo "common:remote --remote_default_exec_properties=container-image=docker://gcr.io/flame-public/executor-docker-default:enterprise-v1.6.0"
} > tools/remote.bazelrc
echo "✓ Wrote tools/remote.bazelrc (commit this — it is non-secret)."

# --- Secret config: user.bazelrc (git-ignored) -----------------------------
touch user.bazelrc
# Idempotent: drop any prior header lines for this header before re-adding.
grep -v -- "--remote_header=$HEADER_NAME=" user.bazelrc | grep -v -- "--bes_header=$HEADER_NAME=" > user.bazelrc.tmp || true
mv user.bazelrc.tmp user.bazelrc
{
  echo "common:remote --remote_header=$HEADER_NAME=$KEY"
  echo "common:remote --bes_header=$HEADER_NAME=$KEY"
} >> user.bazelrc
echo "✓ Wrote the API key to user.bazelrc (git-ignored — do NOT commit)."
# Defense-in-depth: make sure user.bazelrc is ignored even in older repos.
if [ -f .gitignore ] && ! grep -qxF "user.bazelrc" .gitignore; then
  echo "user.bazelrc" >> .gitignore
  echo "✓ Added user.bazelrc to .gitignore."
fi

# --- CI: GitHub Actions secret + workflow snippet --------------------------
if [ "$DO_CI" -eq 1 ]; then
  echo
  echo "Configuring CI (GitHub Actions)…"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$KEY" | gh secret set "$SECRET_NAME" >/dev/null 2>&1; then
      echo "✓ Set the GitHub Actions secret $SECRET_NAME on this repo."
    else
      echo "! Could not set the secret (need repo admin?). Run it yourself:"
      echo "    printf '%s' '<your-key>' | gh secret set $SECRET_NAME"
    fi
  else
    echo "! gh CLI not found or not authenticated — set the secret manually:"
    echo "    printf '%s' '<your-key>' | gh secret set $SECRET_NAME"
  fi

  # Build-step snippet for the repo's CI. The GitHub Actions secrets expression
  # below is single-quoted (so bash keeps it literal — no "bad substitution") and
  # scaffold-escaped (so generation keeps it literal); $HEADER_NAME / $SECRET_NAME
  # are interpolated for the chosen provider.
  echo
  echo "Add this step (or these flags) to your GitHub Actions Bazel job:"
  echo "------------------------------------------------------------------"
  echo "    - name: Build/test with RBE"
  echo "      env:"
  # shellcheck disable=SC2016  # literal GitHub Actions secrets expression; must stay unexpanded in bash
  echo '        '"$SECRET_NAME"': ${{ secrets.'"$SECRET_NAME"' }}'
  echo "      run: bazel test --config=remote --remote_header=$HEADER_NAME=\$$SECRET_NAME //..."
  echo "------------------------------------------------------------------"

  # Best-effort: point out existing workflows that run Bazel and should get the flags.
  if [ -d .github/workflows ]; then
    hits=$(grep -rlE 'bazel (build|test)' .github/workflows 2>/dev/null || true)
    if [ -n "$hits" ]; then
      echo "Detected Bazel steps in these workflows — add the env + --config=remote flags to each:"
      while IFS= read -r _wf; do printf '  %s\n' "$_wf"; done <<<"$hits"
    fi
  fi
fi

# --- Summary ---------------------------------------------------------------
echo
echo "Done. Provider: $PROVIDER ($ENDPOINT)."
echo "  • Local:  bazel test --config=remote //..."
echo "  • CI:     add the snippet above (secret $SECRET_NAME is set automatically when gh is available)."
echo "  • Results UI / providers / platform tuning: see docs/remote-build.md."
