load("@rules_shell//shell:sh_binary.bzl", "sh_binary")
load("@rules_shell//shell:sh_test.bzl", "sh_test")
load("@rules_go//go:def.bzl", "go_library")

sh_binary(
    name = "agent-app",
    srcs = ["affected-targets.sh"],
)

sh_test(
    name = "agent-app_test",
    srcs = ["affected-targets.sh"],
)

go_library(
    name = "cloud_dns_lib",
    srcs = ["pkg/cloud_dns/cloud_dns.go"],
)
