# Copyright (c) 2026 VitruvianSoftware
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: redis
  namespace: argocd
  labels:
    environment: redis
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=zero"]
  generators:
    - clusters: {}
  template:
    metadata:
      name: redis
      labels:
        app: redis
      annotations:
        argocd.argoproj.io/sync-wave: "0"
    spec:
      project: platform-project
      source:
        repoURL: registry-1.docker.io/bitnamicharts
        chart: redis
        targetRevision: 27.0.12
        helm:
          releaseName: redis
          values: |
            architecture: replication
            auth:
              enabled: false
            sentinel:
              enabled: false
            master:
              persistence:
                enabled: false
            replica:
              persistence:
                enabled: false
      destination:
        server: '{{.server}}'
        namespace: redis
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
