load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "github",
    srcs = ["pages.go"],
    importpath = "github.com/VitruvianSoftware/devx/internal/github",
    visibility = ["//devx:__subpackages__"],
)
