load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "k8s",
    srcs = ["k3s.go"],
    importpath = "github.com/VitruvianSoftware/devx/internal/k8s",
    visibility = ["//apps/cli/devx:__subpackages__"],
)
