# Copyright (c) 2026 VitruvianSoftware
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# `nfs` — live workload data on the NAS share /volume1/k8s. Off-node + RWX-capable
# (not node-pinned like local-path). reclaimPolicy=Delete (dynamic app volumes).
# NOT the cluster default — opt-in via storageClassName: nfs.
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
provisioner: nfs.csi.k8s.io
parameters:
  server: "100.126.21.94"
  share: /volume1/k8s
  # Isolate each PVC into its own subdir on the share.
  subDir: ${pvc.metadata.namespace}/${pvc.metadata.name}/${pv.metadata.name}
  mountPermissions: "0775"
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.1
  - hard
  - nconnect=4
  - timeo=600
  - retrans=2
  - noatime
  - _netdev
