load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "authproxy",
    srcs = ["proxy.go"],
    importpath = "github.com/VitruvianSoftware/devx/internal/authproxy",
    visibility = ["//apps/cli/devx:__subpackages__"],
)
