#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 VitruvianSoftware

"""Keep bazel/sources.bzl in step with the upstream build script.

The imported app's own `build.sh` is still the authority on three hand-kept
source lists (the unit-test compile set, the fan helper and the Now Playing
adapter), and `Tests/generate_sources.py` decides which files it extracts for
the tests. Bazel needs all four as static lists. This script derives them and
either rewrites `bazel/sources.bzl` (default) or, with `--check`, fails when the
committed file has drifted, so an upstream change that adds a test source cannot
silently drop it from the Bazel build.

    bazel run //apps/desktop/vitruvian:sync_sources           # rewrite
    bazel test //apps/desktop/vitruvian:sources_in_sync_test  # check

The `--emit-generated` mode is what the `generated_test_sources` genrule runs.
"""

import argparse
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

HEADER = """\
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 VitruvianSoftware

# GENERATED by bazel/sync_sources.py from build.sh and Tests/generate_sources.py.
# Do not edit by hand: run `bazel run //apps/desktop/vitruvian:sync_sources`.
"""


def _block(text, start_marker, end_marker):
    start = text.index(start_marker)
    end = text.index(end_marker, start)
    return text[start:end]


def _swift_paths(block):
    return [token for token in re.findall(r"[\w./+*-]+\.swift", block)]


def test_sources(build_sh):
    """The explicit `TEST_SOURCES=( ... )` production list in build.sh."""
    block = _block(build_sh, "    TEST_SOURCES=(\n", "\n    )\n")
    paths = [line.strip() for line in block.splitlines()[1:]]
    # Tests/*.swift and the generated sources are wired separately in BUILD.
    return [p for p in paths if p.startswith("Sources/")]


def fan_helper_sources(build_sh):
    block = _block(
        build_sh,
        'echo "▸ Compiling protected fan helper…"',
        '-o "build/$FAN_HELPER_ID"',
    )
    return _swift_paths(block)


def now_playing_sources(build_sh):
    block = _block(
        build_sh,
        'echo "▸ Compiling Now Playing adapter…"',
        '-o "build/$NOW_PLAYING_ADAPTER"',
    )
    return _swift_paths(block)


CORE_IMPORT = "import VitruvianCore\n"


def run_test_generator(app_dir, out_dir):
    """Run Tests/generate_sources.py in a scratch root; copy what it writes to out_dir.

    The generator resolves its root from its own (resolved) path and writes
    under `<root>/build/generated-tests`. Run in place, it would follow Bazel's
    input symlinks back into the source tree and write there, so it runs from a
    copy placed next to symlinks of the trees it reads.
    """
    with tempfile.TemporaryDirectory() as scratch:
        root = Path(scratch)
        (root / "Tests").mkdir()
        shutil.copy(
            app_dir / "Tests" / "generate_sources.py",
            root / "Tests" / "generate_sources.py",
        )
        os.symlink(app_dir / "Sources", root / "Sources")
        os.symlink(app_dir / "Tests" / "Fixtures", root / "Tests" / "Fixtures")
        subprocess.run(
            [sys.executable, str(root / "Tests" / "generate_sources.py")], check=True
        )
        out_dir.mkdir(parents=True, exist_ok=True)
        names = sorted(p.name for p in (root / "build" / "generated-tests").iterdir())
        for name in names:
            text = (root / "build" / "generated-tests" / name).read_text()
            # The extractions name Core types, which live in their own module.
            (out_dir / name).write_text(CORE_IMPORT + text)
        return names


def generated_test_sources(app_dir):
    with tempfile.TemporaryDirectory() as out:
        return run_test_generator(app_dir, Path(out))


def _list(name, items):
    body = "".join(f'    "{item}",\n' for item in items)
    return f"{name} = [\n{body}]\n"


def render(app_dir):
    build_sh = (app_dir / "build.sh").read_text()
    return "\n".join(
        [
            HEADER,
            "# Production sources build.sh compiles into the unit-test binary, in its order.",
            _list("TEST_PRODUCTION_SOURCES", test_sources(build_sh)),
            "# Files Tests/generate_sources.py writes; Bazel needs them declared up front.",
            _list("GENERATED_TEST_SOURCES", generated_test_sources(app_dir)),
            "# Sources of the privileged fan-control helper.",
            _list("FAN_HELPER_SOURCES", fan_helper_sources(build_sh)),
            "# Sources of the Now Playing adapter dylib loaded through /usr/bin/perl.",
            _list("NOW_PLAYING_SOURCES", now_playing_sources(build_sh)),
        ]
    )


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check", action="store_true", help="fail if bazel/sources.bzl is stale"
    )
    parser.add_argument(
        "--app-dir", type=Path, help="app root (defaults to the workspace copy)"
    )
    parser.add_argument(
        "--emit-generated",
        type=Path,
        metavar="DIR",
        help="only run Tests/generate_sources.py, writing its output to DIR (for the genrule)",
    )
    args = parser.parse_args()

    app_dir = args.app_dir
    if app_dir is None:
        workspace = os.environ.get("BUILD_WORKSPACE_DIRECTORY")
        app_dir = (
            Path(workspace, "apps/desktop/vitruvian")
            if workspace
            else Path(__file__).resolve().parents[1]
        )
    app_dir = app_dir.absolute()

    if args.emit_generated:
        run_test_generator(app_dir, args.emit_generated.absolute())
        return 0

    expected = render(app_dir)
    target = app_dir / "bazel" / "sources.bzl"
    if args.check:
        current = target.read_text() if target.exists() else ""
        if current != expected:
            print(
                f"{target} is stale. Run: bazel run //apps/desktop/vitruvian:sync_sources",
                file=sys.stderr,
            )
            return 1
        print("bazel/sources.bzl matches build.sh and Tests/generate_sources.py")
        return 0
    target.write_text(expected)
    print(f"wrote {target}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
