#!/usr/bin/env bash
# Copyright (c) 2026 VitruvianSoftware
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# TEST-THE-GUARD for check.sh's `check_delivery` (delivery-orchestrator spec
# §4.4/§6.1). Every arm is proved to FAIL on a seeded violation and to PASS on
# a conforming tree.
#
# WHY THIS FILE IS NOT OPTIONAL. check_delivery is a guard whose failure mode is
# SILENCE: if an arm stops matching, it prints a ✓ (or prints nothing) about a
# rule it is no longer enforcing, and the first symptom is a delivery path that
# nobody notices is ungoverned. This repo has already shipped that exact shape
# more than once -- check_merge_queue matched `paths:` but was blind to
# `pull_request: branches:` and certified 13 required checks as reporting when
# they could not; #1794 was a state-mutating apply sitting beside correctly
# gated jobs. A guard that has never been observed failing is a guard nobody
# knows works.
#
# Hermetic by construction, like check_test.sh: every case builds a throwaway
# ROOT holding only the inputs check_delivery reads (BUILD files with
# delivery() blocks, tools/pulumi/defs.bzl for the macro-generated target
# names, .github/workflows/, delivery-legacy.tsv, the generated workflow), plus
# the minimum canonical-version files check.sh needs to reach that arm at all.
# Nothing is copied from the real tree, so a change elsewhere in the repo can
# neither break nor vacuously satisfy these assertions.
#
# Assertions are made on the "Delivery orchestrator" REPORT SECTION rather than
# on the process exit code: a throwaway ROOT trips several unrelated
# zero-match backstops (there is no periodic-full-sweep.yaml in it, etc.), so
# the exit code says nothing about the arm under test.
set -uo pipefail

CHECK_SH="$(cd "$(dirname "$0")" && pwd)/check.sh"
[ -f "$CHECK_SH" ] || { echo "FATAL: check.sh not found next to $0" >&2; exit 1; }

FAILURES=0
CASES=0
TAB="$(printf '\t')"

run_check() { BUILD_WORKSPACE_DIRECTORY="$1" bash "$CHECK_SH" 2>&1; }

# The "Delivery orchestrator ..." group only. Other sections of the report must
# not be able to influence a verdict here.
delivery_section() {
  printf '%s\n' "$1" | awk '
    /^Delivery orchestrator/ {in_s=1; next}
    in_s && /^[A-Za-z]/ && !/^ / {in_s=0}
    in_s
  '
}

expect_contains() {
  desc="$1"; hay="$2"; needle="$3"
  CASES=$((CASES + 1))
  case "$hay" in
    *"$needle"*) printf 'PASS  %s\n' "$desc" ;;
    *)
      printf 'FAIL  %s\n      want substring: %s\n      delivery section was:\n%s\n' \
        "$desc" "$needle" "${hay:-<empty>}"
      FAILURES=$((FAILURES + 1)) ;;
  esac
}

expect_not_contains() {
  desc="$1"; hay="$2"; needle="$3"
  CASES=$((CASES + 1))
  case "$hay" in
    *"$needle"*)
      printf 'FAIL  %s\n      unwanted substring: %s\n      delivery section was:\n%s\n' \
        "$desc" "$needle" "$hay"
      FAILURES=$((FAILURES + 1)) ;;
    *) printf 'PASS  %s\n' "$desc" ;;
  esac
}

# --------------------------------------------------------------------------
# Fixture ROOT: a minimal but CONFORMING delivery world.
#   - one delivery() unit `svc`, run target //apps/svc:deploy declared literally
#   - one delivery() unit `stack`, run target //infra/stack:up generated by
#     pulumi_project() (exercises the live macro-target lookup)
#   - one legacy state-mutating workflow, declared in delivery-legacy.tsv
#   - a generated delivery.yaml carrying the banner and the kill switch
# Every negative case mutates exactly one of those.
# --------------------------------------------------------------------------
new_root() {
  root="$(mktemp -d)"
  mkdir -p "$root/.github/workflows" \
           "$root/infrastructure/pulumi/platform/repo_config" \
           "$root/tools/conformance" \
           "$root/tools/pulumi" \
           "$root/apps/svc" \
           "$root/infra/stack"

  # Canonical-version inputs check.sh reads before it reaches check_delivery.
  # Arbitrary values -- nothing here is asserted on, they only have to parse.
  printf 'go 1.26.2\n' > "$root/go.work"
  printf '22\n' > "$root/.nvmrc"
  printf '{\n  "packageManager": "pnpm@10.20.0"\n}\n' > "$root/package.json"
  printf '# file\ttool\tpinned_value\treview_by\towner\treason\n' > "$root/tools/conformance/version-pins.tsv"
  printf '{\n  enabledManagers: ["argocd"],\n}\n' > "$root/renovate.json5"
  printf 'package main\n\nvar checks = []string{}\n' \
    > "$root/infrastructure/pulumi/platform/repo_config/main.go"

  # The macro arm (b) reads its generated target names from, LIVE.
  cat > "$root/tools/pulumi/defs.bzl" <<'BZL'
_SUBCOMMANDS = [
    "preview",
    "up",
]

def pulumi_project(name, dir):
    pass
BZL

  # Unit 1: run target declared literally.
  cat > "$root/apps/svc/BUILD" <<'BUILDF'
delivery(
    name = "svc",
    environments = ["development"],
    github_environment = "svc-{env}",
    kind = "cloud-run",
    run = "//apps/svc:deploy",
)

cloud_run_deploy(
    name = "deploy",
)
BUILDF

  # Unit 2: run target generated by pulumi_project().
  cat > "$root/infra/stack/BUILD" <<'BUILDF'
pulumi_project(
    name = "stack",
    dir = "infra/stack",
)

delivery(
    name = "stack",
    environments = ["development"],
    github_environment = "stack-{env}",
    kind = "pulumi",
    run = "//infra/stack:up",
)
BUILDF

  # A legacy state-mutating workflow, with its justification row.
  printf 'jobs:\n  apply:\n    steps:\n      - run: pulumi up --yes\n' \
    > "$root/.github/workflows/legacy-apply.yaml"
  printf '.github/workflows/legacy-apply.yaml%spre-orchestrator legacy\n' "$TAB" \
    > "$root/tools/conformance/delivery-legacy.tsv"

  write_generated_workflow "$root"
  printf '%s' "$root"
}

# The generated delivery workflow: banner + job-level kill switch.
write_generated_workflow() {
  cat > "$1/.github/workflows/delivery.yaml" <<'WF'
# GENERATED by 'bazel run //tools/ci:gen' from delivery() declarations — DO NOT EDIT. tidy-check enforces regeneration.
name: delivery
jobs:
  orchestrate:
    if: vars.DELIVERY_ORCHESTRATOR_ENABLED == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - run: "true"
WF
}

# --- case 1: the conforming tree passes every arm -----------------------------
# The control. Without it, a check that fails on EVERYTHING would look like it
# is working -- a green control turned permanently red is how guards get
# deleted rather than fixed.
case_conforming_tree_passes() {
  root="$(new_root)"
  sec="$(delivery_section "$(run_check "$root")")"
  expect_not_contains "a conforming delivery tree reports no failure" "$sec" "✗"
  expect_contains "the literal run target resolves" "$sec" "run target declared literally"
  expect_contains "the pulumi_project-generated run target resolves" "$sec" "generated by pulumi_project()"
  expect_contains "the declared legacy workflow is a sanctioned exception" "$sec" "⊘"
  expect_contains "the kill switch is reported present" "$sec" "kill switch"
  rm -rf "$root"
}

# --- case 2: duplicate unit names -------------------------------------------
# Two units with one name render one job id; YAML keeps the last, so a unit
# stops being delivered with nothing red anywhere.
case_duplicate_unit_name() {
  root="$(new_root)"
  mkdir -p "$root/apps/dup"
  cat > "$root/apps/dup/BUILD" <<'BUILDF'
delivery(
    name = "svc",
    environments = ["development"],
    github_environment = "svc-{env}",
    kind = "cloud-run",
    run = "//apps/svc:deploy",
)
BUILDF
  sec="$(delivery_section "$(run_check "$root")")"
  expect_contains "a duplicate unit name fails" "$sec" "duplicate delivery unit name"
  rm -rf "$root"
}

# --- case 3: the run target's package does not exist -------------------------
# The commonest real failure: a package moved, or the label was typed wrong.
# In Phase 1 this surfaces as a failed `bazel run` mid-deploy.
case_run_package_missing() {
  root="$(new_root)"
  cat > "$root/apps/svc/BUILD" <<'BUILDF'
delivery(
    name = "svc",
    environments = ["development"],
    github_environment = "svc-{env}",
    kind = "cloud-run",
    run = "//apps/moved-away:deploy",
)
BUILDF
  sec="$(delivery_section "$(run_check "$root")")"
  expect_contains "a run target in a nonexistent package fails" "$sec" "does not exist"
  rm -rf "$root"
}

# --- case 4: the package exists but declares no such target ------------------
# The half-migrated case: the directory survived, the target did not.
case_run_target_not_declared() {
  root="$(new_root)"
  cat > "$root/apps/svc/BUILD" <<'BUILDF'
delivery(
    name = "svc",
    environments = ["development"],
    github_environment = "svc-{env}",
    kind = "cloud-run",
    run = "//apps/svc:rollout",
)

cloud_run_deploy(
    name = "deploy",
)
BUILDF
  sec="$(delivery_section "$(run_check "$root")")"
  expect_contains "a run target the BUILD does not declare fails" "$sec" "declares no target named 'rollout'"
  rm -rf "$root"
}

# --- case 5: a NEW state-mutating workflow that is not declared ---------------
# THE #1794 SHAPE. A new hand-written apply is a delivery path outside the
# orchestrator's gating, ladder and kill switch. It must be declared as a unit
# or justified as legacy -- never merely added.
case_new_mutating_workflow_unlisted() {
  root="$(new_root)"
  printf 'jobs:\n  apply:\n    steps:\n      - run: pulumi up --yes\n' \
    > "$root/.github/workflows/sneaky-apply.yaml"
  sec="$(delivery_section "$(run_check "$root")")"
  expect_contains "an unlisted state-mutating workflow fails" "$sec" "sneaky-apply.yaml"
  expect_contains "and says exactly how to fix it" "$sec" \
    "declare a delivery() unit and regenerate, or add to delivery-legacy.tsv with justification"
  rm -rf "$root"
}

# --- case 5b: the other mutation verbs are covered too ------------------------
# The regex IS the firewall. If a verb drops out of it, the firewall silently
# stops covering that whole class of delivery -- and "silently" is the whole
# problem. All verbs are seeded into ONE root and asserted in one pass: check.sh
# takes ~1s per invocation and this test already runs it a dozen times, so a
# root per verb would be five seconds of runner time for no extra signal.
case_other_mutation_verbs() {
  root="$(new_root)"
  n=0
  for verb in 'bazel run //x:deploy' 'bazel run //x:apply' 'bazel run //x:up' \
              'helm push chart.tgz oci://r' 'docker push img' 'gh release upload v1 f'; do
    n=$((n + 1))
    printf 'jobs:\n  m:\n    steps:\n      - run: %s\n' "$verb" \
      > "$root/.github/workflows/verb$n.yaml"
  done
  sec="$(delivery_section "$(run_check "$root")")"
  n=0
  for verb in 'bazel run //x:deploy' 'bazel run //x:apply' 'bazel run //x:up' \
              'helm push chart.tgz oci://r' 'docker push img' 'gh release upload v1 f'; do
    n=$((n + 1))
    expect_contains "an unlisted '$verb' workflow fails" "$sec" "verb$n.yaml"
  done
  rm -rf "$root"
}

# --- case 6: a stale legacy row ----------------------------------------------
# The list may only shrink. A row whose workflow no longer mutates is a dead
# exception, and dead exceptions are how an allowlist quietly becomes a
# blanket permit (same policy as public-targets.tsv / version-pins.tsv).
case_stale_legacy_row() {
  root="$(new_root)"
  printf 'jobs:\n  apply:\n    steps:\n      - run: echo nothing-mutating\n' \
    > "$root/.github/workflows/legacy-apply.yaml"
  sec="$(delivery_section "$(run_check "$root")")"
  expect_contains "a stale legacy row fails" "$sec" "stale exception"
  rm -rf "$root"
}

# A row naming a workflow that was DELETED is equally stale -- and is the more
# likely way it happens.
case_legacy_row_for_deleted_workflow() {
  root="$(new_root)"
  rm -f "$root/.github/workflows/legacy-apply.yaml"
  # keep one mutating workflow so the zero-match backstop is not what fires
  printf 'jobs:\n  m:\n    steps:\n      - run: pulumi up\n' \
    > "$root/.github/workflows/other-apply.yaml"
  printf '.github/workflows/other-apply.yaml%sjustified\n' "$TAB" \
    >> "$root/tools/conformance/delivery-legacy.tsv"
  sec="$(delivery_section "$(run_check "$root")")"
  expect_contains "a legacy row for a deleted workflow fails" "$sec" "stale exception"
  rm -rf "$root"
}

# --- case 7: the §6.1 kill switch ---------------------------------------------
# Rollback level 1 is "flip a repo variable". If the generated job loses its
# `if:`, that rollback silently does not exist -- and the only way to discover
# it is during the incident you needed it for.
case_kill_switch_removed() {
  root="$(new_root)"
  cat > "$root/.github/workflows/delivery.yaml" <<'WF'
# GENERATED by 'bazel run //tools/ci:gen' from delivery() declarations — DO NOT EDIT. tidy-check enforces regeneration.
name: delivery
jobs:
  orchestrate:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - run: "true"
WF
  sec="$(delivery_section "$(run_check "$root")")"
  expect_contains "a delivery workflow without the kill switch fails" "$sec" "no kill switch"
  rm -rf "$root"
}

# The generated file going missing entirely, and the file surviving but having
# been taken over by hand (banner removed), are both failures rather than
# silent passes.
case_generated_workflow_missing() {
  root="$(new_root)"
  rm -f "$root/.github/workflows/delivery.yaml"
  sec="$(delivery_section "$(run_check "$root")")"
  expect_contains "a missing generated delivery workflow fails" "$sec" "missing"
  rm -rf "$root"
}

case_generated_banner_removed() {
  root="$(new_root)"
  cat > "$root/.github/workflows/delivery.yaml" <<'WF'
name: delivery
jobs:
  orchestrate:
    if: vars.DELIVERY_ORCHESTRATOR_ENABLED == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - run: "true"
WF
  sec="$(delivery_section "$(run_check "$root")")"
  expect_contains "a delivery workflow without the GENERATED banner fails" "$sec" "hand-written"
  rm -rf "$root"
}

# --- case 8: vacuous-pass backstops ------------------------------------------
# The two ways this check could be "green while checking nothing".
case_no_declarations_at_all() {
  root="$(new_root)"
  rm -f "$root/apps/svc/BUILD" "$root/infra/stack/BUILD"
  sec="$(delivery_section "$(run_check "$root")")"
  expect_contains "zero delivery() declarations fails loudly" "$sec" "0 declarations"
  rm -rf "$root"
}

case_no_mutating_workflows_at_all() {
  root="$(new_root)"
  rm -f "$root/.github/workflows/legacy-apply.yaml"
  rm -f "$root/tools/conformance/delivery-legacy.tsv"
  sec="$(delivery_section "$(run_check "$root")")"
  expect_contains "zero state-mutation matches fails loudly (rotted regex)" "$sec" "0 matched"
  rm -rf "$root"
}

# --- case 9: the false-positive traps ----------------------------------------
# The way to get this subtly wrong is in the SAFE-LOOKING direction: flagging a
# BUILD that merely loads the macro, or a rule whose name happens to end in
# "delivery". That turns a green control red on correct input, which is how a
# guard gets deleted instead of fixed.
case_load_line_is_not_a_declaration() {
  root="$(new_root)"
  mkdir -p "$root/apps/decoy"
  cat > "$root/apps/decoy/BUILD" <<'BUILDF'
load("//tools/delivery:defs.bzl", "delivery")

cloud_run_delivery(
    name = "not-a-unit",
    run = "//apps/nowhere:missing",
)
BUILDF
  sec="$(delivery_section "$(run_check "$root")")"
  expect_not_contains "a load() of the macro is not parsed as a declaration" "$sec" "apps/decoy/BUILD"
  expect_not_contains "and the decoy does not make the tree fail" "$sec" "✗"
  rm -rf "$root"
}

case_conforming_tree_passes
case_duplicate_unit_name
case_run_package_missing
case_run_target_not_declared
case_new_mutating_workflow_unlisted
case_other_mutation_verbs
case_stale_legacy_row
case_legacy_row_for_deleted_workflow
case_kill_switch_removed
case_generated_workflow_missing
case_generated_banner_removed
case_no_declarations_at_all
case_no_mutating_workflows_at_all
case_load_line_is_not_a_declaration

printf '\n%d/%d assertions passed\n' "$((CASES - FAILURES))" "$CASES"
[ "$FAILURES" -eq 0 ] || exit 1
