load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "mock",
    srcs = ["server.go"],
    importpath = "github.com/VitruvianSoftware/devx/internal/mock",
    visibility = ["//devx:__subpackages__"],
)
