# External Secrets Helm values
installCRDs: false  # We'll use CRD management through the Helm chart

crds:
  enabled: true
  keep: false  # Ensures CRDs get removed when uninstalling

leaderElection:
  enabled: true
  namespace: external-secrets

webhook:
  create: true
  port: 8443

certController:
  enabled: true

serviceAccount:
  create: true
  annotations: {}

resources:
  requests:
    cpu: 10m
    memory: 32Mi

metrics:
  service:
    enabled: true
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8080"

# For development - creates a fake SecretStore
dev:
  fakeSecretStore:
    enabled: true