load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "logging",
    srcs = ["logging.go"],
    importpath = "github.com/VitruvianSoftware/homelab/internal/logging",
    visibility = ["//homelab:__subpackages__"],
)
