load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "podman",
    srcs = ["machine.go"],
    importpath = "github.com/VitruvianSoftware/devx/internal/podman",
    visibility = ["//devx:__subpackages__"],
)
