config:
  vitruvian-core-repo-config:repoOwner: VitruvianSoftware
  vitruvian-core-repo-config:requirePullRequest: "false"
  vitruvian-core-repo-config:requireStatusChecks: "false"
  vitruvian-core-repo-config:tabulaProductionReviewers:
    - ipv1337
