# Copyright (c) 2026 VitruvianSoftware
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-ntfy-endpoint
  namespace: monitoring
spec:
  encryptedData:
    ntfy-password: AgBnq+hBwEuOcnk9YyEYloMfMuSWNslpwR11G9xIxjJiPCb1XKAn3NxonfG5pOCOP3w5DbWnsDG2Q9ilydCtATdpNV23GHxxwQu4ZdG73ss1kmR5zNSUygS5k8RtJiQq8EWiZPeVCnw8uetQ+XzZOf4Q/vMhs5GW3+v6LrR33GuQ0n0N9QzJQjgGw7eAP3cuD11Qler8et/IeLcC2RKSWDDrDdxLRe5ENk2mWQE5D66lUpWqi9/XT38AsAsNZYlrhDrLVWId69oVpqXzfXXanckSnZs6mEmw3m0uJOiugA+1Ixbtf0mEv1bodlGKomGaDSTgYxyjTVR1HKCV2VCLUzZSuvko8eh1fXrRAx2JoF87a7B1O901Csa9jx/XMfIF4ezuv1RFw4O9tbxp1qwojtsqtYJebDwlFfgk2NN35JB880zRdTXLkD+1vAoK3FbmRuIa97/CCe6FGG6G/T1AQH9H+bs7I649+Vi+2qXvdNY42dow51zq72hPop4hUJDrYa+x9LpezpgZvZ8unWowN6SCRmNga6qRCVdbiEzpFGfvKcv4y8HC4hkN3JCTJ+Ozi20rExas3fQ9/nT8Q6bqN0RXTKBkFsWCt3PtwzhoORXgAYqSyfoHcjUGJbqUaXV9Gnrmhml5d6QITKo+2aT7Xt7+IYNCMA4W0Tz/8g25STVRs6E+WA5vanac/sRt4rwMPtaRE5axRuCNuFqCK5iiQiY9+2eHTpzjv21mHYGpSw==
  template:
    metadata:
      name: alertmanager-ntfy-endpoint
      namespace: monitoring
