# Copyright (c) 2026 VitruvianSoftware
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# Generated by `bazel run //tools/gitops:seal-argocd-backstage-token`.
# Read-only ArgoCD project-role token for the Backstage ArgoCD cards.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-backstage-token
  namespace: backstage
spec:
  encryptedData:
    ARGOCD_TOKEN: AgA5019NX3WP3nfgE+NkJoFk67EAl7uOP31MjgK2gcSqp65+B7KQ7W+9mxGLr4teemcRqNgJEpu0v4Kic6wAyUeOahPr1nQh2ck09X4l15RUjxHKe8ogj1uJcF+bX678bI4ytsePA3nO33q3u7dXwGj33iv5jh2xGHGVV9EfbF0RtwDcAh2tqFzri99qqRgQ5VUwsYZnHRyqfUU3kMcy1+vjnMUPlbwvx2kYUTb0PHOdmP2wlgrlUOtSb/2voeOw2aflSIW5ZvMtrNKt6z99EKtO1KBV/eV0Lc396j61BcWnnbakdWdbagSNhxc4W9Q8I9oYndXTufPNmeJqTn22zce5oesHoci/vrNrgn4+IcnlguHtGGFWUAQpr3Dm4ytdfyXMmqwYnCjfjShEwOGUUNj2IH+S1wl6TXhV+okZI7K797+tBj8cl9Zr3jeP2xXzY5TNj6eP11DTBjBG8grcGj85APyNMT9n6KqT7u8L3w0quEdyHX/9GyxiEIwrIQk2kolRSuuO94pqXRMwYt17RWayPFIy/FH/ob3WVl/HHrudK7l0SCl75RwLPaVuh6WOeHafwJQOrlg3z4rHvBKbxX7eZqKcq6uDvGo6tZmPb1yknApXeT0DnuAjzQE9JhMzUXQypXjl8MEIH/JuomK+3JNCglHBWiYeQTa3Nd7qBIP+o5Z1kRu5qagpeKUMn2rVXOd++PO3cdbBKDMEJ+JJzKMeKkfuCVo9gyYUHrGFbCTp1k0kiY/Mrk2Ej+1AZCXPe4BXXMyqfHG1VULuKMYSQm8Nh6AP7wUW1NhcPkDvqwI5MpI2ocBcfOLJ/67zadyFwb6oAnLKB2J0Xef+BZGfC2gQqfLg92eX/WW0QthSNGC+u3EQ+uCS8pXJYJ6o7o1TJY7hXcEyj2+MeoRB+22lqMHSfAeJ3kHjcV+WfhgrZVMwJwi60BhjzIi8BvKAjQAb5u7KEGlMsrZc5oq5tAIvan1gVrEg3ucaTAApAiBBGKy84Aj//d6QyaCy6tvpeuNLw2Sc8ptDspFq8QvFeN1/eVEr/OB72/U=
  template:
    metadata:
      name: argocd-backstage-token
      namespace: backstage
