# Copyright (c) 2026 VitruvianSoftware
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backstage-secrets
  namespace: backstage
spec:
  encryptedData:
    AUTH_SESSION_SECRET: AgA4755/h04uw+40bFyXct1eNFnFKLreclwy+cLsfOimPXZduRP5uzQnnK5wuqZDxzZT7nXwVTuyGo0MzHmwzU1Fwx5tdLqQKcT3FsZ7XCYS6sipFJpZ6B2hijgcnBwkQx5u9JYR4dQev22OmafAHSrUspAtlu/JCGDOGaR7suXexJ+ygYHgRUACYnuqb2VS51DJwBU0jm+/N0pHzzfJCq7A1hg44ytUrItR8oT40vTXUy3XwuyCw9VGD80g/BdsdiTaxbusNoRY7AxeeC0ILAq4EeZQ9r9iTyIyFJCU3aqnKJBvwAU5LfqubI9imvK22GF/O+JNbg/lKQukIlOQZ6+l09f5F8vU5urvEYsq4h+OU/cnAIvyFEtveASQ6v+N+579IMq7IQiS0eo/Ej3YXy9Uzon7Us+qJijITOolmH4f2Z8hUueo4MRrubnrkJEzMA8mOuhMP8XUAiMHbLe+PTtKr8dUkIVqANY39OUSED+75y6EpkZve9gpv3t/RYE97vinOIISFDQk5RjaibC5os/7ywNuYN54CjBZx89aMKIHzcF6ACbZXMKWBC+nMlvCklR4hTIXpdOiT/hkPPXXf72vxk21W0Nw2uMXWj9WczmJrCsvOsdqD2pENFkL6LqZTelgi2+GCF5azLM892NA2mluZ1BJJEuMeu5k3n68xrfid3dkBmMV/+V9tjgTWRSZSaTS6AycCZv7qhEH2X8hmaMM9R/N+F9y/PrtbVJFnXgUB3BD+p5tLHPoFvoeA/SVu8OVJbe7k2W2SJQtIfHoMK7U
    BACKSTAGE_AUTH_KEY: AgAFx7eDyg1ZIpJ65K6k8922a5V7/HUT4oqFz+37KfcgHTOImqC+892yNCQ1/rl6AdbNsQhlHR1gd+YaYEJQoI50LreAxeq65dZoZpH1jcB8hCiMxauc9GixVoAI+xmQVzk7BtBBqH6LQEyj8fIfq25J7Bwr+6IbTKKbeIWkqzD7/jC1/Um6P4HxgTD+3hlUWxo2S0eYcjb15sVT0tLwpzdElJpNR0SqRuzV267q8zugUK6unzpdgo7rtVTCGA6Vekx0Uj6zKOsIi+ZLoYsQMeO6EcyggLb5NbAkFvJAb3d9bVcmRbWjludMgfX4HBvNB1GkHC7rji5gTFHLv6FesD1iKl9wSXyjBfRZWd+dxTxTcJesKpfovcXO3SjSJqrPdCGlJ15UkmsEa8kaWPOgv1xQAMAzS8iKkzFXlbp7xFTNvBmRxBty5OgGEy6465VYLQzEJ4QPrL/pHe0DNqVr66lFsP6uobuQ2AdsqT6At06zPUhsz4ATy0Qrq/YlO8t8TUIxGfxVEsVjBq92lHNnrBBNvzGo3QJB3cjxSrlV6dVoDIRDwNQt+gpZr/DB7LibJ0tEV4Ox68fRZiKZAVSKheko5cOhM9eenaZJ3SCnbiR6GeqN1bU6qK7zkHtnISCKnwGwgoiCuZYknaptJ8AzvBZ2CVBIGYH5mzvjRMXPkJSpgIFmR0LEWdI/XcuQUnVANwHRRuAaeCjQWsZE2tWJ+sMRWWERwmUvxIa/nKRIEg31eHkAR9Vh6QaQLi3Hc3CW35/UH/tjuVXTcwV4ey8bFJlG
    POSTGRES_PASSWORD: AgCyPI1x4AoYRw8ie2U1JBTQy/oPiqsA+MUonNahkwyLh3kyka4bMITwJ5dfiB9RQ92OgTu07WZnn3gQRyvk/DYe4kEEexSpmqc8JnDfGQh7r3D6itk3sXs6V7dG0MPoxuerXfw4HBhVD2N7XdUciVUX52PUSwBOX9/PdsZ5GmnOLtmSNFqfM9Yc9N3XAWUtQUMp/eyCk2VlQWObtwEyXpX4M9fXDqhPpaKqXsuTprH7acrk2NY/eVgkArTtSwSS8VB+TOvNjxZkcfqtDzl89sVhwgCGKFu55GRvvDOPfKvfR+fDpzaPz/XGcd2PsSHG5bCClJjflY1TMIjoFczfVZVnTOOrn+K0YBHJs0IZQVK+Dd1uZo2PdfAfXheoFwKMHw+OB34jqevZCABRK2CW+rF2S7zPViQ9korGvIujFNxNkItQdxfmKqlp7ECxb5+Vq9vDmAjWAB5JS8pAPb76wS0WneKt4+P5IXZfw4L7wlKCvbGB+KvegJOrThmiqa97mIVy0jIvczUasI5pHEU2X1zMmYZmI6jeVVZfIATBd35rblMQawjfIX5DfVo4LGtTXdpQsmMJPe/03J8nIgCbhn9JWd7hx0SZngUqviG0isbEeuHawZdTRLtPeJE1zi7/VAtjNpvnZ/e3UqxQiovKsVxXim9qc2LDWLUs3yTF0enOhu3E9ZooA6TdbnZg9thQXeKFWryL2MFxjyBEPPTE87yA2vml6/U96tmu3pCz9uWC
  template:
    metadata:
      name: backstage-secrets
      namespace: backstage