# Copyright (c) 2026 VitruvianSoftware
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backstage-db-app-credentials
  namespace: backstage
spec:
  encryptedData:
    password: AgBQkR5v5E2Gq2DArjiDdXnI0OYhVAK7dkRpl/IUPrapvVusindRTB2AWddRzYyz4f+BuJBi5LBpUfSBmufOA5qQ3HSBxAxaSscSZURm3Nr/ea4cnnSryOIjs4DuraOQ8jJ1yh04L79zb1r+7V2AutZDV3LNpLRBoFvdb+49MMU2ddkC8tmx5JZZmMAWJFlUE6jZMpEyWJq63zHmCJligPJ0bkZxQ+6BP3m1GDoKvu85c6kdL3r/xGwZAc3z5LQx+R2G+gL316JyMmdBNZXxVczBUFuNPbTmR1RWbC86SPcSjJI7HNZmGDwMpMJk+Rcsz0fU3OkfdD7FZ3gP/FtyQ3hWM1vUkxJad6xAj3MEn6kiQ7nWOekp81Ru3TpypL/Ux71W5uwhX7iEQWwVEETp8UGUTI65182may0Bm7rfOmNdyf1ZlTNS8nXIVJMHugtic71YxicJaHp4FoC3sHWfYniopNeVGdvNEgjuFF8iac0QZbP2WMSTqbtgzXOnxtbVXo4kk5eqELZtuL5EeCxoz+80jU2vb6vTKNe6EKDRBloo/grycLIK8rxKxj5Dx3e5DVlc2q7YeWLlnUsio0RmhXHQ6Wo7ZcXU3ed91nxIwDLRHYZPQrRh+i588MkOvuw5DVsTzbN/kbh5BrznIYGcmALizNSSwYZw9foHy5ijL3F6mFhnBIw+2qNk0JqcpBv9AGUogs0Lb+gi/nXDPgJOKgs3E/xf+ZzJPnMnbpppA998
    username: AgCltMIOXDF4Ow86/PPeDZY3zvMvENoH6mqqHrwYENF7RO2oRfelZ/moTDKOut/q2qluHAz1QaUHcgaqOY/wQJ1ngfvUc3Y0Z9vEbAs1+84wlNIFFbkJPj+9e18JaxZf2JjsfydHFF1mp0iapHtAlNkjmGVh0l2h+yKWnx1rwcO/Vwi//XgUN1VqPjPlV9yjDR/m1Dih0rpQHVuYi5dtPukg7MrYm4mrldbuKlWvSJbl6EcvzJwX1qoHcYCvXTlV6A/Cn7jSYTQB9U4lO+c8AUz3kD7MDnZXOSlZfb4XpVVN+AEBt5yik/uOl1kp6cj01hO158MCC2U1QdUCrbS71gL4BAa6obb1khXAypaITdPcyGSbjLnpia2OVhbgOE9pdTP38AH2J5VRctTFc9BJ/Sfs+rIUjJXKAoCQSoDUAGITtyl2Bc7vFnSLcGNm5qsvCKXWGthHfvoEz7WbOHilxNFTSpSxCCkazopLk2jUmiuTQdVhIqk3dB2WmuUjRXQO8Lr9slE11cCIbuHaQ3c/Ob3luOTZbqjh0NX/qYorYdrXIcmMb36nFyivvXspZ5+Q3q/bMQL0ORyVKM5zgRaTRRnHAYxKXI+jkASVUzEcOCH5/+gao2AIb3aHGZ1BgZ1nMe5AtuY0dT7CZpSph+K5XolxmoG9h7RjBAWtvjA/yP+nmJH0DJUL0lyubzoBhBY5CJ7g6DJtFMGHxlU=
  template:
    metadata:
      name: backstage-db-app-credentials
      namespace: backstage
    type: kubernetes.io/basic-auth