# Copyright (c) 2026 VitruvianSoftware
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backstage-db-minio-backup-creds
  namespace: backstage
spec:
  encryptedData:
    ACCESS_KEY_ID: AgCysP6laZxVmNTX60XcVCv5Jh8la9TIQW6QGZxsQL3oXrHTgd3+hKhp3B41UCoPWyyUm4TBBpmr2NObLyJzx42XYo9aaIEklPtv0HE3DBuarXkiUzAOEHdf07g3Wukqjskm+snnHWg4Z8YZ9BYvy3XkszeAWDq84xKWOXxNNEOcKopzCiZ5vVuBA70/pHD41RNDr39WjuwyjYuveB2bwL0hHcsT+2JrYZn1RGwkRs7zRZszlHhuOJJU5fLVr+cfsrkp7dl8hvEFFcdVffVlDJ3py37S7DKoj4ViJvciFAWKXxxCFdVRkOe5kqI7wUi50ADFDJEBKRsoEcbeMyWBSMOJ1APDabJ7wpQmQAGEAo9cQtKXC2F61SyxYHJzfUF9M+UmsbuoQvgMNRsHcrinm6gxfyKgTHmxT12o4SVhOFIvJeVBI7z/kXoHT7LnJxLS+1S62pJ4HSk1Wk4qwE7Ucy3j0/00B9kyu2C/cSpb4vLw+FxUtuMwZKY3TITd+eJDM5N28kQw9EfpdcwmReKszVMgK5d/nUkYBlbEGPNEM/jfx+wDJc3pfMm22eYuvAxHEp+sJMoX3ZREs5yP2/Dw0faIfbcHhk0fpcjtRhtR7Cr3erJApkXQA0PVD8F2lsOmrS+muoE7zt8yVQ9Bd9kgE1shLDhon+MXnFtpoJzQLQG3cC0ZBVcfPITq40QA/kKZg+8uNSBKZQ==
    ACCESS_SECRET_KEY: AgB1yRi2U3mW8N/gKKJftT1xx1ecWpVz6Cp+K03xiT9TTnAzqzBv5sLY3WksHXIW+Mv1qcgbyiAGt8WxlUHXS/sIjeqj5QmtLfVYwVzRNfQEZK+iA1Opp+n8Bn9RoMnaO6VIOBZ91TKiOtF9xLBRc9wVhqrKk+UGRIGpGD1GJFQhTSKMkRvcXbDVOL83j1ph1XMmbCcKDg+n0bAssOR3oxR0BfRWlffF39DI7Ea30GkGmjY4NhIITysPXVuQCsPZCpy8DOS6xIPa5JlEY7GghMH+Q8fP6KRhvLGOfXY6/+tMqR8aH04h0Xv6mWjboh5CFrbj8oKo12vq0zj0fnAuP27fWXupUNPSJvplLhBS61G342tyQID06OMGYJnDnWm/0BQjcFJW8gYHQHMILeBqdPHvs4tpNHhdMIV+QARdzwT33ysqWWsut+Yz2P68kazGlxIhyyGBjYT58fQ0IKm0kyTiwEizB/LkGWMYCSxuF7hs+5xXg7+CWaQkNZx3VjxJFHRp1zHWtcetsg5fzMYIqbcaEMaubd0FyXRVSsVh+lniSabL6Zi5gW+ytRG7ZZYCNZY9jR0OBHe1ejpogyUcWJi+SDMiwLMvWJQkxVHLXNgDbK0AxAEs9xhoKDTLzCAb/qY2NM5CYWTtFf6d5QH9r0lQ9rjJBTSTJZEWx1eVw7aQwBNSNXkPyFuxh+uhVU4HECVEx+vhp7lPM7ch9EHIG08i4X/tI96yJWxjFNqDgzyEjCSKJtE8hoHS
  template:
    metadata:
      name: backstage-db-minio-backup-creds
      namespace: backstage
    type: Opaque
