# Copyright (c) 2026 VitruvianSoftware
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: buzz-db-minio-backup-creds
  namespace: buzz
spec:
  encryptedData:
    ACCESS_KEY_ID: AgCaNQ61dN2WGJdHNBU7HDZCJbG2xGacUyvpmowArjI0sO2Zf3ZX+cEsyJYyD0Ll43HZDOeqjdG/cuNj+rKzExvjuQwZM+0mnZETlqepsu9wWQ5HhMZ8qEiO2OZ+CV8698Wj+5e6IGSkecSoO7ZbT2/konW4EN9CptwMQNywdVNYVnmEL33z8pfZLyRfDi1pDGb/rlPGi8jOskeataQIKGAXoluryHTWEncYyn8EHSVRWJXmE9NnRK006cKcKnmMdeB4u2czMg+amK3BKuDMBDGWV/y1JDMJJ+Vx5JhvtmIaltkdw6QtHdMBb3QMkpAfpmEuTYux1s+goThKfM5AcSkpE3N4C50Q1VZihSbDfSHch7vYS52pdozjHg5TCLK5bJJl6dFGE+Qufa6gFCUjyLsZzIU2UbIPJtCIwHsUe3vfbYZRyiV5xztU2VTSIHcQk5B0LGbnMsexJYhHGtoG0lD/QxsOdLsk31vjqtEvTXipn5GzxIwL8Q26dsvmXsy6tXUlmoYyaXnOxrJ4JEvFS25HsldQ4rrfArejVJ+10V5rhqgrEgu/GQ9Gdqp0QUPGcpE7o7KJZHhDL3wTacYcApZfJyhbKtMzNaMrM4TxvrVJzg1Cn/F0C1VbhWYS9oVPySNpKhtvgfSMWcASuZpxnvskS3CjKGWE0pjUVsZPUxhWsLZeJm0JZ3mDKJ6pCJ8xQ4MP1DuTNA==
    ACCESS_SECRET_KEY: AgAyhos4ZiRrEyDszNFD2hwoISESG9rtb2ilZosMFcxS0qxapmnXaTXUHXcRRq6PQmZsIAmcgaDuerzECC1uUIqV2p/Hn83Mt4PQN55wtVvsc1idCMxq7LpHNLPIDBRsKUghhaao/XbWZK/hjf1XdEhDjGMffLo8G/IqDC+vr6qHljoGHWyxa0+xcdjmUQYnnGn/bAvdxVd+xPyenWBevnxVNDBiT1CUVignfLgDGZ0TKtfA0WsBwt88KqLAZpIjMNPTcQCKGPLn/cf4/9VKPhr8IiDRJF3hcmdF3Smd18r7ks2S+1UJhHXrUxy9w9+C0JGQl9TNv/Nljq5dtTxAX4KPncUr3UA5OfbeYmn8r91eQVbFeyqnnJZ4709i3BJarmf5NrPs/W8ZtpBlU3yn4xp4xw8WfNBZDe2cLOqaSDjoN5KG7dGkuIXWtavSni9bKeeg0HMpVU5p3g16L8JO74Dahxc0TfsZfy6vaU4/CwXc4F9Ki0+q2XiLa9ASbxy3zEDgHtSOzHRVMsetZNdQzapHn9APQJczFCJCGlyzlVkWOqW8v6G8SU5tZnrUVVk3oYOtqQEIP9Y0sAYu+RHjxwbUiYKwrmVOylyb2X80YvRw9F67uV+UdyB/WbTgFo9HTtOTrVFighu0550h2PQojJpO3I8dSfEsWSW8vrwAGcR9GVUVPVTmOvdls//MO1EgUEmUYNzKc67KrZeXVVeJZgy5/mTJX3uiopb3V6/1/PgQZ5UEb6zAstCv
  template:
    metadata:
      name: buzz-db-minio-backup-creds
      namespace: buzz
    type: Opaque
