# Copyright (c) 2026 VitruvianSoftware
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: buzz-relay
  namespace: buzz
spec:
  encryptedData:
    redis-password: AgCwB7+8JGoKgY+W7i7/QIcif3fuuiXSO08u3JKISNQH+4udViquPIjP3yJQyEySfh7bZU/FZxCw3bTUVR0OHeE+0PQsds9sI6UKZ0m9GnlvuZgH9q0O+PrdgAhSo/eXr3jceAxtRgime9pTVqRZ7MfeW3swDyqzlja0HElf4L6Xmq7qCUrtZcE1AxtPkloR/2Nm2XcS4pwyqV+m2TbIOxFOqpZo109SQ2n1WQxcBsiwEgb7UN1kgzKD+6zk5EJ0sLP6YuoZi3GQ2rJ1Znox5tXV542Q6mV9fa7zdTqjUMWEMa0fizqVno5BghW5iVmldpb+TfuJd8BBb8szYOQLoNvAPwGEFfESZtIbBPNzpWzmiNoghiaDf3nzc4D6c4b92EgFziVpctMixDrZIQ6kKah7atGIxMvez1hTBCaIQ9Zl0GnUZxqlBoMUFk9s+58pcpAxVEhcNlVXnb3MO6wLd+NWohtgIFIOkoTt+UXg1vsW1K88sELhL/kFUODDhwxfUvWM0Gr/wHKkJf+RGNzw81cq4UzUkMNCYPIZHw1Bp+MbIGuMi8oXIzyUGJcAP4KY90XwawRg9CRVHQsKq+UdAA0O3eYz82ojUtXcPXmj/sUeTiv29aNViU4s1Nxf8GoSOs8oSD9w1o6YOBv5kCXWilOfAO+xwadatKH8pAMwwkAkdo8U2M7HP9DHFIOIqEG11LMep7RvpnG9XyHUT9HPdbVeR8I7LGjeWAdAjsnQ684bGg==
  template:
    metadata:
      name: buzz-relay
      namespace: buzz
