# Copyright (c) 2026 VitruvianSoftware
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: buzz-db-credentials
  namespace: buzz
spec:
  encryptedData:
    password: AgBXTrobqWDRLVHYJjIEtA/KXDP+XRtDOtdkJomGMN7poJuTCau/kEkuEuxU8GjVmQSkYICbhkI5t+T47WmM2SCjyaa2Ej6tta77Y2/JqXQpulWOemtsaoukjI4bAMIhdYBf3Nz9U7D0yu6gbxTuHzyiAy7pDIyVbux/+8L+99NFlCz7/cLGxyQ4QUW/ugAQdqY8lqCPg+tE2rv46Kxu8f/Z0QMITlPvk0/dP1ysCwoFE6ltpi7aRIuwXFNEWCcLLrRx9fD/2UXGIhnsbpfupC6iSKX/NmytVm/1xycMYxZ9fEBgX3+rjJoQ8yQWgXI9vb/VpTJ6ZQQYTFa6wLJGvXxMcLyDkD+h31iZYShiuEwsNOT71eGsQfLV5wL3aW083D4K5J6VNEb57BatS1B7KVGi4khMLxt6LnrYYUEF/akdWVyiVBkMaxcrcAkmcfSGQ6pbRzCoh7Lbg9mFC3Fq28GG2u8A09N2DG+BVfesLzfdj1ho9amhvX4sGEm13ISZLD4AO+A8evbtfa7eyT5S857kiRYmy/q6ravDUWASEE+QLpY4kJSCIwvNrgRSR2iVKK5+WnB6wz4IMrp5Pmxw+OwibjYsL+I5qZnLX7rwYkXSS8S2K+g5nZexPkh7Ic5py1yYbPzRsJQckCnJ7qFwgSyTBotiA/itxSBkMYCyEZsYMnjirOSTPWY0hyu/jR5TpFPsrpadOsZY0qpbL2o/Atzzb89VGMtRyw==
    username: AgCraNCdcGm2Ou3L5fAWWPGSD1ukJhWIaeoLRKGiGFEaVJSv1aFsmBxGST+ekW/OPRHWSSqOe9KFO7AtLrVxReGIZbH8C5UJXlX41WOXV/qlVrxySIMA01DmZONIEohfv8/psBiCnFXgstnin9SNjbGUsPmqz16pNgPRV1HbfaiTWWixZiZLiK+hj17Ve4/PpQfytsPygGlqLbpcU5XAmt432ItL3RkQIDgmbbx24+hLzCdSq2eBemGk63uddj+i88siOhNKZLrbaQOIuOsABRiyJHTcukqQbnxM4MRVIChNiWhaBOeYYms3OFdHMLIhC6bHgRbN2p0VHP3WMgHGb89+l4nGVqWaDVVOXNvmoIjvb6F+9E7iODHG4uvIkTRNZV/DqEQJTDa3PjCZOiMl/8Bmd3clTyma5PYaIdj1E6KiymkGjM3hsG3XjTQIsjCFdPH/YYwi804qronM1GaiwLhLu8feIuVGyQT5ltvw9HIvwIfFSKd4KpU4Qf+KefBx/KgwEQc90e2NZQv8u5IjC/ssm926PUxRbw6vC21KG4ks2/RuEEceymmzfGLsqogXi0wAwn2LnyVu7R9unkbK55AMkxyyaIn3om55pCZjc4hREYcOZbvXKD99KxH+haxZ281dl1mHAG6NL2qdMz8CWjxmoRunsFlN3/+830LnqIrwphYggM5+b85zhvK02FkbwrfLZ59q
  template:
    metadata:
      name: buzz-db-credentials
      namespace: buzz
    type: kubernetes.io/basic-auth
