# Copyright (c) 2026 VitruvianSoftware
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# cf-secret (external-dns's Cloudflare API token). Sealed directly to replace the
# fake-ClusterSecretStore + cf-external-secret indirection (which held the value
# inline — not git-safe). external-dns reads this Secret via secretKeyRef.
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cf-secret
  namespace: external-dns
spec:
  encryptedData:
    cloudflare-api-key: AgBJJveyKmZa0OkMD7KQDq2EuVdqLT9RKMx7JpfLnrP/tcnL7lBzgV+ac5Ibehlq6GFwiZJMbraeYXFdDULYWEMJgVNVMXB1Ih57ZumqR8ZfpisT4f91kK7Vnqtct6OztmZzfPvR6lqCnibnLwsjQ2u3/+RQL0aBpFqoOzNM7xdESXfz1eIpFVILkpAni+UxDT1Yr8mGahAMVycdj9y2Yhxmu+Poqi5dsORLHpVsWeAt/pPLyhO5H3tuzSb7JAGpVFt54XAByxElb7l2uXuD7qw0ypzosONRDEjUdGqwjp5ub7M4a1kORd/gRWQyEeugGeN7+a+LuqVyq0vpgjGwJZxxdz7l+VTdpy2PJJUEbgKXpdkBgFx0fbXq+xHKsb28SDOgP83NaIrw2MNlveDmqcnDUlfs1U+5ctCYaB2sK4ndLfhfglWpQpqphO3pStePEiwRmlu+vKwvTrobJ1sGye5OddBRtZyy/Ob5h54DFrtKOPz8Eoji87XW9w6yGZAYBTUF+G4+WjywDxBLsIIgY06y0M4MeeuwDkn+HW1/McrMZgL26LetDls1QujuaR0aV49pjODknriJqsrHIQRsPjBLrVgZ7QCzIm8SmqSrzo0MH/4O9gclKd0/RwjuldVCKTf9dBUgxHKso49cs+/fNMQrSf3npljjpb90l3yc4fugTy/gsqBlOMVX3QjHDYrqa2cI5yvstteI7xGd44wUbwTXPg8bQ+VNo68RIx9nS08QhPuV64jMZvDJ
  template:
    metadata:
      annotations:
        reconcile.external-secrets.io/data-hash: d43a3c59bfbd43638afb01e6fe20fc58
        reloader.stakater.com/match: "true"
      labels:
        reconcile.external-secrets.io/created-by: b816a8084f199d20daf6214e566972ee
        reconcile.external-secrets.io/managed: "true"
        service: external-dns
      name: cf-secret
      namespace: external-dns
    type: Opaque
