---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBVuy9YZ5CEplAZpV+cJTajqfJJoxVc1c8p3isMBKjq51PTwf71ucoVvux/wc4Jcou1mhs4HRQe6WYaf8WXnVgzQwPgiRH79jnbqctSkAHcyjQ80nRImKXwW/WtfvWWCn9U/GppIiWP54z+ABuvK5NM5MDeSVDSQy11bdSI2Yuh5xK42Yp7Ioei85/1KiFLKKXu49FDRC69ElkmP93JV32vd8zpYHCLEAQyyXYxvQeYePkltY0jIEYb3m7v+wEWavPEoudaniYIyLjyqm5OGBxVGxJ+dUvUpFn4KDnUPi9dgX3qHr/cCD51gjInHxYQsNvqI4pVLUEuoj6OZyHJk4JsVDOvBOP/jFOWvKIkilSxeblZsPcGA+kup21sX+7H4lqvfkUYnPv5M7nZn31hBMNgpsBap9ZezOZLjRwhXclWa7V3CCUgrLGjhUCQXJQhqXDavGYeHmj3c4Xro0QhfZzy2soL8o0Fpz5Ns5/1F4+EoXkxmngFeIgBikyRPMNJzCrAsbbKILrK1bm0Y4KrMCv/hzHNwB7cfGHfTs+PRUE4Tb1yGz3k0ztT/ng7ipudoVFl83IpgDPqhpiB/9vMwobJ+P0msgzdJusjP11BB88hg4Kv3BZgyg/XnJCRvcMJ0WwmCDTK4XvzB/zDkoSljQm0vYgE8Hw4PmpvZ7EtKfIaADVMn8h+85nM+Vn11gmDOnmeVMwYo/EyszY0mRgo+Z2TxktXYAE2r+nEbhsWSc1QI3oklfQYuMld
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
