# Copyright (c) 2026 VitruvianSoftware
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cnpg-cluster-minio-backup-creds
  namespace: cnpg-cluster
spec:
  encryptedData:
    ACCESS_KEY_ID: AgA01UCMEUa+EKsq0t5lD57WrtiSGkch6K8HW8Om4KI0U+fq4dg6uoMe6ztDpaIYLI8hhgi80IkQJ82Gcxa6AElb5wJWjdT09D6oTdgkpJdZpyq83uuKtB8XkTC98W/jliWf6G1gduQmAYVHRFKfM0wh/yPHWvmMpNkhB/XWHbmkELQBzI5k5IpCdjsv7xZWYAPzX8rmd60MfHJeDZCRN8+1HowFKlN/TX/qyb0rbVRvLByWEjokFhrHuBChG0j+cVOAxGEobxzUMZ7HWUGn6ZLmrhGAPebON2e5jI4R0SRFLli0EbCORjgGq8GDWZ+Ja/NPeR59uwCu7O+Nw4jfIq/rRYMqDFWD4SqJqO0/0jZx3Q2x0AC55dFQJ1e4Sjb7niAcXkSbSLOqgZXMojb1C4knFLc5probEXNB1YkHql/7CLUhVekA2lrQEtEZhHiZZlflw2QWKc2VXFHYurxj8wtpEuUD5kTnAiNbSIRRO5UAYSm+dDX2R7dvK8aqiEIg77bsDN68y7MZyX5LEj7yPeH/elrVblwLMV2padHSWVigwzl9lb/O1tdsIk+1yCyrAHX6HUN5nPcPHll76zwjcw7wp+cMCYS8yZZ2pAHBOX8iM7sc+OA4IBqZ9gC9IjcSY83ddg7TMGu0ceqJSDPQIUU1l5X4WPosc6XUnViJJnWPm/5P4fSCBRmphFh0c1FZ57LJbzNseQ==
    ACCESS_SECRET_KEY: AgCEBZk8l1JofNDnSPMWa8Pm7eDhOLKqOwjZFzieDX91egEUk8sHSTfjiK/qMBXEWrVX63Iz0nY8p2vLMAeYLrIkSxblPRQIxP7xv9RfyjDbUyEXMulahAxKCUJuqVhGUNUkwkvy9bWDKIBTyGM7FPHXgMXqgbVpRqFItCTbMkDGRop5hnOCeB8fJJyG0bJfpCZ3XCIKVLJaUe2I08L9oE1Zt4Hr0EP0jUovYv9oNiA/5W+C86Ai8FmnaoEaDC4acTEW+eOvR8VT+9QhB2+CU3354tx5ltPJegpdTFDG3JqYwi5WyBDiQrC5bH6aeMJaHv5NO97mYcdipdH77a7j9qF/GFbqXedRqEjHsI1B2LQWSBvZmbTJkEUbJ1qfOP16bskk1HIdwMw82VPtVLMrnZjquWQDNW0AioXt03iPGrxQyNRo30h7DheKerhlrrdQ7mkcB5tIZTZJYdE/LZ4YPhoB2R0w2scatxG1XGagmXQHy1qFj67neo/F5TG81Ysh1Hp9tfqREliXDIMTJaU++MEQNzP02eU8lO7KF6vU6hL5adjmDf7pTj9SYGn5fuFOCRuufTXK+n9redgGZVaqQPgL46JfvRFoYAeQ1bOqTgxG4yMNYbhnx+sFs289t2fFZEpDA7kOnndPumoOF8aapAQAM2JJ3kdakD6jjc6pxsEzK39v3FNidJI8xAjbUsElNVjeI1rzX13vuRzgcDmACWsooYUzPKEcwPjPRaDiL1142dOeUhwwSN8Y
  template:
    metadata:
      name: cnpg-cluster-minio-backup-creds
      namespace: cnpg-cluster
