---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cnpg-initial-app-credentials
  namespace: cnpg-cluster
spec:
  encryptedData:
    password: AgBp/L/cvq/aSenX3wDPBqbHMFo/otIf6HmLsq8p21EOUbiqNDB4B7v48dU5fdYomrKjuThzeiLcHLysOP/17042L2n7VX6e9V25q2kyT0n8WpAWMj2j8QE2sc/a5lsCaDx86wV1wyDKUs+SFqeq23oKLyAAeQNTfYoso2JoWZfgUm9C07rlE9//Uu9kPxHbvndzdqtRtyPTGc/qVtQK9UNlcgxK8qsAI7AsBG/X4zG30VijchwpHS47yvbUA2XLvXBc8/xD7GOsmTqeOffjRPfOnGJtguqhQNjCa8vb5X0+YjQU2h06kCIUUt7ZgZ6ogrukbEIbgPhw+l8uq7pqq57JnmV9sdxhDcs5CaPCvUtqSm5j5s8Yh85bBFbneh6XeAaVJJ5r7FRgwdnL/bKBpXYnXH18usHSruLUKKroQxVrsvsfH40llcCAZ0EhZgyFwYzoonFnXkfbTi4tbh9kReNyF62K37ujTaAT/elAfbM9wuzpmJVtD1jgTAVXHrVjKvu13K+1iXcGHY796rTEwE3fk6ULgqnEdmi2eH732zFinDO8i40slel2tbCidWHb+gGTNaGggr1HPPCjkXiQvHSKNRtVMsHbUxr8R8IRnIaj1W8WpGUoQk84wEDWpEmj+Ya6Z6rkI3pj3vtn81deubjSOWsGqhSl18NwUHzKnbh4mY4ICOS0GVxSNPRqI2xE/SFh4bxYN4pqfK+P
    username: AgASWBCzyV2x29IK6Qj9XKupYvKAtfd5ADOf/Fr3FD+gfheXnUopMUlt5Dw/3Fefv0wdKrcXTL7U0XROMrkib6Pq3L0FkVNdpMMOYSdP7taBZfwtjPvmeRiV68ZzDuOvCcSYi8BTH/XtRiJ59rM5U7AS2KrYmPRXN7GehWIYgZERjeQN6Ftcu/WvH6aCmYfGuzicou9MNXRA69z79Xy3jPUvMQd+dgswNsJHZIox4/zSVJlTn9XjLDBGQz+1LqRsbuoiSY0RAOYWN+TOsea60UYMmAUzrfKweiHB1isarB5WQDCPN/6+NeUJ0Hfj1nXFp8IUjJPvsC1fUMuANLI47BVQ2/9n5QmeWcTViM9eonSWxxT2YEB+DGOQFnbBh2HRc5ig6cF90jhhOsuqbmx4OhQKswJXIig4hDsPF+vs1DcVjkBSpuT43DvQp9Hx298Y/l1zFcsGjtLv2LL/wkBK7UqQ4YDwOx6l4ucDJe33Q4giwPe0N/qdxOtARXUI5PGrUQTsj/u8u8KnU4g8PBtIxHSFF5v5CSPDgkbcvaFvg3DhhNk24oS3cZsbczSpPeVWpkpacSfEbtLBFDNJfDJZsAIK9Ar3iCXjUB+zasE+yfHzuR5r1oqU8WgdlRv0mjWmXh4R2SZZ2ag1Brx6tRXAOZ4Iptf8k2qT7t9EFSiVMOpPBjWFvrU/RFYFsQAYFz0rSQPXY89xgrm0EA==
  template:
    metadata:
      name: cnpg-initial-app-credentials
      namespace: cnpg-cluster
    type: kubernetes.io/basic-auth
