# Copyright (c) 2026 VitruvianSoftware
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cnpg-cluster-backup-s3
  namespace: cnpg-cluster
spec:
  encryptedData:
    ACCESS_KEY_ID: AgBPmwbsc4Ik65+ilv7g/EVGC3UET5k4bytSk75LHrTV9CMCGv86ec2PFpTBGTQp+lt4Hv3m2QSwal7WLNifOelqL13/KwXw9hRQWOxk7OJl2hCSwzqXUDnMQ6a9/s7agdBRCxMB0aBwzmwdXqRCUpL6oKTnBsycZYGqy9MRdld5xVslVNSdfp+dyFnoesPeZTS56MKB98ygoFyuhBTOBIjjnDzd+xqQoxGNBi3mX1TtYnIue1bzi1EdHAQFX2XnLmsEnZuflgQ5PII4ivIxPfoMfSpp0EQV3hMrHCw9GbmiojGtplf7y+TOQiz8R0HqUS+MIDVfWy6Q5zh5TD7KsWRlz2mQI/tHLEobZp8TuA/97Xazm++6ifH+Imvb4PM3hUOyhflBpT1z7DMJO9r/Zx+1uxG7ufXpBNS70PatsKgseNfk5XpLJb4LvbCRd3K4Uog4hLJTiJg+cGVndeCr8XKBLtsd17YJ8ONdHvtC8Kpi9TvbLm8wQV5lDtMqXwhVSizY3M/qD8HpJxsmtK093Oad5QsD2X2VHRoGN8Bi3WODi1jDt0H0osqgPcsXcaxuKibirmWNyLAUX+eH2DQgClgqi5yVUWB2mwvM1UdDll7ni6RHTkpwXzRkbPrxZfRy72CLp9Giq+YKHDzpOm0lNh642BM3o6r77MIi0n0XIJlRgTc+SuIQdj/qZaJrVgIIpQnA97A7WwUaLsAyS5IxwDa/yD/f
    ACCESS_SECRET_KEY: AgAMD34GxMdiW8ctbdUUhUHpcCDgabqTJXDnh620oP56tzhp5KeZs8pblGAJkAwsmxXpFDCQdfhZJMECg4OaP1f5kuxgswcU7S53HIUG8MubwofWGKhRN+cumSVZ+O1W25PTf+UPB+PozvreU4s0o5iOO+XdbxQooS8v1tp6E6aH0r3ejH9xfYtH6ch2Wpu14M5v44qJHJaExLWywoCOWWI1ApXrWHeRH0tXvLKAAwRXoiMFvdy8mAWhlVNTgi8nuaTJfkKv++PTcrgd5TWQsUQ7oUyC5X7dnpgDb60fjnk44RKwtJZdoDDdeVhZ2vaWfbWa48D07jsQfPmNRovf+T68IZn7ihNMWE2fim6TGBORwUHmlsjaHqnEdJ0imtzaeccFooGTTM5lOjX35spwCPWdYItgHOAhENZ5VgNjoVpBsc5hv8keryS0HJauq/FTUgNb6GAt+ZSD9zBaz7w0x+0GpheYhg5YVEXvBCqyLb9HNtjGyZ9a9Dl+dsshGvNcxzDK5Su+gea961Wc0P28zNhHrNU8Fzdh9pcfaFontelAekgf1fRIiqY4SLU1yV4I7ITWfeMphSznm3jY81Exa14cWctU/qMn8XZdgxUGXZDfkGrJmRunMJqHv1RY3pruyqX8i/OxysOnSA6XMRMCYprl24VUtzuJse/sqiP2PrSPuydj6ho25Az43e5MYIITUtcsg88cjZDghrwePiPin0a+6R8QUSFNfZgsAEiPiG+iVyWRKi/s5uh98Q4Lycqc108=
  template:
    metadata:
      name: cnpg-cluster-backup-s3
      namespace: cnpg-cluster
