# Copyright (c) 2026 VitruvianSoftware
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-otel-webhook
  namespace: cicd-telemetry
spec:
  encryptedData:
    GITHUB_WEBHOOK_SECRET: AgCZCv4DEtUwB+oPnt6L0YkeNyCk1CDGBrGT2qPtNL6mL6KXt92w8y1nKsAyrkJBVaVUgnvNUYMD171gM9HlWehHfKKeF/1Aab+GC/pawEjXh4HT5PdvRcrEFepxByYHKV7nqSMUUHHcXzhVhA6Y/BxbeoKeZ+8ALXQlTJcuJTNf7XgpUmXtWYzRgGRAcVpwlryjRlAJiDOU8QouZcwOA7whUshSWuCnEoKK9CzxqY2Nwjm7BLV2QL+o8FcWDEcUjCpZg53gCckhuC8rRCtaMKNXQW1Z3QNq3TiaL7PYxs/wIAEidlFghh0nvKoMIyh1UeCzjcdNU6lBN522VMv0XsTlifUMUyJBs34dgWum7FprzVYewmxWYLV0tpphZCqY9UxS2OdRsUfMhWu0fNvKGXpSFKhZkv0qr2OaKggChPS9dEIIiTUD/OtR95uxmV2dOBX1FKUTzPlBa5wlz8t4/3A29LIVHHNDJEzQi3p9kM7qjUoqvxX2o2zVNyrg0Q8TuAzKhKL5zpyf26uGUZYdvvcGKbzSnxTaxJws3tTSIflRWDyeFwOhDC9oxEGVi7I5v9GzRq0VGEvcu2c9wdlLKwH4BXwl7Izd7MoJCb4MERVwmeZy8M+Y4yWzD/fw2SxZPRes/4lRaydA9kCmn1cAwo3Nfr6aJeCererJuYn2A4UD53/xqVo2iGj68oUpU12tkb/P6LP1m8Mz7vAj0qMCMDxPvVOr1AfW9as1kfWTyrFWu00qtisVOZHVsd9q9dHkN784+OFQVdpcwwCe3NNl2JHJ
  template:
    metadata:
      name: github-otel-webhook
      namespace: cicd-telemetry
