# Copyright (c) 2026 VitruvianSoftware
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgAlxMQJvE7ATJGfKyFMrpih25PBHdOBCY/RNxI870DzEl0CrLb1dZrg0MY6/+LYWYhJZUV5DfrV1E788xVF0o5wOZc6ZZ9E8hUB57KaTwp7vohQLK+iit/3sZ8G99ryJpDwwSL8vj0hXLWYbgZTd21okcFAo/ShEoeiGPVKVTv71AX/QD2Av1GOkVzhU5+sqLa+zyuuSO6UKuGtQwfAl5N98yew9BAtKottCZzcaAq+ISdM+uS6xBMkMJGyvLY9f15UurHg4F3v9Mf8pDMRf+/m+jt5pZos3kqlcSIib6A0d7NAD3xfeRmFhz1RepV2P3z9Qu3CdBLOveKFw2h/2klS7eZsV1rlP1ORYZlmI9v7w66bTUeBGFrD5LUXox/5PAZHAUVldeJpIkvw/45go1qkPVnVqH5QXM/w1oJLcrfFOqvBUX7lXWiQ7IlWFomYNPBGtjCllba+CMiilIGNOjs4zHatj47EVx9EDfyLwXmUrEa1Af/muR9l26qKx5CqsGyjQGsUs5kWeoLFpk9SsWNLhXb99JJFAa2CTitpH1P36juU9yVy0FYUfpB7Psxj8D4uJplavlkW5uSRpx0wl47kX7peSCKKQVmzzq1AnybI8pPvBsguXeTZwLNT5E2MM7eONAYrQbaJHJ8Djz9fNj0pNfZPWUMXG5sR1/DEDh9LyFbhzRus8rv686tsH1F7wantL2zTWzKpjl93zsvOIEZw/VaBhpAtSDE=
    admin-user: AgCGWLStGjc8iB3oNjKnlniLjtJbsXh3S8bMnkz1ZV+oLLqaUd5c0T3Vg57fx/dO2ZKM5EtU4Kiwznd87J9S5Lpwfi3ODUFAAXoBx1k3NsKnP+kTgLEow1RDFXOfSoVuSSERU9PJsL+SGlR+PHs90dYooSlgnY38r3nVvvkj8fsZZiXzIa50/2bJCeRPqklJ8sG4WlU5KXTYZ2sr8omq7DQGAL8jtuli7X0uzR2fFQL811Hs7l1T+YrptSE5ROTzJLBP63XgGgxKa2ekrg/EmnsgepDdLnMEu+WWbuoozKH/KmSw6/scGbv4KYy6UptfwKG3i9pK/MIMBFZJj6VcvtNVlFLNSD7t35KtBgDr/2xOPOZOdI9KrzUFIN9m3+W85c/OpdpxneWuEHt8tmNo3zWACwjv39Ny38DgwrRJ9c7BLifkmMKwpAhFSaUyjfIBr2uNX9D6RK/CSEFLJccXCS6AdboJvfva7qnRjwrMwyAQgX4YnZG3Syln9thBFY5W2u+c2xVtnTfBjZC3cqb9HoJ3G74j5zaEwTSzXnRDKIUuayM+O5yl/5zU8Ux5t1sf9e2OT29mB28c/g16kYVLY5t/36q5ERv2l3sWfKkqiDsiuGJxGsiVDjpekQ2QAeYXT2i/HUoqQ3qMAz9AzKTW05URHkKdn5QZUjR365rY+18g8f/x9CwjNiwxLfUwidwU88mCElPmBA==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: grafana
