# Copyright (c) 2026 VitruvianSoftware
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-db-backup-s3
  namespace: grafana
spec:
  encryptedData:
    ACCESS_KEY_ID: AgAketU2UJHvvOEBBP7Xb6Ita+VTZfiKm/S5P4wfBLrk6wm5fehHpU62YQqrJB5bxfjZT4l3eI6Xnr7FpJFXjmpE4Xqo/JYB+maRJJociNH3IoR5iRnP4q1lRhR5B42n4De0cGQ5K9RGpRPLGOi0dfwUZkWGYYcXzNzldPo/mDq6lnQ7y86ZRtHxkLJ4MiiEu4n8YCEyqKmZ/JplI38SeOadj1Qm9MEiSTW+eKF5JvnVInoVxE+9YDrsPb8k0eak2OipmDW09DKWPEN2bsHx2fwt+TqmVRtTuyO/p1jKOjKs4HA5Y1dA9Iw4gVlLuX10V+GoRZ/FtibKr5E8szHfRtEtoiigYmMylJYAAF3taVl0dnUCnrRLAad4uoh2jCrvZdTQm2JFP1tSE0e3UwZaCrhfaa+hnczV+Z6wjHdvn9FKPEFKD14dD/XPPCnIZfcZmCqy66HrhjHBQU5Te6eHd9EYkxw5IBSHUAdZG4h/5VoBBwf2aOC0kTtt10or1LDsYZQ4d+93ZYOc71gz+5TL/+URq16YdL3pWJsKJ8DpcNn3OeF6z1DyW1hGb7G/PZIT9f9hL+1+kklsXP9OkBeVBHOHeIwC/1zlVwcPTN4paRvAwEbL9udPVZGFPLTnYd3KzS0CZKA+IgQJw5JpnXLm8l4GoXEDgzoRIegK+4hi+/FP7P4cqFvpLmDuhb1+vKL5sv1UZBk2fLJ47LuyDcVqO+kQ/A==
    ACCESS_SECRET_KEY: AgDFISAou6eaBdB7LqmN3O1YWDiMAoHjXSaYcALcz101hndEqpk0gxCy+nNEHtaJkyrwS1sJn83958VdxqB7vNJ4jI1n1Of5a5zhOzh0gGwaYe9NoWiDASlqoGrL9yLXNZYSA24uEELsnA/tY5bzzTJFjDsDALhdHkyWWsFdyVqP36+RvSutENfp2S1VXzG8SDhEd1AjYokvBL51o5dHUr04uOojv2b6/2ZXY94TdB0A3Vi0apYV1/7M7NVNYo5cDIVMX1oURLv65m1OuvH0fO7Aknmud/JBWyu+K1xTV9UfF3k9hoXN3BjhoCazsMPbQoMb5O7acxTT6ix7Xd1PmSFsjKfcbe6B6X5Iq/bBdGCUt2F4JMxX7qGIB7in31Wmqv969jXEW4Ly8ERzCK9vWAOOluFYulgX7wpmVXu7dVxzI68fTSRSKvySI3nxlQRwclB6HzAnApY6GlSaKDcpJSLFWD5707OqCuvCHCGJZDf9lHJMl38X7pujqFMldM5BQP/DVQOzIJTTXwceJljGpc7espcu9Xx1UM6jqY03u6EEud+U9E+KuRuonR/KdsNhz3m4g5pgboobSLwerq6Km5JdOPZzrcx4muhg3iRl0xyKKNfgYHein0Ce7BU55VvS1Ieyb8nSCUMUrM7dy0Xkz2rMH+ZYHHH1nREowL7f9zwM6dd1xdMcqhvZtU/kqCwJqhka67xThahxqk3M8LIILLyyRq3Se1Zm/5YziCuOOb/Il/JR7T73Iap6D854IBVT/ng=
  template:
    metadata:
      name: grafana-db-backup-s3
      namespace: grafana
