# Copyright (c) 2026 VitruvianSoftware
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-db-minio-backup-creds
  namespace: grafana
spec:
  encryptedData:
    ACCESS_KEY_ID: AgCWMR6QPzUmdrvhkY35hXkz6w6/RRazHMZ6FQAcQpV+Qx2ZfWDmMOBKkukpj6oHStMUAXv4oj/WMiE37xVSWB4SHG3pUub6W6rinFbOZA7sHFyFk2+eWzDwnZy4exUovGLutqaHSH/n+Cs2PlaDOEoF1mY3bpi/cILAKjJR0flDdtUypv0EW7UhwHKnjNlz1ihET1eH8+v7uP41daatOcISytVvjfwkxbBwWp/LX0/PFMa/RCmQZmAIgwvFvMeGlg+NJn+yCwL3grdYqMFCdNmUDQwMFCYdVn6tlGdRDmGckrPSHNtn9v211ePWDWeinKFPF1OjxERkWGl2L9u9m3vS7Kr9P3z/+Pu6Em9sKFibdLaIEiQPvUlCcKpXGpDELu87dlilV0y8I4lg9Rc81JwC35pv9E745Aj1h27Wmc56+kDGAVgW23r54Y58UmAD/0cTy1JKEumjpEJXsTV3xlktHypf6em8LL7bz+Z/SJ12jiRLrumkL0aTD4qVYzviukbcRIR4W7ZtQWdf+/N8T4sImKfOd15nrgeXgmtp+gz5xbA0IrNkTupQqMioRcCVGSC+X+nLgfpMP4LvPbCwvf1jrD3bDnqToInzs+LBnXHDqs99EXN8c7yhzuxTngYiHqicgqy7rM0Q1lGErgS9Og0RSG3PWmNnDxIgpMSLrk6srCG2+thWzFSvctYAwn2cJlVeGMP7zw==
    ACCESS_SECRET_KEY: AgDA3uIWi1E7OW5qxvQOvkIGTRNunCy/ShWaHbne885MVpv2fLX3+fGAZedWb5JwOUx2M26nxUIQwN9Gj6FAESQ7jQAQ0WwaVgn1w8qyFEASUIMNkJ4i9DA0ufD2o2A2v3wGLVkRCRW9mHJnPDWlHp7DxVZYtWblBkniot+NJaXkg6F15ZHp3FFe4sFBeeezAi2b6iemvKyBFCcZ8kpa/ZarInkxKQcMG8IJsyr8xvr8KTSMm6jWLvzxC/elQFFlpMXRG7cEHvHT3AJCfajRY+fW+U8proAswWtwCTuWfr1xSKnOUISnQQeBNKfCqqs5BF+2waMRt/VYeNb3j+n6Zxyo7ToE8vC5il9pWZGbXs98L9WZNaDuOX9GSopvCAd7OyyS8vC7uiG/ep+8uDPTizm3lCo36dR4pLI8jpA0glAiEAe5a94357CkVV2+ScGpINLstUCg8E/JmOzAT6QIrlNKF75qu4EwtQjUAip31/rEU7xK1JcMWjDsy4tUo9wqVjLSA/+lu6/zvy88KV7tcGGolzY8nHrNYbkR0+BN4oT8EGfQv5KwtVLeztGiTNXYiWN1ehpQfgUNnQzhJm20y7hzTwnACaDJsL+lsSNPtjSQ6UeuA9hRs0cWGmjCQ6us8roREQ5N4BmoIw61Yi9EQ/14bX38CSQcktdDymXsemBM5Hq1zc+HCvVfXiFge4RSfLrHmf3aAm5DKBHOnR72BZH+kTsgSdVtM42UFR/FDollfCMptXvRe2d2
  template:
    metadata:
      name: grafana-db-minio-backup-creds
      namespace: grafana
