# Copyright (c) 2026 VitruvianSoftware
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-db-credentials
  namespace: grafana
spec:
  encryptedData:
    password: AgCMYVEIUSplE85y8Uc4z/PUr08lHroD+zv/vCJuYx1Gf56Ea0WzUeAgQglymiA7kh47Vui+RSPRfsk3AWpYkfNMYvhInqKfk16Bfd2gZ08tcUtmDPYk+c99+X0PUxGP8aN5knWQFWeDS2mi34MIWlAHHgjNOaqBEOK5i+ww+gb+S8DzqecBbIkEjcDkeES5mYcqyWEJ0XuOmUkq8Rvl3QmJdLwiaTy70Pz4OnE0OCePM+85gppbhQm6zkPDjCoMvqDzzhSBl+JBlQmGEfOpn+FYv2lecwTAyr9iCFmXi4n3avQjHWh1Kd3fdThwt+Qq74Nu28z3B8Qut6lu8GvsHVw7SoqhNdOlP4+31hGRS9rpiZOGSJ80JZxLTVKlJzXE0aj+djok2pYksaed/5OUO40gu1DiV5Nhq7kwE00mWnsGY3HTBgGzs2T540ckTPpcfkuSmSu+lsSm3U+NBUByvwafYr/LxMD5d58rqeYPJGMyJ+T5Cv5WUts8MCW8MmgRrWubpPov5vJ9fNOqJLGqIaBnJwxLSMHvwXvJ+wFwSanVstDioE+QsH2zamj8lz/aJmMmNa0ybvlyTtVt4ucf2dX61uY+2e6FiRC13C7a1pmC8F+k6YA/5hiv0D6UEhdlcQQ9+N53GzUFQOS0DIDZfsANIjaLhDtrczDcbGVHp+ncbzfwNFr533fDkE1iUJGii0utqmkYQYuwv9ypx3lrxCDJNp6VWaigYq6Z
    username: AgABYsjQfZwO/Rbd/k4xmSTtc6XMYF4boK5K2hOgmtfl926FhbA5v9fG68FvOCpF4YfDf+BES/Q4+xweSli+7BawJwaL4zMiRG3C1ln3b8wFIjNqfIOQ77cZLU1Q7I4NXl6TeXPmuzdGbW1SqTtgh6VWCvAvKCPZUBrDc6Swf6XTbBLSeyWpZYUzGrdXXA9LA17La9FKWauhJb0qNE1kEuT7voTdhKoJfi2JgcXS7A5CjNZBvBEz/axfUt++J9ruSfNPQAuwQBfwkboKc00oYcqv93BhXCEkjKFsCAenl1pnqonZAZga/CznLGDgEST1/oKwy76aO6vKycpk5V/8KsLX1ELtqwgDPWmXkN2mVjmvdqPZ5DZg4W0gdt+a7tiPubS9H7fNwWfx8qYBtWtFvGztc4ugEbt7P+3mMdHM5R2hkPfUn/Qnzfod3qjdY3mU6CYulzsCgGT3sy4pJ3SzHOIYyGFhwpnG/jBfYKjCNY3xffGxX00k2MfifPYUAYkMSlBCc3LQ6pbx2CBdjTYUss7EUF/mDHkuKzwYsSuVtUn62cXY/ZOTQZXT961ujvhJcfbuh/kEJSFg+uxupM5EsQbYDp5U6+h20okgqhlHZFAW1B9UeItP5iGTXT68qS8ZZIeXpjX+8eaIY9Djv6RV4l1Bbv2aZGrKfv95N/K1QyK0gKd9Znz2s5Z657aXGZA9Vwc4vCnrSi0j
  template:
    metadata:
      name: grafana-db-credentials
      namespace: grafana
    type: kubernetes.io/basic-auth
