# Copyright (c) 2026 VitruvianSoftware
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: headplane-secret
  namespace: headscale
spec:
  encryptedData:
    cookie-secret: AgBp2vWGNl3UiuQ1J/y2hE9mC2DFFpaitvozYxDgHyAhAAbycRTdpcUd83yk24Sm71FUTRZX+J/I7iPo2xI982+VMGviM5hyB0d/qlDpRfyQptPvj3bySMCkd/lneX2MazWYlXtTc5VBS/UBoNbaZe+WDkUyVBAKlsdqqWwR03UFr7GY6oDb0e5Y+fl6EhZF19QvnmM534Xb/ejADo1RPQRFZg75MZu0VXeRcvntc0PWN/QAu4zLTD9vJVOLxKiLT8EYlE2AhuE0bnU2Q31/O4svDlLhsMhxbtYmo2eToTHYlzaSPebgffIfjDofIkNMf3nxu0MX20fS9NrwObHbq8tOQGWwhCGKjdfnBPjEYN/n9w2BluR+7Biz/jJlS2UhuBDc0V8AwohFWGvhhFJvsd+AncUBlAC/jolyw7dRnF/ZRMKFlXyE7/QjzL/R/IN8dyc81fDZMxvoZ0974fYOYfNWRopUNRNJ/pGCT2/7GLnUNnvQ1iK+EHy5lzbU7N0Y+XB60otSKnrXTfB3t/2lNM/XbejuxW9600AwpLzHWKRkNRgSc35YtLHjtwsk3wMU0oJKHZd/o8i3Ngr6aPKll30zRgeAbLbR2Ly1FJFVUck6oNB3K5sXyEovNdp5UvPnDHR41x+nLm6QWfk1gocBG6ysenvToSrFX0N+1/dCGFxvUNcSKLLDng/SZWFnIVref9MCkDRaLKJ/3XAw3skHMosSlPUfJ5/aXqMm9u+2S8krUA==
  template:
    metadata:
      name: headplane-secret
      namespace: headscale
