# Copyright (c) 2026 VitruvianSoftware
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-user-cnpg-cluster-backup
  namespace: minio
spec:
  encryptedData:
    secretKey: AgCNYQZktT9pCgCqsAXZ6K7etZn1vg2XDhfYtdcS1g1q5u0Em6n26Kg1sXY+PGMUW64xHWBaJgF32yQmp3x6P1cSNrZh05klM7f0nHu1ycbaFtYQxJoxucsvuTzZRBFMwOhoKPHpBPVJ6fH/Qa3xCT6jTn0XwHvuEKe62x9w30a1U7sWe48ATcGoHTZhuuDP57PPSICXv2I60IjSUjGaIhgkBHIiJzRnw6fgp5ensHMsAzxuxQzesonpz1zUSSKvstHp6ZUCu/KcvKi5IeB7vxidt6f3sDEz0Pym1XE9bw9nNtZ6AH2HP3FJCAUaYFEvIiz/ElQ1fWaVgk5yURV9g/kNptfJrP1pbndZKPhOQRpt+ILKEma9RNlAR5YDvI+UcxkqvOk9zj4nOzQbfxsn0ni0KF1ILtdbIcPMRAvues373jv7Fu/68IxUb1wTUH5xrNRn9XPPjf5nciMN0vxNESaM/yvq8G7Ihns68j+8k2UKNLwpoZdNgq69RJWti45/zo9am1+bxgKuRGceYbbN/GLartlnmFASkRSPi4D0J0YGYy8x6QgVx8CbJvT9EKRBARSXAjREy3spmMQP/xkg8WO8oTG3k3Qc8aKXChtdfLMdEr8i1TMFIPUnObsO632VGyvvOsMMlKcCckXoTFUbv+L5yUuBg4IAuH49jrSkzU8bbOMmmOnRlc8coScPtZrJfCT0Ix5rxi9Jz3FYoZGF1lded23sp1FAEV9vZZ57Z3Sunnh9Q2NAW919Y8W9//QEBm8=
  template:
    metadata:
      name: minio-user-cnpg-cluster-backup
      namespace: minio
