# Copyright (c) 2026 VitruvianSoftware
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-user-buzz-media
  namespace: minio
spec:
  encryptedData:
    secretKey: AgDUhAfYQISOzlcAqk9tCtblZECCZz3thNtCll7lYQg5Du0/tj0CBsheyawOjF8AwrvFzzb7w916idig4JybslpMpc/z5eD+uVT54ut9bsU/rPDQw0y7Fe70gYXSu7JO1sWpw3unQSEuJLwCsRWyIKAy25iB/5uJhyot/WbviBwUDuEPiMtFPW+dtRSxyc+DihALRx7zrTl0zOravyF6hvhdrFzNZq8g4XgrAzJhfWc1+BoO4Yj0RzAVh+/VMZbFah7Me81MZgoBTLYz3/HrOXwAXgGH8oFAfAnB3GCHkVM4rfjH3ptJ6L6wYZoAHr5jgrmwcRKOolyVUsqHOEkkLA4W8V3X5utVP/TR20YbtVCyJ12Mxy0HecbaoEXhHz+nfEfXvNDONZId4lgmPWp1liqBgaAENe/aPrT4f7OqwfwLhA4mrSzphSqVTffGrKdfDL5NU3JE+ezehbZVNuGN7cdTb8B+WPhfKlL5B40zo84aau/VH3IPFjHraleiNYPCSJMbyUREgTv6Y7k4VLLqbZqWa49O+TE0QKT28piPAoU+EzLnd41cv9tMrnrCG799giRIOveG6E1knkpa09XtVnHDokS++xJsmUND1BKdTefzNlWjMHR0EpBRIyD7DNu3skT88KGAZyHEsVF1Jrhch4gymGPKtxBBh6nncEmcA33AdCC402clF3GOJr+CaHN7EVmX5B+54j4aQwYqKAb5t9H0jkLnI1DI2Gs=
  template:
    metadata:
      name: minio-user-buzz-media
      namespace: minio
