# Copyright (c) 2026 VitruvianSoftware
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-user-backstage-db-backup
  namespace: minio
spec:
  encryptedData:
    secretKey: AgAfixdqEfMdeS/G/wMBCDc0GFRk34gTa6VeQJlrLO2xSOhsZB7QH1ZFS9Nhj7fQApvx5Sj/5sPT3jllELMbdHKkeoyQ4bN5FjmRYd1EZ9RcA1f+l9w8jpSRy/T0UbE3MQA6oBsFOlB3M0U63yiLFyeypfxgesM21tz9Oh3O90w4iIK3Hp+RboXloTQjuKYBgCvMj+czwrReHnWQItzm9EStdKrb060ZqMPvCJXN6/zGXXoai2LSOuKDf8nqu5M2aU9XHR4bQ2XB40GghL/XHgSEevoT1IasYfV2rS2tq5CeNtZdbs+EZ/xxRYeuyFsv0FPnDiLa/EPciCN8sfcfXIkLNiBgRHqqmbr8oMd6mUIKzTnPr5h4ig/C+IIYHsf7j6sfKVe8moeG3BicjHCxowetIc2ntP5T1GEndKfX41RV/6W60f4Gm/aYlslkzNq8aBUk2Ft0YxTZRxKpe95SqcXh2TIo9tFWCE+tBZujWbOSKWxBOGIJf8UiEQoGAf6nREJJkRV+ZNK4JIUFNB+egMbBYMyv+NUzu5j1KNezRiAheQeBzwz2MriYrBvtXIlJ8ADeIANSF93fqa1SDmYLTLkQHA1cFdP5TUtddj3i4ifgV5UTdznI+ejSdYHkAaWKjIrsNMwX5rUHn1u6yfe/pwITIsYWpr2ibrA82QQjLvia9/+SqxYboZnWsQFSVkMZFtJDOf/aGB3Pt5XwGA46/mMpobPzmn/PAhqeC1MoME5C3V4Cds9XUYxIstU8049ef5c=
  template:
    metadata:
      name: minio-user-backstage-db-backup
      namespace: minio
