# Copyright (c) 2026 VitruvianSoftware
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-user-buzz-db-backup
  namespace: minio
spec:
  encryptedData:
    secretKey: AgDNLJFWF2+baSKJl8t7BqzUuxyYV6RacSTSCokn/XKcG3yuKMKCSXoeE9qKLj9LGzRXkuAUL7WDKCD/kgu0mOVNhOSCKyKkPzgrX/u2Mbcp3HqD1f7SrJJ7FnpqavKaOEMcSHKHQzWaeRHeDanFEnCGusHb+9jwIUYQivkyGow5ef4fQKEEBZYhj6Pts5AAd61Ul0Yfa7TOKmLOChQw/iNPm1aIWf+mrg9eB3MBIvOr/Ibt3I8o0NQiPI7Gf1dbNB8ob9EaatkaIR2abi7jVVjzDpiR/QvaGsLbXEYqHR3qreXsRhtsCDVJ5FDd/pffk2IDbzF2K+jcB/Asa/ENfIgGIAFl/Cpv8uAyW+ud0AH2Ohmgrp8Tvo7ipyr1hl0GSvz/U/EfrW+0m6ToKrld02dWxIo96jt1rJVffdOEVe0xuEjmh+3KQ3FI98ewP4Ot7Iaz1SJjUFXn7M3LY9Tb5sjq1nhnD+9oXI7mWtZJM4D7oZjcOhT1GKJ080Z2IjnbV8XI9GS89ixMujiYEpsLS/vRhXkygg+PIyG07Y35DTp+8pPurmr66+Ecx6XOuswmXFh9QxRAgGgleK9wuyllB7rcaMMyAlsmdgFBOHOM+5sy3j7nroBHOpZNkge+/Hlqrx3ZJcFM5l8oseXgRWI//VU+ABVbMsa+fvnkrPg7Km9WaEcjNjxrymiwpSI+va2ax+yuhcExVdLorQuR9eaCQ63ztgQQ4iD3MG3XGQGoOmlnNLGjSYqDWnOFFii4BJ3xohA=
  template:
    metadata:
      name: minio-user-buzz-db-backup
      namespace: minio
