# Copyright (c) 2026 VitruvianSoftware
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-user-grafana-db-backup
  namespace: minio
spec:
  encryptedData:
    secretKey: AgDS7luAskUXLCJB929kt2aFk5CI5oWRE7k7JHPk7Y8VJIP4kOX10xd74O0nD3q9RvkJ0BhsmUxcj0/8q6FPf3PVMWw755WfjP5GN8VzvZtiwtHk4QhZupFK2FQ3Insl0Ag+icvW0S6+ir96MOWdQJmVFmJbWiSD4LkKFaVVXa9kENJUYhcPs36ZxHukGKCWf5c8UmIE+U0clZjPa+y+GOP+f9hxrEBbGypqQudOQQVf7z5PpLhb9BU0e4kzNFrl5FLWq0MewcSnLXvtKZ8gWMjyShrpYqhuJJ9/8NJR3MeGAAU8qN19d+gFD1pxskiaI8R2PH4BabIz2t9vmcukcXfo87VthuNexH4l4bI88tn0Ubd67M010Zc0GoyBsDLUXkoH4G/0srSPcpjrz5alP8BkgZ3YQhgorWBLQdUDRSSMynYQZkhhAak3gtFbsNmO7hwal3gZKMozdsqSxEMH1hgR2k0sO5nEAymvYgTh6Jh8zjujMKer/QZ7JoQHt7bmHuzEJUXdMGKsFRTriW34MC1BbmmNjP8galyCrAtqTJbBA9vFOaqLE0lxmCzH786OtMr6OcD2RdcCbVoSDyDjTFa2ig8hz4tQ0iJbYiaZ9SVmOCCKfkkl4EHV58aPf2G856h5iMhLIL36GKbNLaCtCzkLwWWIz2iTV4h5VIgUJMSDAw0nnDe7UlcxkJQeAdrLtOsfdtjKlgiUOmQpC1SwvqAee95xLqJ/5Qj0C3EhWM3CnMLNOqQKz4+Ffp3vt319YBc=
  template:
    metadata:
      name: minio-user-grafana-db-backup
      namespace: minio
