# Copyright (c) 2026 VitruvianSoftware
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-user-tempo
  namespace: minio
spec:
  encryptedData:
    secretKey: AgCZr6aSuuXRSk8QgCNt4eRiYbnzBBfbzRUsqRQagT+Y3WN4YPyvSAshMotC+V6XG2cal5eSM9u/CcJG7W+29m9m4QhaahoMy/Kz0sQZgnAR3XfyjfVLbXPpbMte63TKkBc+coFSeZgaKTvzZuezYZuSVGuz3qbbIemhBL5zcFpFH0PZSFq2PmkQduXncfCke7cMMB4wHmFnpimzo6ugNvWnrsPSyjMtb5WNy86MutT7TQDnq0LQvOGW4IzrhO7Ip91m4S9fsRung08y417pEp3D9BthoCh4Ci3Dbm+R7rYw+ScA2anYt9/8KBEjokYXKNx06ZOQ3PwAKqTM5kNep4jknjvDj+8pSxR0G8CkWHx6kz7Mbe9b6F+u1Q4rM8+nXIUZDVqt9g9/DsTIYFrVF64AxnqiEDdDOx0xUE9JmRYXZBdS9NhvhGZcUb3J9+kU385llgcZhqCC5CCZQF46Z0elZ+ZCAtng2XYH6Qp9S9rM549PGkEYlQou17znENGH9/ANECMTc70EOyK55orjnLBUQKMJBNZ1oJUHR1NdlJlQ+QDaTp5S3zEFWPYN+SUxkkNLtNUiOl5qIm83VW+1SdX/KbeCbJ2gkaJQJEE3hEtcKb8rHAtfHQSzwgJnGXISK5h5Dtb25iY0ZpUxcLSHiWKB0yoL3tAngvasCvSQuvHERJpWW36pmMELnLwDWp3Ycmr7Bl9SYjfF6iMF7EayUMqPl9nOQnI22peIbUllbSpnGtnxeJDfSi3HYbP5UwwkvPc=
  template:
    metadata:
      name: minio-user-tempo
      namespace: minio
