# Copyright (c) 2026 VitruvianSoftware
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-user-thanos
  namespace: minio
spec:
  encryptedData:
    secretKey: AgBZgInWFxFOHDyVlvTaYg/hZadRwNHW98Cs4TiP9RVtcK70OVOgWYSme75pGsN28Ne2l8lqHauOAkNo4PjQMhFS8Jwc70OgK4+Hg+taTWf3AMUC1jCcj8yXgvRMxUk9H153t17VZ0UyE2ep9P6J4OJ55ukJKpwvAm2NtGKwXHuAZ7X2RTu11pPzZAMwLdaCG9rZXeThNt3qL/na2JpbrGG/3Msz7OllRFf5H4XraErty7/J1DNaW49lrQQmGqrJcJ7V06pSXJbNLDRrVcXpXAWgQqY0SaLwON1Q6FlV9PC0FpUZSpRI+Dm+hSFfOotbXfbyRMyZKgCvF4n+IxmyOPN4IL8f2d9/VlwhCPHt8GFSVKMIlfqOk/ZF0hngLKHFkwassRCabyfZKiDHgT6B+uZyVJlw0mWkq1uXVQPS2kGW+xbh7ou0Wzh76n5N5U6fmqzW33FXxpVrHogX+bCZrfiHi+uUoGuIXf2hBab1dFDJuwzP0A6vJMBNmzjoEcBzgUqrFEOHjhAr3RrCbwnq67U3l16g//Gplh40fq8rHmUIz+VcnqD09mcAjZiSfnLNtYwRYV1K9x8adrC9nEB+dW0lfLCIv2XdNYZ+FEXofd7anQaD+8Jvv9ajbXBFoJwGJWgbuxQg/wsuVMVNVYG/tLysthUBst0FFvZLQnpeb41Sa3SGkQnRSmQl48RYNFKBmeP6r57rVAiK8tSuu9uNsCZQPPOcJpsUJOOW97J39LR1A9vzGhzoCazCDQqghjWpDXI=
  template:
    metadata:
      name: minio-user-thanos
      namespace: minio
