# Copyright (c) 2026 VitruvianSoftware
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-root
  namespace: minio
spec:
  encryptedData:
    rootPassword: AgB5nXQ/VXtoM9cud2MkHNnClJwNHRHtTs/n50YoyXJiD1NSUlt/JcCArWi8LEzHfIxLz86snKKsh8d06IsCm4/kLVaDldSoOF7gLblCWbu4/sU4Qs/h796Djhid7bYmxcEDPqk7+b0oOzgRk3Z3L5dTovyxjYuL9P/6dHwXLaVU9/wD/IQ3HdD5YRwmkdDw6Zy8+nD0MTQeew0x080GDLAJmWTzMSPk/o82VPQyrjUyYI6o2XXsfSUQrxqu9SmgtYEjlAE0PEAeP7Qrn2Mwz1Z1x4KUsLQSgbfBpFPGtgGfydw+TVjdYpJOjc7PZgYDIh9LXCyqVWXGzUp/wfyI1nZJEzlLFL1daI+5AckIgWTEZvWBmEiymjOtZeQ8Ii0lScr7Gd/G10MVrUHeZWOwp9jgZhh6BaW/kZnxrltcJmPx4D0WcXkeT0Tq74NbNB5yIrgba8cIFahMvLwH6hzkjoU3u1soNSsUc/0QanSoh+1RAsCGXk+2a1MHLgi7uafYn7IAuUS3e5Jp4aN0uGnd+PKxyY2VjwkB1mLXP9zlQQyuHnU/0cc9WgB7uaeEyHNRinnaOSWkyOg4FqLo7npYqPkg3ilnO6SN79rbvLaEOTDtRuvValfEYNvoGyUpU2MOhR7BfRhvUnKD4+Z55NdvlhFipbEHKFALB0VpP0hS1L4eZJDF7XWUA7y2n5np3tBrdzp4iymZR21AU2GSNdwtfWf7nEPSSybg3sqYOF94lh6oSICpV5Bcc/qs
    rootUser: AgA1PxKvyFG9TOU1aBKIIoJFCjZvTJJGVQ/sABMDWLe5tE9U7EcIEDlkLMUlWmGTXoJrptoH2SlUfmZZh7T+OSn488PMKwafpikymnBe8M13hjqRjbpUcW5JNo8lTeBqDxyGm9YrlxkY+609XIfAB8r9vHucVioAKLoGbzcWeLtTDQqoL+K+3YQP1FnDTPureclaFJAcU9uHQMfUGPcOUcHUS87A3+1wXYL5vYHUjfS+rn1/+0fuWGjXZkt5JhtPNjdGi4M+dmzCnO/gnHmrpdd7ck3oBhohSx0QPhmvwiEfUkBfOC4Y9B15p9RD0hafzTonGkuUqEh9d6IhFzfNuMMbRpZG6kl0lnv7gEKjgnqi+A2ffh3w5BB7wcRp8cHTDfLnHUHdSucq2meJWT3r3uLBCpZpGxfTyB/Q8BySuMlabvRfX5FWoqVXo3ubWXwhq+gxdtGpXMv+ErzRy4vf5F5e5yUmJCmyhMWclxQ27QzDeDvxqwrECdtpIOKr2eXzXxCsFt14bT91sVecnZ02Qts2tQnDZLgDaE3AOh7ToEKVkoSCVgs8dfCz68DdHT/8jEPJRcZZKFM8GqA7WpZHBu1B5kTbkqA7F8d6cQE9NkWAhXVRR5VWN25NQEpNdtKqa+Dj4uxxoOrj95sHyAmX8/H8BaDIgSIC67I/SRShTr8qTuKfT63pR6l990yPzwjS2bvzpOEMHQ==
  template:
    metadata:
      name: minio-root
      namespace: minio
