# Copyright (c) 2026 VitruvianSoftware
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tempo-minio-scoped
  namespace: opentelemetry
spec:
  encryptedData:
    MINIO_ACCESS_KEY: AgDTdZo9MFSrAToDO/BN5AhKTIoyY21snegXS9173MM+wOqhBpu/HyU2zeGAF+VnXcJh1IXv9qOk/Tm+m/js5O/hRA2OiNjmysP8rQWk0hDvFTwDoICy0uu8CQus7voVDiFzBlZ6IDBPN15HLeL3hcbHjAydkfNbVm5ZsDWxCtxXtV4karGcydHwVMqGQgd4Rd5FK5igEeimR6LrB3KEDqBH8SZ8dTA97IqXdEXR3yweuOMxjXOaHx/yo58cdiaSOVlzRYlC/C3jICEVlrb7cktpANxKbT7/ngCViYAR9iyTne5B5H4iIOJoQD0F2vxeOikTW/fSXRC+PS2m/ZYGB47jytgjVCix77ejuhxWhKUkaeJSsTBhU/z4AIkeut4Mm7981yaGj6Mr1KoO4LrbmqJ7SYwJ0DhEeE6C0Y6YOC09HWlBx7Ura8cdiioYVEu7ExYvfrrSoohKdjPbr3ykUFNelg7bBHc/bax8CyKYEOXjI3h8y+2XbbNsuRKYvHICVld54aOGffahmEjps/MptYWKkSCTdOOzpv/wsPPSavbGo/FpkdeDPJVIW/Mz+1ccXagPUt8vaSaq+jPHZX2TF6XfmbEyLRsyJWGodxetykH4r9pZuuHS47RA2m0StQAnnd6TYyRmw6EVLcZ3s25afoxxQEFUO7XW0LJS0qleuxcvPqF7hv+MmIcJVXKiEE6gMVdiiJWb9Q==
    MINIO_SECRET_KEY: AgAH4KzR+Gce7ttJPP2dKoMUpqVbwsYWjRSXAjHsh1HoxUFhIOjQAVNPO+pJHaUMaQkMnX89voft+Dmcao+/t9/WP4/Hl4uPKvBlhZPLxovRhAQ7e6syI0Tw3pVuGozJfoG9buCRDmIYpLvpmQr6hNF+FAs98YtS04EwoSkZYZB495qMku9btdYMKgWHxm7vdHxxm5yNC0Us6iY1CMFP0hevpr/LnMd2x13l+8kn/R0ZOsd+ZXvXwisqQMBLb14SzN9CdjZrHvZrO/r9ctN+rGYtLWkW6KVzxfitvrZ6P3KqOqMCfeLNUDB2nCtOVvyGDzIfi+52QJDo62asKX0VC2nxWWcpwISZ0PE8xo0M3i4NcSCB4PKsm9jfDOanpBlnuAmostibB5olYu1L/r0IIGu4WtxkB9CB9Sycfr5ItSbNSFYKaXMG/TQmqe4OqvLdjHVi5Kdl5nDyIRC0EzX1P40E6E3v4bK1kSfOnKaefnclD64BfjvE+ki9NrNE0rV5Rl45WtTRKIG8sds9IXt8WeN2Shbi21hXPS5EWwTk4mZZpGzp6FKoijSKjSD3/fY8lo9qazRh6SUSnbFjylzFRWghdewviHCosk32ZXx6CWh4kvQLTFynhxUwJemAolZVWeE3pelTDuFouqf9SUG7mPMg7WbSqbBTR6wJP4YYCybhQdwMcw+TXcnGNZda6YGolk1+WT4Hl1RXx2YPjSivjRk41G0nGYiz12F6hqTjtkOOx5KLCJZ9UnBr14/d1DJSnHQ=
  template:
    metadata:
      name: tempo-minio-scoped
      namespace: opentelemetry
