# Copyright (c) 2026 VitruvianSoftware
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tempo-minio-creds
  namespace: opentelemetry
spec:
  encryptedData:
    MINIO_ACCESS_KEY: AgCmP1VOgRJYk3IRhzu+84LluPqeTcwmYqpEyLnBo1nxGdeXaYYAIHB0Oi2RsoSBpgL58p1IB8On2ozVziqp0OvGvd4l4IPdPDOikAHbfmv13Q8xvbaHs9+XdL1NMgJY5glVVUNDqdoBzztUIbjMYHktmiq+LM/zKG8S+79rNPFkv3Rh5RtKm/ehdaWN3cdCoqq0McTsCkWBNvr2XHX/6wEz8nZI2J78kEPoM8KBAvmpZNri40/WpOS0RgcarVz1noJu09B3y3gInuHdSvV9ucFD+xXAXaEqubZCVg3FnBaC5akBi+hr8HY6hw4zPyE6lyP/EwF0C7Uj4QpHxOowV1wgeZmZXN56vbrmFCNIfsXaTPZGFGIwYm/7jinw3PLowUEXVfQOrvjtO6zDyvlDUDh4nU0abvMH1OT2qeRiWb3DSucwvfmhHcBPdEarV50i9DzBOQFMmZ18uE9WNwOT5LpTjPM+oB+dg99qhwk6xMWfcrxRYhgEg6kOU6VPk2nd75ecgb1UyDqXoOmwexOd5Zi+4SPPVk/X/HPtHN4ZZhc7hTHtLYtVKlncqj+Dexz01KgK1/UQq8DIdfY+N9UE5jPHAkquszHxHZEANdfhDKAW37wbeqVLSsNWgoPHzVyOY1Ueuo0UHDqpmX/hAqegWScgRq1fv+hldeiiJIaFeT99B+nkm/ODMYu2xylcJLmVifzWXvLdfg==
    MINIO_SECRET_KEY: AgAydkx3UbBEchBEPShFxL9w3iPnAXo/SCXEHSRQEqlLjh5awYZHzYo9LKv5lAHiUeC1OQCdoCArJctg3E/w00hwbNxV/LEF5gHuAHqDkrpjOjOEJ4/FDBeqsvueQmOSaSiLMQPc7VlGFiIP9zIs1taRnTWnUETaDlPah3ZquvCuYEmn1RAThZQJlR7riUOtzyZj3cbtxuCcO8IKfqywQVnJyIIjBw3xGW8xzxCNN9vVNMTxnN9gCM9mu59TlVgMoZXrKng3iJ6n6tdwIuNBw0Na04Od0trc/C24iELRjyCxHi4IiPheUs3CpICghdGlFXwVFar49tn8C1VeTuX9WauivKAod8qxijyN6i4lITGWEYny6poHH0J2OSZqYg9ySQgkw/BonHO6UWKUxBeKxu9eTR5RDZxooVdo1UXFCn3zOG7Nr8a88LWRrkn8wZ04FGbeHKxpAcxVMMIudDkA0Xb2aerVpy9ei9lejb1UCV3RFlPgeAb7y9LL8vdRmOlNT5w0DZIjyI5pDOij9NSbtWeJWELM7gXiCkNcVCamsyyz2ctBjH+ABaEqKGwjGxur8Op0ehNnYi+rKWF4Ndyazz/+aSxgNo11VmW6ZqXvPa1Th57A2xezXu53DVfTcS5wQRDN0KHAJlpHmzMnW5jxgF0OTVZ24T/NvNwdILCfBugrM9pd7bHNfy3IPGbHH1YonFfwm0DA59IVclnosceO+X0N7dc5bCAlPrOPlw/zR540/Qvc+QbOt8ru
  template:
    metadata:
      name: tempo-minio-creds
      namespace: opentelemetry
