# Copyright (c) 2026 VitruvianSoftware
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: thanos-objstore-scoped
  namespace: monitoring
spec:
  encryptedData:
    objstore.yml: AgBuqQEi9fdcp0nEFyqoSbLkYp4+DdtNMGtD5PEwP/uhZ+C+N0CKp/3gY2QwK09k1K4lFd5ep/8CejStO8LuJZkXNLDLywMQT7IvY/QKBeg2b9GHQYUGNsv2Pqn2QLVaGl1Uj+pQkvmMQyfD0kDsL038a7KKVeGDN5Ed8qoTjCzaP2CQ/TAWuFXQr6jyHqER59MLAUtQ3orXk6ZTUlFFP1Kh/0lIvrvOLdDBWu9Xy1QVKvW7HPkIcJqWGbbRk+szJNZsIRdVX9m2Kuig2ndLC/HAzmWsJdbYLWN9oma4HszjN3wusZfZ+DCMUtssifJ6Wl4Lvi3j4zT0PypcfSjbZ57KHZS7nQbjzjQylTlMJAT5YFmzQsAXHv37DLn0NrTYDhQlFRdafX0d8CuzqxcecSd+kQ9sd7q2AzNEd0veSPuQc5xQX8EuE6oHevOOD20tMKue5lspTL978ONo2kaBkLWMlvqS5pcQ8XRI+zMLYHbkJOFSjNWZouHQBvq7TIVLYhUncjD/NlWhhc+Bs6865bdZuAP62rraHdsJEmGn2doI8BHkOXwxv+poyEK4SrsZZ7pBwLlRvu346+VZr1uKVkBfTq5B6UZSkF4qxLCu/LyF7YF0ua0Cu8OBLTLQFS/9JCc0nlqqxIma5CTrfvm2/FkGL/9tJNHw5h7P+qYnJcMgxMnPtOzW84ofO5lYxTMcNPAHFyu5upeXSM97BbbeqpqlH5ld/yQART8/NPAr6OjHoy+UbcRSkt33MDXL7ExURqmtXp1VuMmwdcx6gi8YNQxlqkuZ35pFxlZRJwDxZbHA910bFuuh7es0U/7WRhxolzzVEAjWq8xW8qlLAn9lvVH6wPwiGZ81A2WD7rwmLkfvRsooAvS02D2hd6xeSgo5GJtYMdjG5ghFRDopqohnC0GcqvkhcDzAVzde2B2rVEa6HsPd0BOwzsZ17kpQAg==
  template:
    metadata:
      name: thanos-objstore-scoped
      namespace: monitoring
