# Copyright (c) 2026 VitruvianSoftware
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zitadel-db-minio-backup-creds
  namespace: zitadel
spec:
  encryptedData:
    ACCESS_KEY_ID: AgByDVhK0T6vOmVcvt7IssRPqPkyMPy9AUax6kKt9xkX7A2+OYI5J4WeYNCdajo+Nhfn1xN5dEn+rdIHab7JgAXYPka6vJOCJyoKdLuyWw0JE6V4RRM8NzFKubZ+J88xX6VCeoCnPTxODCfchRgAhuWZXcU8P2tthfs55PAl87iPE9rjPxSGJOv0x0/9NF8gciJCRkMgFr7YebIa5R3tZsDGZAmjdPXRJjv2McATbX49EsOeAXK4C2FuJlNk0h9GUuTbQkg3DIpE+RIxCMV59ZU6AwB5fQfcHtFci7HDU1j4UkobIk9Ax28eZvmG//9O9A6drBEsgoJAqXxv/SZ0O8aOppNTqHyT/9DS8rG6gqu9FY3XtumNvbOuq+Cm896zh7WjWf7xYZq7nJ26N0Xi0HxfCFBvR3NUq5MSkw1WCrpm9Irtz2dgOB6x9B4FOmGtaorwsAskqFctcatWxcEzR42lEl7nkvhv3WR+aRX6koDpA/otnV3SNIlbVuSktG29ExdqLbtcbAJKDhky+uCO7XIHP7MhpqU5REhPqrnSxOW/CaBgHTieX24jmTduBlEC4DfGP9Sucoa4Kd0ozG+0keE0E8aL8/9cDGs8z7XBpU6cUk7+c2mBzxdqzXOiW2vE9FT5+gRxcNf0+1ANb+vl97PQm9k40LK13eCvdvThjh1e1SIdRzDpzTzbUGYh2UQrJsKZCSi54g==
    ACCESS_SECRET_KEY: AgCs6TgT9qt/BdagqEVT+VMm9ZQ+y0l6IKI6QOSVItRI1QA323wH0oFz2II3M01+4/g6P8Ifc4CqynGN19m+9cENT5UTuF3dijwcjOKNJaP1yzA/EfE+iUMplzNfJ8CrvDBST3FIBxZwxzYdkXCvzBZ133o0BJUogMEuKU1z00ck3AIAz34CrLeDWzTtxUWgnkiq2Kp8W3BFl8Ax45AVDep1jSe/D/yFAChOagIrz3WjBUFHAhndUA7BzFAMf/exoegxGkeoCM32VAqNSllT7nv9jwf4JDLUaicV7HtxsFAm+MvJtMo+Yt6lhdZ0a8QZhoHsC9/x0DHR4I5pfI4a7OhIz7oT1PUW1GNu9SwD+dFJnYerEbkASGc2E4Mk2cuQ1qB0d6CxTjPtlEANzE8IR5fB1gPj+KBgbkvwziBmDonfygqX/IRjmNHHp1rsCka4cYDUxor3Ua5u767HCl3gFE2mUejEGQEhZnJmnkp7InWKRct4SnwgYHnPf6LMQvOlDfgkbI05Ari2UPNQ0rclJ/+kYzAwn/e+AISRT3V/fFKfsyMurufgdZtv3gePD3Uyon40mI4M97E1UfLIaSZtg0mUZP4WO1XxkrtbyCTfwJN7lZEdX6Nt3oOyPMZ4/40blPhXaf5PyP/NZtAIKayp0JEulDhpYaHloFv+QttCuTCaPosAxSqDI7wxHu7MUHrhCTX3+edxKHONCcIMxrw4Uw2bpK4bm81Br89kWmBcyXCpiUB80rtla5lw
  template:
    metadata:
      name: zitadel-db-minio-backup-creds
      namespace: zitadel
