---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zitadel-db-app-credentials
  namespace: zitadel
spec:
  encryptedData:
    password: AgCTjDqRLlQIb+24Kc11tRg7U6NfuAcHyBboOefYTVsZgTa/vAbtP8Nx4T0ncv2GIvw1B4rpGWuxbe9F71rYrQkKTqB/E4RuPdbkfto+Lmp0bt2HXbQrvzDmc+0ShJJQ4fdWcStQbQhEqdyjCBtJfjiRbIeH2kBirUvL54TQTgOkIddHVGt+dgac6nZlvBP1E8ZCTp6JQKB+ZgPDSpV17P8Xb9K4BCEi+ZfCdebgUSgrRKe6CAQHBjNleq7QSPmipia9HzsLuyoUTFpCiithE65jVtN2eL/u57aOQT9HlJyfu55Mf+9iUN35+p3ReLczup+f0LyciV6ThbtWakOnrF+WkjlbReQaZ4XEPnUpSIM3LPaC+F965Fmhx1jxQPWRqhE/DnLZjpxiA1EbfQ0gbI53GmMvKb5k2NAGEnCire06zc9Irebs6Foe6UZ3jnQw3oE2xVnrKGSZS1SF0RE4CGAhS5Ur43GuSKFAbzpEM9iFaqbc8Z9OL5IGTJA463AV6LTQNgfgZ7E+WTTiZbx33AUlyee+XDlOytFAbGbo4mdgCAmTp/ywLz8gYWaRD17EdPsk2CPp7s7ftFy4IFpAOKLqvNOVUhuov+u4BVkoGyhMF2FLpOTH5VyVe9oxXSMDnR2MQ+7mSA9Qz7ksQG+TPzo6OOCM54Am18IqDd+OFtcrh7ei7sZTYw0ruhRa7/4DFm1CKmDxRLCxuJYnjjJigOfEttTrJZJ+mhvf6dzd
    username: AgC6GFZs3MK9MFrNvk9wp2ghP9zz2VUIj+W0tdCubUQRkIC7gY6Lli/9zqODyMzD/zHgb1lT/llf+jsPbYankPtB9+KtFbxNut8j7zD7wcQtZ69BuYEmow1r3z+pzUMrMUsoe87qTTxl/EyXSg832ZC/6MY+kUYPjymh0EA7fUulYbzE9jOBeh69UZalKzntM8dXkB73tKAjAnOjLv4KpUvz6CDSEkxHZGdOHlcc/1X6WMCqGjoh8GzClrZyOHm7/CysZIbHAV9kwdjl0bXKAdEfEvv9KFfkBAxFRfQdWKBxGebgzxspUvHbWtbKLQv3fY1kdxDdtGoyARejGE0NeAKKK2aQjSxdk1OBK/1g/qr6NDXt+lAuEe3kwXyNGvW+St/6V1VNPRghQ1HYbbwhv9utY8ylhvcuez+wT5n6c6sD6BreM8WHoDM9NJyunopdOsucKl6JKJfF2tGP8r7njquFokv9Ii/Y5CZrWXsAUBrQfeKk3eNdjt2AAShdaroANQBP85uf3mDwaWdRWkeh9PRlVJgCztWimIelQDIQGI/vUuR57aE63UIbpbRP8+vg5cguuaT9HHOhxrgOxeL7LiLHRubtZbcSS7imdVV0POD+2T22ZoIObKRuZnHhxJ4K+nHCDq8ngmBMKs3zLHb5E38s8zs79xvWlebKCPqnCMt8GKPwWChzFWEpVBhxBmi64W1lDBX0CT9p
  template:
    metadata:
      name: zitadel-db-app-credentials
      namespace: zitadel
    type: kubernetes.io/basic-auth
