---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zitadel-masterkey
  namespace: zitadel
spec:
  encryptedData:
    masterkey: AgBrXtDNs9UsM7VaprwFWEtTyESKfHb5mQLW0Pp1vE1o00Xu/n1h4PA7TL9kyum+uN6EXhkJguutTTT7tZwzYBPryb8pSULfYrTwmZjZqDOeFfSqyIvOBcBgMgI2hkouwMavB8N91DxbLsECBxA/ssUKbRdLYfAY61Fx5K9MUtco60hVWXG65s1qXOsGTGUSlldUt8pGwfvKrmTOe5HDYebqo6zatOggsiAfDKsyIIuKHSe6lbli2TyEo8BAcNBWVoHuhIQPM6FHaN2hjOEj1a6JELy61yhd/jNFREJ2RFgW+0IW50jOfm2tkO7KDBAGweq3oDAN2rfJezzyJFW+5isAp7S/jiu1Fj8E+NdKzAwQVZrW7Pq7Dyf1GcB/JBrAS09auaFiNL2UrLtv381v1+TuKYcdtetV85UrqV1qs9xrW10kX2R4gOS8xXgCsmU8ZGHbRbtDEhBYSOGcPiQ67Hb0WU63zhgNwTEscb4Y9Phf4vZiRh+Dswm5e8Y6MfEBbftz0MBdkN4ltBo1D3NSvSyGnOx/Bt1m1wSeAwgYAKIk/+tO6gwi78lKfdjz3SRF1ifTYm+PbuoDlueRDRc6WMfH4yP+ZK3VhXIU9I4IFc2NNj4uEeBWM/RFeUduVt6ACmQHyr9mXF6HFt0lOIT/K0ltz30AMWD34A8I0YtN2Cs/kqjCLpqCZdJe4eUnhXHGKtMp2+Ve/gjJ44CwpzHO/g6r8USQIMQlce93L7Y3n/8f8w==
  template:
    metadata:
      name: zitadel-masterkey
      namespace: zitadel
