# Copyright (c) 2026 VitruvianSoftware
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zitadel-secret-config
  namespace: zitadel
spec:
  encryptedData:
    config-yaml: AgAw1To1850ykus9jzxEM2l9GlnnDwT+2UNpxw1/FM1ALDMbH4e0ItEgFiLADSWgMnX/XwN1yHwyoWoOm4qq0gr0+AqYPHpAy2cQN4Ygu1ZkqVk5yjOup5xKvOZ6Z/J2EnR98kGVmY0n4/VnfxqE6+Jmigv2DRxwMMvtIZDnoXPGHeyCOpUFZxtVuJdriT47vxRt+9rWWmG4tIdfhlClkN36zKZQ2OhwDOyBfhpDE2UmC+M5HMSC6/ju9YC1glmTDrlTTwnLmeqnrtlEEAZ5erc1auzkdOllJrgf0NGSTCjdZyUkK38B5qZXOvHrXjZ2YgnsOcVBd1b+Kw9Sg2fzhJOpzcHqt9DrPxbBGvLxwDlPrXbtJR9Gg/0t+YCT5X6h55e1EQmi0ntEMvMl7yNRM4Pwf36+F3py0H2CvsJsC0QmvQM+LPTMmbyFeRD4+ooguVzwX4+1mpVfThmYNobku9qbIrjNzE5a8vKHSRoUl78JvFiwkKIo3V3Dgg5n3B3EcOrSEE/UfcBmeSUDUiNJF+tXK/15p78/9GxN9mYI8W2B5bcJrh00Wmew5JgjYArxR7KTMlrQU8Ds9sek7fSQmXqb6PtDCCEGD+rsRw4/0v+bA93plPlsmNAEiJlg6r/Vrac8RjHxgSAktb0wBsg55bxzJzJvE54WczdKnIeCjKsjyhyIej6Rhv4R0BopzcuqdOjzlsLT6bn7LBcc/ENlGqoy/mI0pwAoHS/krTm/RfOhyWlPWzYf+G55fxf4hIzFPB+ZDdQ8EgwcdXitEJAkavErOLf2BWTObAoZhZqkV//i8uD9T5zUNMkD+03WCBwDirMpg4jJQFDs21r9b/Sue5CwpBkBvvK6xoikhTwDCa9XaQ1l/Z9NMSI+LP8PDWqarJiYdXitTrYWdfPSUL/zsN6Wxc65BV8nDQxTkAa0BxHAcX6HAdvv0MkOJZp+s4rKO/GnalGe+vSjjc2Lq3hcCKmSiuJI8SSw9sKCrugbew==
  template:
    metadata:
      name: zitadel-secret-config
      namespace: zitadel
