# https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-operator/values.yaml

image:
  repository: otel/opentelemetry-collector-contrib

mode: deployment

replicaCount: 1

config:
  exporters:
    otlp:
      endpoint: tempo:4317
      tls:
        insecure: true
    prometheusremotewrite:
      endpoint: "http://prometheus-server.monitoring.svc.cluster.local:80/api/v1/write"
      timeout: "30s"
    debug:
      verbosity: detailed
  service:
    pipelines:
      traces:
        exporters:
          - otlp
          - debug
      metrics:
        exporters:
          - prometheusremotewrite

presets:
  clusterMetrics:
    enabled: true

ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    external-dns.alpha.kubernetes.io/sync-enabled: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-cloudflare"
  hosts:
    - host: otel.lab.ipv1337.dev
      paths:
        - path: /
          pathType: Prefix
          port: 4318
  tls:
    - secretName: otel-tls
      hosts:
        - otel.lab.ipv1337.dev
