package cmd

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/VitruvianSoftware/devx/internal/tui"
)

var rbacNamespace string

var bridgeRBACCmd = &cobra.Command{
	Use:   "rbac",
	Short: "Print the minimum RBAC manifest required for bridge intercept",
	Long: `Generates a ClusterRole and RoleBinding YAML that provides the
minimum permissions required for devx bridge intercept to function.

Apply the output to your cluster with:
  devx bridge rbac | kubectl apply -f -

Use --namespace to scope the RoleBinding to a specific namespace.

Examples:
  devx bridge rbac                    # cluster-wide
  devx bridge rbac -n staging         # namespace-scoped
  devx bridge rbac | kubectl apply -f -  # apply directly`,
	RunE: runBridgeRBAC,
}

func init() {
	bridgeRBACCmd.Flags().StringVarP(&rbacNamespace, "namespace", "n", "",
		"Namespace to scope the RoleBinding (default: cluster-wide)")
}

func runBridgeRBAC(_ *cobra.Command, _ []string) error {
	if !outputJSON {
		fmt.Printf("\n%s\n\n", tui.StyleTitle.Render("🔐 devx bridge rbac"))
		fmt.Printf("  %s\n\n",
			tui.StyleMuted.Render("Apply with: devx bridge rbac | kubectl apply -f -"))
	}

	manifest := generateRBACManifest(rbacNamespace)
	fmt.Println(manifest)
	return nil
}

func generateRBACManifest(namespace string) string {
	roleName := "devx-bridge-intercept"
	bindingKind := "ClusterRoleBinding"
	roleRefKind := "ClusterRole"
	namespaceLine := ""

	if namespace != "" {
		bindingKind = "RoleBinding"
		roleRefKind = "Role"
		namespaceLine = fmt.Sprintf("  namespace: %s\n", namespace)
	}

	roleKind := "ClusterRole"
	if namespace != "" {
		roleKind = "Role"
	}

	manifest := fmt.Sprintf(`---
# Minimum RBAC permissions for devx bridge intercept
# Generated by: devx bridge rbac
apiVersion: rbac.authorization.k8s.io/v1
kind: %s
metadata:
  name: %s
%srules:
# Agent Job lifecycle
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "delete", "get", "list"]

# Agent RBAC resources
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["create", "delete"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["create", "delete"]

# Service discovery and patching
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "update", "patch"]

# Pod discovery and port-forward
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/portforward"]
  verbs: ["create"]

# Endpoint inspection
- apiGroups: [""]
  resources: ["endpoints", "endpointslices"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: %s
metadata:
  name: %s
%sroleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: %s
  name: %s
subjects:
# Replace with your user/group/serviceaccount
- kind: User
  name: <YOUR-USER>
  apiGroup: rbac.authorization.k8s.io
`,
		roleKind, roleName, namespaceLine,
		bindingKind, roleName, namespaceLine,
		roleRefKind, roleName,
	)

	return manifest
}
