package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

var mapOutputFile string

var mapCmd = &cobra.Command{
	Use:   "map",
	Short: "Generate a visual architecture map from devx.yaml as a Mermaid diagram",
	Long: `Parses the devx.yaml service dependency graph and generates a Mermaid.js
flowchart showing databases, services, tunnels, and their interconnections.

Output is printed to stdout by default, or written to a markdown file via --output.

Example:
  devx map                          # Print Mermaid diagram to stdout
  devx map --output topology.md     # Write to file`,
	RunE: func(cmd *cobra.Command, args []string) error {
		yamlPath := "devx.yaml"
		if _, err := os.Stat(yamlPath); os.IsNotExist(err) {
			return fmt.Errorf("could not find devx.yaml in the current directory")
		}

		// Idea 44: resolveConfig processes includes before generating the map
		cfg, err := resolveConfig(yamlPath, "")
		if err != nil {
			return fmt.Errorf("reading devx.yaml: %w", err)
		}

		diagram := GenerateMermaid(*cfg)

		if mapOutputFile != "" {
			content := fmt.Sprintf("# %s — Architecture Topology\n\nAuto-generated by `devx map` from `devx.yaml`.\n\n```mermaid\n%s\n```\n", cfg.Name, diagram)
			if err := os.WriteFile(mapOutputFile, []byte(content), 0644); err != nil {
				return fmt.Errorf("writing output: %w", err)
			}
			absPath, _ := filepath.Abs(mapOutputFile)
			fmt.Printf("📐 Topology written to %s\n", absPath)
			return nil
		}

		fmt.Println(diagram)
		return nil
	},
}

// GenerateMermaid produces a Mermaid flowchart string from a DevxConfig.
func GenerateMermaid(cfg DevxConfig) string {
	var sb strings.Builder
	sb.WriteString("flowchart TD\n")

	// Style classes
	sb.WriteString("    classDef db fill:#4A90D9,stroke:#2C5F8A,color:#fff,stroke-width:2px\n")
	sb.WriteString("    classDef svc fill:#50C878,stroke:#2E8B57,color:#fff,stroke-width:2px\n")
	sb.WriteString("    classDef tunnel fill:#FF6B6B,stroke:#CC4444,color:#fff,stroke-width:2px\n")
	sb.WriteString("\n")

	// Databases — cylinder shape
	for _, db := range cfg.Databases {
		id := sanitizeID(db.Engine)
		label := db.Engine
		if db.Port > 0 {
			label += fmt.Sprintf(":%d", db.Port)
		}
		sb.WriteString(fmt.Sprintf("    %s[(\"%s\")]:::db\n", id, label))
	}

	// Services — rounded rectangle shape
	for _, svc := range cfg.Services {
		id := sanitizeID(svc.Name)
		label := svc.Name
		if svc.Port > 0 {
			label += fmt.Sprintf(":%d", svc.Port)
		}
		if svc.Runtime != "" && svc.Runtime != "host" {
			label += fmt.Sprintf(" [%s]", svc.Runtime)
		}
		sb.WriteString(fmt.Sprintf("    %s(\"%s\"):::svc\n", id, label))
	}

	// Tunnels — hexagonal shape
	for _, t := range cfg.Tunnels {
		id := sanitizeID("tunnel_" + t.Name)
		label := fmt.Sprintf("🌐 %s", t.Name)
		if t.Port > 0 {
			label += fmt.Sprintf(":%d", t.Port)
		}
		sb.WriteString(fmt.Sprintf("    %s{{\"%s\"}}:::tunnel\n", id, label))
	}

	sb.WriteString("\n")

	// Service dependency edges
	for _, svc := range cfg.Services {
		svcID := sanitizeID(svc.Name)
		for _, dep := range svc.DependsOn {
			depID := sanitizeID(dep.Name)
			edgeLabel := ""
			if dep.Condition != "" {
				edgeLabel = dep.Condition
			}
			if edgeLabel != "" {
				sb.WriteString(fmt.Sprintf("    %s -->|\"%s\"| %s\n", depID, edgeLabel, svcID))
			} else {
				sb.WriteString(fmt.Sprintf("    %s --> %s\n", depID, svcID))
			}
		}
	}

	// Tunnel-to-service edges (match by port)
	portToService := make(map[int]string)
	for _, svc := range cfg.Services {
		if svc.Port > 0 {
			portToService[svc.Port] = sanitizeID(svc.Name)
		}
	}
	for _, t := range cfg.Tunnels {
		tunnelID := sanitizeID("tunnel_" + t.Name)
		if svcID, ok := portToService[t.Port]; ok {
			sb.WriteString(fmt.Sprintf("    %s -.->|\"expose\"| %s\n", svcID, tunnelID))
		}
	}

	return sb.String()
}

// sanitizeID converts a service/database name into a valid Mermaid node ID.
func sanitizeID(name string) string {
	return strings.NewReplacer(
		"-", "_",
		".", "_",
		" ", "_",
		"/", "_",
	).Replace(name)
}

func init() {
	mapCmd.Flags().StringVarP(&mapOutputFile, "output", "o", "", "Write diagram to a markdown file instead of stdout")
	rootCmd.AddCommand(mapCmd)
}
