// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 VitruvianSoftware

import Foundation

package struct NexusAgentFeatureStrings {
    package let title: String
    package let hubDescription: String
    package let panelCaption: String
    package let quickPromptTitle: String
    package let botSection: String
    package let statusRunning: String
    package let statusStopped: String
    package let start: String
    package let stop: String
    package let restart: String
    package let openLog: String
    package let recentLog: String
    package let logEmpty: String
    package let configurationSection: String
    package let token: String
    package let tokenCaption: String
    package let allowedUsers: String
    package let allowedUsersCaption: String
    package let workingFolder: String
    package let workingFolderCaption: String
    package let choose: String
    package let approvalMode: String
    package let approvalYolo: String
    package let approvalAcceptEdits: String
    package let approvalPlan: String
    package let approvalDefault: String
    package let model: String
    package let modelPlaceholder: String
    package let effort: String
    package let effortAutomatic: String
    package let effortLow: String
    package let effortMedium: String
    package let effortHigh: String
    package let save: String
    package let savedRestartHint: String
    package let saveFailed: String
    package let botFolder: String
    package let botFolderCaption: String
    package let autoStart: String
    package let missingToken: String
    package let missingBot: String
    package let missingNode: String
    package let startFailed: String
    package let missingAgent: String
    package let quickPromptSection: String
    package let quickPromptCaption: String
    package let promptPlaceholder: String
    package let send: String
    package let stopReply: String
    package let newChat: String
    package let thinking: String
    package let working: String
    package let replyStopped: String
    package let emptyReply: String
    package let agentFailed: String
    package let sessionsToggle: String
    package let planModeOn: String
    package let planModeOff: String
    package let sessionsFilter: String
    package let noSessions: String
    package let followUpPlaceholder: String
    package let untitledSession: String

    package var pinWindow: String { "Pin window" }
    package var unpinWindow: String { "Unpin window" }
    package var scrollToBottom: String { "Scroll to bottom" }
    package var newMessages: String { "New messages" }
    package var copy: String { "Copy" }
    package var copied: String { "Copied!" }
    package var retry: String { "Retry" }
    package var switchProvider: String { "Switch provider" }
    package var autoModel: String { "Auto" }
    package var worktreeModeOn: String { "Worktree mode on (isolated branch)" }
    package var worktreeModeOff: String { "Enable git worktree" }
    package var confirmDeleteAll: String { "Confirm?" }
    package var clearAll: String { "Clear All" }
    package var worktreeContext: String { "Isolated git branch — ask the agent to merge when finished" }
    package var planContext: String { "Read-only — agent will explain without making changes" }

    package func approvalModeName(_ mode: NexusAgentApprovalMode) -> String {
        switch mode {
        case .yolo: return approvalYolo
        case .acceptEdits: return approvalAcceptEdits
        case .plan: return approvalPlan
        case .standard: return approvalDefault
        }
    }

    package func effortName(_ effort: NexusAgentEffort) -> String {
        switch effort {
        case .automatic: return effortAutomatic
        case .low: return effortLow
        case .medium: return effortMedium
        case .high: return effortHigh
        }
    }
}

extension FeatureStrings {
    package static func nexusAgent(_ language: AppLanguage) -> NexusAgentFeatureStrings {
        switch language {
        case .enUS: return .enUS
        case .ptBR: return .ptBR
        case .tr: return .tr
        case .ru: return .ru
        case .es: return .es
        case .sk: return .sk
        case .de: return .de
        case .fr: return .fr
        case .it: return .it
        case .ja: return .ja
        case .ko: return .ko
        case .uk: return .uk
        case .zhHans: return .zhHans
        case .zhTW: return .zhTW
        case .zhHK: return .zhHK
        }
    }
}

extension NexusAgentFeatureStrings {
    package static let enUS = NexusAgentFeatureStrings(
        title: "Nexus Agent",
        hubDescription: "Run your Telegram bot for the Antigravity agent and ask the agent from anywhere with a Quick Prompt",
        panelCaption: "Telegram bot and Quick Prompt",
        quickPromptTitle: "Agent Quick Prompt",
        botSection: "Telegram bot",
        statusRunning: "Running",
        statusStopped: "Stopped",
        start: "Start",
        stop: "Stop",
        restart: "Restart",
        openLog: "Open Log",
        recentLog: "Recent log",
        logEmpty: "Nothing logged yet.",
        configurationSection: "Bot settings",
        token: "Bot token",
        tokenCaption: "From @BotFather. Kept only in the bot’s .env file, never in Vitruvian’s settings or backups.",
        allowedUsers: "Allowed user IDs",
        allowedUsersCaption: "Comma-separated Telegram user IDs. Left empty, anyone who finds the bot can use it.",
        workingFolder: "Working folder",
        workingFolderCaption: "The folder the agent works in.",
        choose: "Choose…",
        approvalMode: "Approval mode",
        approvalYolo: "Run everything without asking",
        approvalAcceptEdits: "Accept file edits",
        approvalPlan: "Plan only",
        approvalDefault: "Agent default",
        model: "Model",
        modelPlaceholder: "Agent default",
        effort: "Reasoning effort",
        effortAutomatic: "Automatic",
        effortLow: "Low",
        effortMedium: "Medium",
        effortHigh: "High",
        save: "Save",
        savedRestartHint: "Saved. Restart the bot to use the new settings.",
        saveFailed: "Could not write the bot’s .env file.",
        botFolder: "Bot folder",
        botFolderCaption: "Where nexus-agent is installed. Empty uses ~/.config/nexus-agent.",
        autoStart: "Start the bot when Vitruvian opens",
        missingToken: "Add a bot token to start the bot.",
        missingBot: "No bot was found in this folder.",
        missingNode: "Node.js was not found. Install it with Homebrew.",
        startFailed: "The bot could not start. Its log may say why.",
        missingAgent: "The Antigravity CLI (agy) was not found.",
        quickPromptSection: "Quick Prompt",
        quickPromptCaption: "Ask the agent from anywhere. Replies stream into a floating panel.",
        promptPlaceholder: "Ask Antigravity anything...",
        send: "Send",
        stopReply: "Stop",
        newChat: "New chat",
        thinking: "Thinking…",
        working: "Working…",
        replyStopped: "Reply stopped.",
        emptyReply: "The agent returned no reply.",
        agentFailed: "The agent stopped with an error.",
        sessionsToggle: "Recent sessions",
        planModeOn: "Plan mode on (read-only)",
        planModeOff: "Turn on plan mode",
        sessionsFilter: "Filter sessions",
        noSessions: "No recent sessions",
        followUpPlaceholder: "Ask a follow-up…",
        untitledSession: "Untitled"
    )

    package static let ptBR = NexusAgentFeatureStrings(
        title: "Nexus Agent",
        hubDescription: "Execute seu bot do Telegram para o agente Antigravity e pergunte ao agente de qualquer lugar com um Prompt rápido",
        panelCaption: "Bot do Telegram e Prompt rápido",
        quickPromptTitle: "Prompt rápido do agente",
        botSection: "Bot do Telegram",
        statusRunning: "Em execução",
        statusStopped: "Parado",
        start: "Iniciar",
        stop: "Parar",
        restart: "Reiniciar",
        openLog: "Abrir registro",
        recentLog: "Registro recente",
        logEmpty: "Nada registrado ainda.",
        configurationSection: "Ajustes do bot",
        token: "Token do bot",
        tokenCaption: "Do @BotFather. Guardado só no arquivo .env do bot, nunca nos ajustes nem nos backups do Vitruvian.",
        allowedUsers: "IDs de usuário permitidos",
        allowedUsersCaption: "IDs de usuário do Telegram separados por vírgula. Vazio, qualquer pessoa que encontrar o bot pode usá-lo.",
        workingFolder: "Pasta de trabalho",
        workingFolderCaption: "A pasta em que o agente trabalha.",
        choose: "Escolher…",
        approvalMode: "Modo de aprovação",
        approvalYolo: "Executar tudo sem perguntar",
        approvalAcceptEdits: "Aceitar edições de arquivos",
        approvalPlan: "Só planejar",
        approvalDefault: "Padrão do agente",
        model: "Modelo",
        modelPlaceholder: "Padrão do agente",
        effort: "Esforço de raciocínio",
        effortAutomatic: "Automático",
        effortLow: "Baixo",
        effortMedium: "Médio",
        effortHigh: "Alto",
        save: "Salvar",
        savedRestartHint: "Salvo. Reinicie o bot para usar os novos ajustes.",
        saveFailed: "Não foi possível gravar o arquivo .env do bot.",
        botFolder: "Pasta do bot",
        botFolderCaption: "Onde o nexus-agent está instalado. Vazio usa ~/.config/nexus-agent.",
        autoStart: "Iniciar o bot quando o Vitruvian abrir",
        missingToken: "Adicione um token para iniciar o bot.",
        missingBot: "Nenhum bot foi encontrado nesta pasta.",
        missingNode: "O Node.js não foi encontrado. Instale-o com o Homebrew.",
        startFailed: "O bot não pôde iniciar. O registro pode dizer por quê.",
        missingAgent: "A CLI do Antigravity (agy) não foi encontrada.",
        quickPromptSection: "Prompt rápido",
        quickPromptCaption: "Pergunte ao agente de qualquer lugar. As respostas aparecem num painel flutuante.",
        promptPlaceholder: "Pergunte qualquer coisa ao Antigravity...",
        send: "Enviar",
        stopReply: "Parar",
        newChat: "Nova conversa",
        thinking: "Pensando…",
        working: "Trabalhando…",
        replyStopped: "Resposta interrompida.",
        emptyReply: "O agente não respondeu nada.",
        agentFailed: "O agente parou com um erro.",
        sessionsToggle: "Sessões recentes",
        planModeOn: "Modo de plano ativado (somente leitura)",
        planModeOff: "Ativar modo de plano",
        sessionsFilter: "Filtrar sessões",
        noSessions: "Nenhuma sessão recente",
        followUpPlaceholder: "Faça uma pergunta de acompanhamento…",
        untitledSession: "Sem título"
    )

    package static let tr = NexusAgentFeatureStrings(
        title: "Nexus Agent",
        hubDescription: "Antigravity ajanı için Telegram botunuzu çalıştırın ve Hızlı İstem ile ajana her yerden sorun",
        panelCaption: "Telegram botu ve Hızlı İstem",
        quickPromptTitle: "Ajan Hızlı İstemi",
        botSection: "Telegram botu",
        statusRunning: "Çalışıyor",
        statusStopped: "Durduruldu",
        start: "Başlat",
        stop: "Durdur",
        restart: "Yeniden başlat",
        openLog: "Günlüğü aç",
        recentLog: "Son günlük",
        logEmpty: "Henüz günlüğe bir şey yazılmadı.",
        configurationSection: "Bot ayarları",
        token: "Bot belirteci",
        tokenCaption: "@BotFather’dan alınır. Yalnızca botun .env dosyasında tutulur, Vitruvian ayarlarında veya yedeklerinde asla tutulmaz.",
        allowedUsers: "İzin verilen kullanıcı kimlikleri",
        allowedUsersCaption: "Virgülle ayrılmış Telegram kullanıcı kimlikleri. Boş bırakılırsa botu bulan herkes kullanabilir.",
        workingFolder: "Çalışma klasörü",
        workingFolderCaption: "Ajanın çalıştığı klasör.",
        choose: "Seç…",
        approvalMode: "Onay modu",
        approvalYolo: "Sormadan her şeyi çalıştır",
        approvalAcceptEdits: "Dosya düzenlemelerini kabul et",
        approvalPlan: "Yalnızca planla",
        approvalDefault: "Ajan varsayılanı",
        model: "Model",
        modelPlaceholder: "Ajan varsayılanı",
        effort: "Akıl yürütme çabası",
        effortAutomatic: "Otomatik",
        effortLow: "Düşük",
        effortMedium: "Orta",
        effortHigh: "Yüksek",
        save: "Kaydet",
        savedRestartHint: "Kaydedildi. Yeni ayarları kullanmak için botu yeniden başlatın.",
        saveFailed: "Botun .env dosyası yazılamadı.",
        botFolder: "Bot klasörü",
        botFolderCaption: "nexus-agent’ın kurulu olduğu yer. Boş bırakılırsa ~/.config/nexus-agent kullanılır.",
        autoStart: "Vitruvian açıldığında botu başlat",
        missingToken: "Botu başlatmak için bir bot belirteci ekleyin.",
        missingBot: "Bu klasörde bot bulunamadı.",
        missingNode: "Node.js bulunamadı. Homebrew ile kurun.",
        startFailed: "Bot başlatılamadı. Nedeni günlükte yazıyor olabilir.",
        missingAgent: "Antigravity CLI (agy) bulunamadı.",
        quickPromptSection: "Hızlı İstem",
        quickPromptCaption: "Ajana her yerden sorun. Yanıtlar yüzen bir panelde akar.",
        promptPlaceholder: "Antigravity’ye her şeyi sorun...",
        send: "Gönder",
        stopReply: "Durdur",
        newChat: "Yeni sohbet",
        thinking: "Düşünüyor…",
        working: "Çalışıyor…",
        replyStopped: "Yanıt durduruldu.",
        emptyReply: "Ajan yanıt vermedi.",
        agentFailed: "Ajan bir hatayla durdu.",
        sessionsToggle: "Son oturumlar",
        planModeOn: "Plan modu açık (salt okunur)",
        planModeOff: "Plan modunu aç",
        sessionsFilter: "Oturumları filtrele",
        noSessions: "Son oturum yok",
        followUpPlaceholder: "Devam sorusu sorun…",
        untitledSession: "Adsız"
    )

    package static let ru = NexusAgentFeatureStrings(
        title: "Nexus Agent",
        hubDescription: "Запускайте Telegram-бота для агента Antigravity и обращайтесь к агенту откуда угодно через быстрый запрос",
        panelCaption: "Telegram-бот и быстрый запрос",
        quickPromptTitle: "Быстрый запрос к агенту",
        botSection: "Telegram-бот",
        statusRunning: "Работает",
        statusStopped: "Остановлен",
        start: "Запустить",
        stop: "Остановить",
        restart: "Перезапустить",
        openLog: "Открыть журнал",
        recentLog: "Последние записи журнала",
        logEmpty: "В журнале пока пусто.",
        configurationSection: "Настройки бота",
        token: "Токен бота",
        tokenCaption: "Выдаётся @BotFather. Хранится только в файле .env бота и никогда не попадает в настройки или резервные копии Vitruvian.",
        allowedUsers: "Разрешённые ID пользователей",
        allowedUsersCaption: "ID пользователей Telegram через запятую. Если оставить пустым, ботом сможет пользоваться любой, кто его найдёт.",
        workingFolder: "Рабочая папка",
        workingFolderCaption: "Папка, в которой работает агент.",
        choose: "Выбрать…",
        approvalMode: "Режим подтверждения",
        approvalYolo: "Выполнять всё без вопросов",
        approvalAcceptEdits: "Принимать правки файлов",
        approvalPlan: "Только план",
        approvalDefault: "По умолчанию агента",
        model: "Модель",
        modelPlaceholder: "По умолчанию агента",
        effort: "Глубина рассуждений",
        effortAutomatic: "Автоматически",
        effortLow: "Низкая",
        effortMedium: "Средняя",
        effortHigh: "Высокая",
        save: "Сохранить",
        savedRestartHint: "Сохранено. Перезапустите бота, чтобы применить новые настройки.",
        saveFailed: "Не удалось записать файл .env бота.",
        botFolder: "Папка бота",
        botFolderCaption: "Где установлен nexus-agent. Если пусто, используется ~/.config/nexus-agent.",
        autoStart: "Запускать бота при открытии Vitruvian",
        missingToken: "Добавьте токен бота, чтобы запустить его.",
        missingBot: "В этой папке бот не найден.",
        missingNode: "Node.js не найден. Установите его через Homebrew.",
        startFailed: "Не удалось запустить бота. Причина может быть в журнале.",
        missingAgent: "Antigravity CLI (agy) не найден.",
        quickPromptSection: "Быстрый запрос",
        quickPromptCaption: "Обращайтесь к агенту откуда угодно. Ответы появляются в плавающей панели.",
        promptPlaceholder: "Спросите Antigravity о чём угодно...",
        send: "Отправить",
        stopReply: "Остановить",
        newChat: "Новый чат",
        thinking: "Думает…",
        working: "Работает…",
        replyStopped: "Ответ остановлен.",
        emptyReply: "Агент ничего не ответил.",
        agentFailed: "Агент остановился с ошибкой.",
        sessionsToggle: "Недавние сеансы",
        planModeOn: "Режим плана включён (только чтение)",
        planModeOff: "Включить режим плана",
        sessionsFilter: "Фильтр сеансов",
        noSessions: "Нет недавних сеансов",
        followUpPlaceholder: "Задайте уточняющий вопрос…",
        untitledSession: "Без названия"
    )

    package static let es = NexusAgentFeatureStrings(
        title: "Nexus Agent",
        hubDescription: "Ejecuta tu bot de Telegram para el agente Antigravity y pregunta al agente desde cualquier lugar con un Prompt rápido",
        panelCaption: "Bot de Telegram y Prompt rápido",
        quickPromptTitle: "Prompt rápido del agente",
        botSection: "Bot de Telegram",
        statusRunning: "En ejecución",
        statusStopped: "Detenido",
        start: "Iniciar",
        stop: "Detener",
        restart: "Reiniciar",
        openLog: "Abrir registro",
        recentLog: "Registro reciente",
        logEmpty: "Aún no hay nada registrado.",
        configurationSection: "Ajustes del bot",
        token: "Token del bot",
        tokenCaption: "De @BotFather. Se guarda solo en el archivo .env del bot, nunca en los ajustes ni en las copias de seguridad de Vitruvian.",
        allowedUsers: "ID de usuario permitidos",
        allowedUsersCaption: "ID de usuario de Telegram separados por comas. Si lo dejas vacío, cualquiera que encuentre el bot podrá usarlo.",
        workingFolder: "Carpeta de trabajo",
        workingFolderCaption: "La carpeta en la que trabaja el agente.",
        choose: "Elegir…",
        approvalMode: "Modo de aprobación",
        approvalYolo: "Ejecutar todo sin preguntar",
        approvalAcceptEdits: "Aceptar ediciones de archivos",
        approvalPlan: "Solo planificar",
        approvalDefault: "Predeterminado del agente",
        model: "Modelo",
        modelPlaceholder: "Predeterminado del agente",
        effort: "Esfuerzo de razonamiento",
        effortAutomatic: "Automático",
        effortLow: "Bajo",
        effortMedium: "Medio",
        effortHigh: "Alto",
        save: "Guardar",
        savedRestartHint: "Guardado. Reinicia el bot para usar los nuevos ajustes.",
        saveFailed: "No se pudo escribir el archivo .env del bot.",
        botFolder: "Carpeta del bot",
        botFolderCaption: "Donde está instalado nexus-agent. Vacío usa ~/.config/nexus-agent.",
        autoStart: "Iniciar el bot al abrir Vitruvian",
        missingToken: "Añade un token para iniciar el bot.",
        missingBot: "No se encontró ningún bot en esta carpeta.",
        missingNode: "No se encontró Node.js. Instálalo con Homebrew.",
        startFailed: "El bot no pudo iniciarse. El registro puede indicar por qué.",
        missingAgent: "No se encontró la CLI de Antigravity (agy).",
        quickPromptSection: "Prompt rápido",
        quickPromptCaption: "Pregunta al agente desde cualquier lugar. Las respuestas llegan a un panel flotante.",
        promptPlaceholder: "Pregunta lo que quieras a Antigravity...",
        send: "Enviar",
        stopReply: "Detener",
        newChat: "Nueva conversación",
        thinking: "Pensando…",
        working: "Trabajando…",
        replyStopped: "Respuesta detenida.",
        emptyReply: "El agente no devolvió ninguna respuesta.",
        agentFailed: "El agente se detuvo con un error.",
        sessionsToggle: "Sesiones recientes",
        planModeOn: "Modo plan activado (solo lectura)",
        planModeOff: "Activar modo plan",
        sessionsFilter: "Filtrar sesiones",
        noSessions: "No hay sesiones recientes",
        followUpPlaceholder: "Haz una pregunta de seguimiento…",
        untitledSession: "Sin título"
    )

    package static let sk = NexusAgentFeatureStrings(
        title: "Nexus Agent",
        hubDescription: "Spúšťajte svojho Telegram bota pre agenta Antigravity a pýtajte sa agenta odkiaľkoľvek cez Rýchlu výzvu",
        panelCaption: "Telegram bot a Rýchla výzva",
        quickPromptTitle: "Rýchla výzva agentovi",
        botSection: "Telegram bot",
        statusRunning: "Beží",
        statusStopped: "Zastavený",
        start: "Spustiť",
        stop: "Zastaviť",
        restart: "Reštartovať",
        openLog: "Otvoriť záznam",
        recentLog: "Posledný záznam",
        logEmpty: "Zatiaľ nič nezaznamenané.",
        configurationSection: "Nastavenia bota",
        token: "Token bota",
        tokenCaption: "Od @BotFather. Uložený iba v súbore .env bota, nikdy v nastaveniach ani zálohách Vitruvianu.",
        allowedUsers: "Povolené ID používateľov",
        allowedUsersCaption: "ID používateľov Telegramu oddelené čiarkami. Ak necháte prázdne, bota môže používať ktokoľvek, kto ho nájde.",
        workingFolder: "Pracovný priečinok",
        workingFolderCaption: "Priečinok, v ktorom agent pracuje.",
        choose: "Vybrať…",
        approvalMode: "Režim schvaľovania",
        approvalYolo: "Spúšťať všetko bez pýtania",
        approvalAcceptEdits: "Prijímať úpravy súborov",
        approvalPlan: "Iba plánovať",
        approvalDefault: "Predvolené agentom",
        model: "Model",
        modelPlaceholder: "Predvolené agentom",
        effort: "Úsilie uvažovania",
        effortAutomatic: "Automaticky",
        effortLow: "Nízke",
        effortMedium: "Stredné",
        effortHigh: "Vysoké",
        save: "Uložiť",
        savedRestartHint: "Uložené. Reštartujte bota, aby použil nové nastavenia.",
        saveFailed: "Súbor .env bota sa nepodarilo zapísať.",
        botFolder: "Priečinok bota",
        botFolderCaption: "Kde je nainštalovaný nexus-agent. Prázdne použije ~/.config/nexus-agent.",
        autoStart: "Spustiť bota pri otvorení Vitruvianu",
        missingToken: "Na spustenie bota pridajte token bota.",
        missingBot: "V tomto priečinku sa nenašiel žiadny bot.",
        missingNode: "Node.js sa nenašiel. Nainštalujte ho cez Homebrew.",
        startFailed: "Bota sa nepodarilo spustiť. Príčina môže byť v zázname.",
        missingAgent: "Antigravity CLI (agy) sa nenašlo.",
        quickPromptSection: "Rýchla výzva",
        quickPromptCaption: "Pýtajte sa agenta odkiaľkoľvek. Odpovede prichádzajú do plávajúceho panela.",
        promptPlaceholder: "Opýtajte sa Antigravity na čokoľvek...",
        send: "Odoslať",
        stopReply: "Zastaviť",
        newChat: "Nový rozhovor",
        thinking: "Premýšľa…",
        working: "Pracuje…",
        replyStopped: "Odpoveď zastavená.",
        emptyReply: "Agent nevrátil žiadnu odpoveď.",
        agentFailed: "Agent sa zastavil s chybou.",
        sessionsToggle: "Nedávne relácie",
        planModeOn: "Režim plánu zapnutý (iba na čítanie)",
        planModeOff: "Zapnúť režim plánu",
        sessionsFilter: "Filtrovať relácie",
        noSessions: "Žiadne nedávne relácie",
        followUpPlaceholder: "Položte doplňujúcu otázku…",
        untitledSession: "Bez názvu"
    )

    package static let de = NexusAgentFeatureStrings(
        title: "Nexus Agent",
        hubDescription: "Betreibe deinen Telegram-Bot für den Antigravity-Agenten und frag den Agenten von überall mit einem Schnell-Prompt",
        panelCaption: "Telegram-Bot und Schnell-Prompt",
        quickPromptTitle: "Agent-Schnell-Prompt",
        botSection: "Telegram-Bot",
        statusRunning: "Läuft",
        statusStopped: "Gestoppt",
        start: "Starten",
        stop: "Stoppen",
        restart: "Neu starten",
        openLog: "Protokoll öffnen",
        recentLog: "Letzte Protokolleinträge",
        logEmpty: "Noch nichts protokolliert.",
        configurationSection: "Bot-Einstellungen",
        token: "Bot-Token",
        tokenCaption: "Von @BotFather. Nur in der .env-Datei des Bots gespeichert, nie in den Einstellungen oder Backups von Vitruvian.",
        allowedUsers: "Erlaubte Benutzer-IDs",
        allowedUsersCaption: "Telegram-Benutzer-IDs, durch Kommas getrennt. Leer kann jeder den Bot nutzen, der ihn findet.",
        workingFolder: "Arbeitsordner",
        workingFolderCaption: "Der Ordner, in dem der Agent arbeitet.",
        choose: "Auswählen…",
        approvalMode: "Freigabemodus",
        approvalYolo: "Alles ohne Nachfrage ausführen",
        approvalAcceptEdits: "Dateiänderungen annehmen",
        approvalPlan: "Nur planen",
        approvalDefault: "Standard des Agenten",
        model: "Modell",
        modelPlaceholder: "Standard des Agenten",
        effort: "Denkaufwand",
        effortAutomatic: "Automatisch",
        effortLow: "Niedrig",
        effortMedium: "Mittel",
        effortHigh: "Hoch",
        save: "Sichern",
        savedRestartHint: "Gesichert. Starte den Bot neu, um die neuen Einstellungen zu verwenden.",
        saveFailed: "Die .env-Datei des Bots konnte nicht geschrieben werden.",
        botFolder: "Bot-Ordner",
        botFolderCaption: "Wo nexus-agent installiert ist. Leer verwendet ~/.config/nexus-agent.",
        autoStart: "Bot beim Öffnen von Vitruvian starten",
        missingToken: "Füge ein Bot-Token hinzu, um den Bot zu starten.",
        missingBot: "In diesem Ordner wurde kein Bot gefunden.",
        missingNode: "Node.js wurde nicht gefunden. Installiere es mit Homebrew.",
        startFailed: "Der Bot konnte nicht starten. Das Protokoll nennt vielleicht den Grund.",
        missingAgent: "Die Antigravity-CLI (agy) wurde nicht gefunden.",
        quickPromptSection: "Schnell-Prompt",
        quickPromptCaption: "Frag den Agenten von überall. Antworten erscheinen in einem schwebenden Fenster.",
        promptPlaceholder: "Frag Antigravity alles...",
        send: "Senden",
        stopReply: "Stoppen",
        newChat: "Neuer Chat",
        thinking: "Denkt nach…",
        working: "Arbeitet…",
        replyStopped: "Antwort gestoppt.",
        emptyReply: "Der Agent hat nichts geantwortet.",
        agentFailed: "Der Agent wurde mit einem Fehler beendet.",
        sessionsToggle: "Letzte Sitzungen",
        planModeOn: "Planmodus an (nur lesen)",
        planModeOff: "Planmodus einschalten",
        sessionsFilter: "Sitzungen filtern",
        noSessions: "Keine letzten Sitzungen",
        followUpPlaceholder: "Stell eine Folgefrage…",
        untitledSession: "Ohne Titel"
    )

    package static let fr = NexusAgentFeatureStrings(
        title: "Nexus Agent",
        hubDescription: "Faites tourner votre bot Telegram pour l’agent Antigravity et interrogez l’agent depuis n’importe où avec un Prompt rapide",
        panelCaption: "Bot Telegram et Prompt rapide",
        quickPromptTitle: "Prompt rapide de l’agent",
        botSection: "Bot Telegram",
        statusRunning: "En cours",
        statusStopped: "Arrêté",
        start: "Démarrer",
        stop: "Arrêter",
        restart: "Redémarrer",
        openLog: "Ouvrir le journal",
        recentLog: "Journal récent",
        logEmpty: "Rien n’a encore été journalisé.",
        configurationSection: "Réglages du bot",
        token: "Jeton du bot",
        tokenCaption: "Fourni par @BotFather. Conservé uniquement dans le fichier .env du bot, jamais dans les réglages ni les sauvegardes de Vitruvian.",
        allowedUsers: "Identifiants autorisés",
        allowedUsersCaption: "Identifiants d’utilisateur Telegram séparés par des virgules. Vide, toute personne qui trouve le bot peut l’utiliser.",
        workingFolder: "Dossier de travail",
        workingFolderCaption: "Le dossier dans lequel l’agent travaille.",
        choose: "Choisir…",
        approvalMode: "Mode d’approbation",
        approvalYolo: "Tout exécuter sans demander",
        approvalAcceptEdits: "Accepter les modifications de fichiers",
        approvalPlan: "Planifier seulement",
        approvalDefault: "Par défaut de l’agent",
        model: "Modèle",
        modelPlaceholder: "Par défaut de l’agent",
        effort: "Effort de raisonnement",
        effortAutomatic: "Automatique",
        effortLow: "Faible",
        effortMedium: "Moyen",
        effortHigh: "Élevé",
        save: "Enregistrer",
        savedRestartHint: "Enregistré. Redémarrez le bot pour appliquer les nouveaux réglages.",
        saveFailed: "Impossible d’écrire le fichier .env du bot.",
        botFolder: "Dossier du bot",
        botFolderCaption: "Emplacement de nexus-agent. Vide utilise ~/.config/nexus-agent.",
        autoStart: "Démarrer le bot à l’ouverture de Vitruvian",
        missingToken: "Ajoutez un jeton pour démarrer le bot.",
        missingBot: "Aucun bot trouvé dans ce dossier.",
        missingNode: "Node.js est introuvable. Installez-le avec Homebrew.",
        startFailed: "Le bot n’a pas pu démarrer. Le journal en donne peut-être la raison.",
        missingAgent: "La CLI Antigravity (agy) est introuvable.",
        quickPromptSection: "Prompt rapide",
        quickPromptCaption: "Interrogez l’agent depuis n’importe où. Les réponses s’affichent dans un panneau flottant.",
        promptPlaceholder: "Demandez n’importe quoi à Antigravity...",
        send: "Envoyer",
        stopReply: "Arrêter",
        newChat: "Nouvelle conversation",
        thinking: "Réflexion…",
        working: "Travail en cours…",
        replyStopped: "Réponse interrompue.",
        emptyReply: "L’agent n’a rien répondu.",
        agentFailed: "L’agent s’est arrêté sur une erreur.",
        sessionsToggle: "Sessions récentes",
        planModeOn: "Mode plan activé (lecture seule)",
        planModeOff: "Activer le mode plan",
        sessionsFilter: "Filtrer les sessions",
        noSessions: "Aucune session récente",
        followUpPlaceholder: "Posez une question de suivi…",
        untitledSession: "Sans titre"
    )

    package static let it = NexusAgentFeatureStrings(
        title: "Nexus Agent",
        hubDescription: "Esegui il tuo bot Telegram per l’agente Antigravity e chiedi all’agente da qualsiasi punto con un Prompt rapido",
        panelCaption: "Bot Telegram e Prompt rapido",
        quickPromptTitle: "Prompt rapido dell’agente",
        botSection: "Bot Telegram",
        statusRunning: "In esecuzione",
        statusStopped: "Fermato",
        start: "Avvia",
        stop: "Ferma",
        restart: "Riavvia",
        openLog: "Apri registro",
        recentLog: "Registro recente",
        logEmpty: "Ancora nulla nel registro.",
        configurationSection: "Impostazioni del bot",
        token: "Token del bot",
        tokenCaption: "Fornito da @BotFather. Salvato solo nel file .env del bot, mai nelle impostazioni o nei backup di Vitruvian.",
        allowedUsers: "ID utente consentiti",
        allowedUsersCaption: "ID utente Telegram separati da virgole. Se vuoto, chiunque trovi il bot può usarlo.",
        workingFolder: "Cartella di lavoro",
        workingFolderCaption: "La cartella in cui lavora l’agente.",
        choose: "Scegli…",
        approvalMode: "Modalità di approvazione",
        approvalYolo: "Esegui tutto senza chiedere",
        approvalAcceptEdits: "Accetta le modifiche ai file",
        approvalPlan: "Solo pianificazione",
        approvalDefault: "Predefinita dell’agente",
        model: "Modello",
        modelPlaceholder: "Predefinito dell’agente",
        effort: "Impegno di ragionamento",
        effortAutomatic: "Automatico",
        effortLow: "Basso",
        effortMedium: "Medio",
        effortHigh: "Alto",
        save: "Salva",
        savedRestartHint: "Salvato. Riavvia il bot per usare le nuove impostazioni.",
        saveFailed: "Impossibile scrivere il file .env del bot.",
        botFolder: "Cartella del bot",
        botFolderCaption: "Dove è installato nexus-agent. Se vuota, usa ~/.config/nexus-agent.",
        autoStart: "Avvia il bot all’apertura di Vitruvian",
        missingToken: "Aggiungi un token per avviare il bot.",
        missingBot: "Nessun bot trovato in questa cartella.",
        missingNode: "Node.js non trovato. Installalo con Homebrew.",
        startFailed: "Impossibile avviare il bot. Il registro potrebbe spiegare perché.",
        missingAgent: "La CLI di Antigravity (agy) non è stata trovata.",
        quickPromptSection: "Prompt rapido",
        quickPromptCaption: "Chiedi all’agente da qualsiasi punto. Le risposte arrivano in un pannello mobile.",
        promptPlaceholder: "Chiedi qualsiasi cosa ad Antigravity...",
        send: "Invia",
        stopReply: "Ferma",
        newChat: "Nuova chat",
        thinking: "Sto pensando…",
        working: "Al lavoro…",
        replyStopped: "Risposta interrotta.",
        emptyReply: "L’agente non ha restituito alcuna risposta.",
        agentFailed: "L’agente si è fermato con un errore.",
        sessionsToggle: "Sessioni recenti",
        planModeOn: "Modalità piano attiva (sola lettura)",
        planModeOff: "Attiva la modalità piano",
        sessionsFilter: "Filtra sessioni",
        noSessions: "Nessuna sessione recente",
        followUpPlaceholder: "Fai una domanda di approfondimento…",
        untitledSession: "Senza titolo"
    )

    package static let ja = NexusAgentFeatureStrings(
        title: "Nexus Agent",
        hubDescription: "Antigravity エージェント用の Telegram ボットを実行し、クイックプロンプトでどこからでもエージェントに質問します",
        panelCaption: "Telegram ボットとクイックプロンプト",
        quickPromptTitle: "エージェントのクイックプロンプト",
        botSection: "Telegram ボット",
        statusRunning: "実行中",
        statusStopped: "停止中",
        start: "開始",
        stop: "停止",
        restart: "再起動",
        openLog: "ログを開く",
        recentLog: "最近のログ",
        logEmpty: "まだログはありません。",
        configurationSection: "ボットの設定",
        token: "ボットトークン",
        tokenCaption: "@BotFather から取得します。ボットの .env ファイルにのみ保存され、Vitruvian の設定やバックアップには含まれません。",
        allowedUsers: "許可するユーザー ID",
        allowedUsersCaption: "Telegram のユーザー ID をカンマ区切りで入力します。空にすると、ボットを見つけた誰もが使えます。",
        workingFolder: "作業フォルダ",
        workingFolderCaption: "エージェントが作業するフォルダです。",
        choose: "選択…",
        approvalMode: "承認モード",
        approvalYolo: "確認せずにすべて実行",
        approvalAcceptEdits: "ファイルの編集を承認",
        approvalPlan: "計画のみ",
        approvalDefault: "エージェントのデフォルト",
        model: "モデル",
        modelPlaceholder: "エージェントのデフォルト",
        effort: "推論の深さ",
        effortAutomatic: "自動",
        effortLow: "低",
        effortMedium: "中",
        effortHigh: "高",
        save: "保存",
        savedRestartHint: "保存しました。新しい設定を使うにはボットを再起動してください。",
        saveFailed: "ボットの .env ファイルに書き込めませんでした。",
        botFolder: "ボットのフォルダ",
        botFolderCaption: "nexus-agent のインストール先です。空の場合は ~/.config/nexus-agent を使います。",
        autoStart: "Vitruvian の起動時にボットを開始",
        missingToken: "ボットを開始するにはトークンを追加してください。",
        missingBot: "このフォルダにボットが見つかりません。",
        missingNode: "Node.js が見つかりません。Homebrew でインストールしてください。",
        startFailed: "ボットを開始できませんでした。理由はログに記録されている可能性があります。",
        missingAgent: "Antigravity CLI (agy) が見つかりません。",
        quickPromptSection: "クイックプロンプト",
        quickPromptCaption: "どこからでもエージェントに質問できます。返答はフローティングパネルに表示されます。",
        promptPlaceholder: "Antigravity に何でも質問...",
        send: "送信",
        stopReply: "停止",
        newChat: "新しいチャット",
        thinking: "考え中…",
        working: "作業中…",
        replyStopped: "返答を停止しました。",
        emptyReply: "エージェントから返答がありませんでした。",
        agentFailed: "エージェントはエラーで停止しました。",
        sessionsToggle: "最近のセッション",
        planModeOn: "プランモード オン(読み取り専用)",
        planModeOff: "プランモードをオンにする",
        sessionsFilter: "セッションを絞り込む",
        noSessions: "最近のセッションはありません",
        followUpPlaceholder: "追加で質問…",
        untitledSession: "無題"
    )

    package static let ko = NexusAgentFeatureStrings(
        title: "Nexus Agent",
        hubDescription: "Antigravity 에이전트용 Telegram 봇을 실행하고 빠른 프롬프트로 어디서나 에이전트에게 질문합니다",
        panelCaption: "Telegram 봇과 빠른 프롬프트",
        quickPromptTitle: "에이전트 빠른 프롬프트",
        botSection: "Telegram 봇",
        statusRunning: "실행 중",
        statusStopped: "중지됨",
        start: "시작",
        stop: "중지",
        restart: "다시 시작",
        openLog: "로그 열기",
        recentLog: "최근 로그",
        logEmpty: "아직 기록된 내용이 없습니다.",
        configurationSection: "봇 설정",
        token: "봇 토큰",
        tokenCaption: "@BotFather에서 받습니다. 봇의 .env 파일에만 저장되며 Vitruvian 설정이나 백업에는 저장되지 않습니다.",
        allowedUsers: "허용된 사용자 ID",
        allowedUsersCaption: "쉼표로 구분한 Telegram 사용자 ID입니다. 비워 두면 봇을 찾은 누구나 사용할 수 있습니다.",
        workingFolder: "작업 폴더",
        workingFolderCaption: "에이전트가 작업하는 폴더입니다.",
        choose: "선택…",
        approvalMode: "승인 모드",
        approvalYolo: "묻지 않고 모두 실행",
        approvalAcceptEdits: "파일 편집 허용",
        approvalPlan: "계획만",
        approvalDefault: "에이전트 기본값",
        model: "모델",
        modelPlaceholder: "에이전트 기본값",
        effort: "추론 강도",
        effortAutomatic: "자동",
        effortLow: "낮음",
        effortMedium: "보통",
        effortHigh: "높음",
        save: "저장",
        savedRestartHint: "저장했습니다. 새 설정을 사용하려면 봇을 다시 시작하세요.",
        saveFailed: "봇의 .env 파일을 쓸 수 없습니다.",
        botFolder: "봇 폴더",
        botFolderCaption: "nexus-agent가 설치된 위치입니다. 비워 두면 ~/.config/nexus-agent를 사용합니다.",
        autoStart: "Vitruvian을 열 때 봇 시작",
        missingToken: "봇을 시작하려면 봇 토큰을 추가하세요.",
        missingBot: "이 폴더에서 봇을 찾을 수 없습니다.",
        missingNode: "Node.js를 찾을 수 없습니다. Homebrew로 설치하세요.",
        startFailed: "봇을 시작할 수 없습니다. 로그에 이유가 있을 수 있습니다.",
        missingAgent: "Antigravity CLI(agy)를 찾을 수 없습니다.",
        quickPromptSection: "빠른 프롬프트",
        quickPromptCaption: "어디서나 에이전트에게 질문하세요. 답변은 떠 있는 패널에 표시됩니다.",
        promptPlaceholder: "Antigravity에게 무엇이든 물어보세요...",
        send: "보내기",
        stopReply: "중지",
        newChat: "새 채팅",
        thinking: "생각 중…",
        working: "작업 중…",
        replyStopped: "답변을 중지했습니다.",
        emptyReply: "에이전트가 답변하지 않았습니다.",
        agentFailed: "에이전트가 오류로 중지되었습니다.",
        sessionsToggle: "최근 세션",
        planModeOn: "계획 모드 켜짐(읽기 전용)",
        planModeOff: "계획 모드 켜기",
        sessionsFilter: "세션 필터",
        noSessions: "최근 세션 없음",
        followUpPlaceholder: "후속 질문하기…",
        untitledSession: "제목 없음"
    )

    package static let uk = NexusAgentFeatureStrings(
        title: "Nexus Agent",
        hubDescription: "Запускайте Telegram-бота для агента Antigravity і звертайтеся до агента звідусіль через швидкий запит",
        panelCaption: "Telegram-бот і швидкий запит",
        quickPromptTitle: "Швидкий запит до агента",
        botSection: "Telegram-бот",
        statusRunning: "Працює",
        statusStopped: "Зупинено",
        start: "Запустити",
        stop: "Зупинити",
        restart: "Перезапустити",
        openLog: "Відкрити журнал",
        recentLog: "Останні записи журналу",
        logEmpty: "У журналі поки порожньо.",
        configurationSection: "Налаштування бота",
        token: "Токен бота",
        tokenCaption: "Видає @BotFather. Зберігається лише у файлі .env бота й ніколи не потрапляє до налаштувань чи резервних копій Vitruvian.",
        allowedUsers: "Дозволені ID користувачів",
        allowedUsersCaption: "ID користувачів Telegram через кому. Якщо залишити порожнім, ботом зможе користуватися будь-хто, хто його знайде.",
        workingFolder: "Робоча папка",
        workingFolderCaption: "Папка, у якій працює агент.",
        choose: "Вибрати…",
        approvalMode: "Режим підтвердження",
        approvalYolo: "Виконувати все без запитань",
        approvalAcceptEdits: "Приймати зміни файлів",
        approvalPlan: "Лише план",
        approvalDefault: "Типово для агента",
        model: "Модель",
        modelPlaceholder: "Типово для агента",
        effort: "Глибина міркувань",
        effortAutomatic: "Автоматично",
        effortLow: "Низька",
        effortMedium: "Середня",
        effortHigh: "Висока",
        save: "Зберегти",
        savedRestartHint: "Збережено. Перезапустіть бота, щоб застосувати нові налаштування.",
        saveFailed: "Не вдалося записати файл .env бота.",
        botFolder: "Папка бота",
        botFolderCaption: "Де встановлено nexus-agent. Якщо порожньо, використовується ~/.config/nexus-agent.",
        autoStart: "Запускати бота під час відкриття Vitruvian",
        missingToken: "Додайте токен бота, щоб запустити його.",
        missingBot: "У цій папці бота не знайдено.",
        missingNode: "Node.js не знайдено. Установіть його через Homebrew.",
        startFailed: "Не вдалося запустити бота. Причина може бути в журналі.",
        missingAgent: "Antigravity CLI (agy) не знайдено.",
        quickPromptSection: "Швидкий запит",
        quickPromptCaption: "Звертайтеся до агента звідусіль. Відповіді з’являються на плаваючій панелі.",
        promptPlaceholder: "Запитайте Antigravity про що завгодно...",
        send: "Надіслати",
        stopReply: "Зупинити",
        newChat: "Новий чат",
        thinking: "Думає…",
        working: "Працює…",
        replyStopped: "Відповідь зупинено.",
        emptyReply: "Агент нічого не відповів.",
        agentFailed: "Агент зупинився з помилкою.",
        sessionsToggle: "Нещодавні сеанси",
        planModeOn: "Режим плану ввімкнено (лише читання)",
        planModeOff: "Увімкнути режим плану",
        sessionsFilter: "Фільтр сеансів",
        noSessions: "Немає нещодавніх сеансів",
        followUpPlaceholder: "Поставте уточнювальне запитання…",
        untitledSession: "Без назви"
    )

    package static let zhHans = NexusAgentFeatureStrings(
        title: "Nexus Agent",
        hubDescription: "为 Antigravity 智能体运行你的 Telegram 机器人，并通过快速提问随时随地向智能体提问",
        panelCaption: "Telegram 机器人和快速提问",
        quickPromptTitle: "智能体快速提问",
        botSection: "Telegram 机器人",
        statusRunning: "正在运行",
        statusStopped: "已停止",
        start: "启动",
        stop: "停止",
        restart: "重新启动",
        openLog: "打开日志",
        recentLog: "最近日志",
        logEmpty: "尚无日志。",
        configurationSection: "机器人设置",
        token: "机器人令牌",
        tokenCaption: "从 @BotFather 获取。仅保存在机器人的 .env 文件中，绝不会写入 Vitruvian 的设置或备份。",
        allowedUsers: "允许的用户 ID",
        allowedUsersCaption: "以逗号分隔的 Telegram 用户 ID。留空时，任何找到该机器人的人都能使用它。",
        workingFolder: "工作文件夹",
        workingFolderCaption: "智能体工作的文件夹。",
        choose: "选取…",
        approvalMode: "审批模式",
        approvalYolo: "全部执行，不再询问",
        approvalAcceptEdits: "接受文件编辑",
        approvalPlan: "仅规划",
        approvalDefault: "智能体默认",
        model: "模型",
        modelPlaceholder: "智能体默认",
        effort: "推理强度",
        effortAutomatic: "自动",
        effortLow: "低",
        effortMedium: "中",
        effortHigh: "高",
        save: "保存",
        savedRestartHint: "已保存。重新启动机器人以使用新设置。",
        saveFailed: "无法写入机器人的 .env 文件。",
        botFolder: "机器人文件夹",
        botFolderCaption: "nexus-agent 的安装位置。留空则使用 ~/.config/nexus-agent。",
        autoStart: "打开 Vitruvian 时启动机器人",
        missingToken: "添加机器人令牌以启动机器人。",
        missingBot: "此文件夹中未找到机器人。",
        missingNode: "未找到 Node.js。请使用 Homebrew 安装。",
        startFailed: "机器人无法启动。日志中可能有原因。",
        missingAgent: "未找到 Antigravity CLI (agy)。",
        quickPromptSection: "快速提问",
        quickPromptCaption: "随时随地向智能体提问。回复会显示在浮动面板中。",
        promptPlaceholder: "向 Antigravity 提问任何问题...",
        send: "发送",
        stopReply: "停止",
        newChat: "新对话",
        thinking: "正在思考…",
        working: "正在处理…",
        replyStopped: "回复已停止。",
        emptyReply: "智能体没有返回回复。",
        agentFailed: "智能体因错误而停止。",
        sessionsToggle: "最近的会话",
        planModeOn: "计划模式已开启(只读)",
        planModeOff: "开启计划模式",
        sessionsFilter: "筛选会话",
        noSessions: "没有最近的会话",
        followUpPlaceholder: "继续提问…",
        untitledSession: "无标题"
    )

    package static let zhTW = NexusAgentFeatureStrings(
        title: "Nexus Agent",
        hubDescription: "為 Antigravity 代理程式執行你的 Telegram 機器人，並透過快速提問隨時隨地向代理程式提問",
        panelCaption: "Telegram 機器人與快速提問",
        quickPromptTitle: "代理程式快速提問",
        botSection: "Telegram 機器人",
        statusRunning: "執行中",
        statusStopped: "已停止",
        start: "啟動",
        stop: "停止",
        restart: "重新啟動",
        openLog: "打開記錄",
        recentLog: "最近記錄",
        logEmpty: "尚無記錄。",
        configurationSection: "機器人設定",
        token: "機器人權杖",
        tokenCaption: "從 @BotFather 取得。只儲存在機器人的 .env 檔案中，絕不會寫入 Vitruvian 的設定或備份。",
        allowedUsers: "允許的使用者 ID",
        allowedUsersCaption: "以逗號分隔的 Telegram 使用者 ID。留空時，任何找到此機器人的人都能使用它。",
        workingFolder: "工作檔案夾",
        workingFolderCaption: "代理程式工作的檔案夾。",
        choose: "選擇…",
        approvalMode: "核准模式",
        approvalYolo: "全部執行，不再詢問",
        approvalAcceptEdits: "接受檔案編輯",
        approvalPlan: "僅規劃",
        approvalDefault: "代理程式預設",
        model: "模型",
        modelPlaceholder: "代理程式預設",
        effort: "推理強度",
        effortAutomatic: "自動",
        effortLow: "低",
        effortMedium: "中",
        effortHigh: "高",
        save: "儲存",
        savedRestartHint: "已儲存。重新啟動機器人以使用新設定。",
        saveFailed: "無法寫入機器人的 .env 檔案。",
        botFolder: "機器人檔案夾",
        botFolderCaption: "nexus-agent 的安裝位置。留空則使用 ~/.config/nexus-agent。",
        autoStart: "打開 Vitruvian 時啟動機器人",
        missingToken: "加入機器人權杖以啟動機器人。",
        missingBot: "此檔案夾中找不到機器人。",
        missingNode: "找不到 Node.js。請使用 Homebrew 安裝。",
        startFailed: "機器人無法啟動。記錄中可能有原因。",
        missingAgent: "找不到 Antigravity CLI (agy)。",
        quickPromptSection: "快速提問",
        quickPromptCaption: "隨時隨地向代理程式提問。回覆會顯示在浮動面板中。",
        promptPlaceholder: "向 Antigravity 提出任何問題...",
        send: "傳送",
        stopReply: "停止",
        newChat: "新對話",
        thinking: "正在思考…",
        working: "正在處理…",
        replyStopped: "回覆已停止。",
        emptyReply: "代理程式沒有傳回回覆。",
        agentFailed: "代理程式因錯誤而停止。",
        sessionsToggle: "最近的工作階段",
        planModeOn: "計畫模式已開啟(唯讀)",
        planModeOff: "開啟計畫模式",
        sessionsFilter: "篩選工作階段",
        noSessions: "沒有最近的工作階段",
        followUpPlaceholder: "繼續提問…",
        untitledSession: "未命名"
    )

    package static let zhHK = NexusAgentFeatureStrings(
        title: "Nexus Agent",
        hubDescription: "為 Antigravity 代理程式執行你的 Telegram 機械人，並透過快速提問隨時隨地向代理程式提問",
        panelCaption: "Telegram 機械人與快速提問",
        quickPromptTitle: "代理程式快速提問",
        botSection: "Telegram 機械人",
        statusRunning: "執行中",
        statusStopped: "已停止",
        start: "啟動",
        stop: "停止",
        restart: "重新啟動",
        openLog: "打開記錄",
        recentLog: "最近記錄",
        logEmpty: "尚未有記錄。",
        configurationSection: "機械人設定",
        token: "機械人權杖",
        tokenCaption: "從 @BotFather 取得。只會儲存在機械人的 .env 檔案中，絕不會寫入 Vitruvian 的設定或備份。",
        allowedUsers: "允許的使用者 ID",
        allowedUsersCaption: "以逗號分隔的 Telegram 使用者 ID。留空時，任何找到此機械人的人都可以使用。",
        workingFolder: "工作資料夾",
        workingFolderCaption: "代理程式工作的資料夾。",
        choose: "選擇…",
        approvalMode: "批准模式",
        approvalYolo: "全部執行，不再詢問",
        approvalAcceptEdits: "接受檔案編輯",
        approvalPlan: "只作規劃",
        approvalDefault: "代理程式預設",
        model: "模型",
        modelPlaceholder: "代理程式預設",
        effort: "推理強度",
        effortAutomatic: "自動",
        effortLow: "低",
        effortMedium: "中",
        effortHigh: "高",
        save: "儲存",
        savedRestartHint: "已儲存。重新啟動機械人以使用新設定。",
        saveFailed: "無法寫入機械人的 .env 檔案。",
        botFolder: "機械人資料夾",
        botFolderCaption: "nexus-agent 的安裝位置。留空則使用 ~/.config/nexus-agent。",
        autoStart: "打開 Vitruvian 時啟動機械人",
        missingToken: "加入機械人權杖以啟動機械人。",
        missingBot: "此資料夾中找不到機械人。",
        missingNode: "找不到 Node.js。請使用 Homebrew 安裝。",
        startFailed: "機械人無法啟動。記錄中可能有原因。",
        missingAgent: "找不到 Antigravity CLI (agy)。",
        quickPromptSection: "快速提問",
        quickPromptCaption: "隨時隨地向代理程式提問。回覆會在浮動面板中顯示。",
        promptPlaceholder: "向 Antigravity 提出任何問題...",
        send: "傳送",
        stopReply: "停止",
        newChat: "新對話",
        thinking: "正在思考…",
        working: "正在處理…",
        replyStopped: "回覆已停止。",
        emptyReply: "代理程式沒有傳回回覆。",
        agentFailed: "代理程式因錯誤而停止。",
        sessionsToggle: "最近的工作階段",
        planModeOn: "計劃模式已開啟(唯讀)",
        planModeOff: "開啟計劃模式",
        sessionsFilter: "篩選工作階段",
        noSessions: "沒有最近的工作階段",
        followUpPlaceholder: "繼續提問…",
        untitledSession: "未命名"
    )
}
