// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 VitruvianSoftware

import Foundation

/// The words of GitHub in the notch: its Features entry and its Settings tab.
package struct NotchGitHubStrings {
    package let title: String
    package let description: String
    package let notConnected: String
    package let connecting: String
    /// `%@` is the GitHub login, without the `@`.
    package let connectedAsFormat: String
    package let connect: String
    package let useCode: String
    package let codeHint: String
    package let copy: String
    package let openDevicePage: String
    package let disconnect: String
    package let cancel: String
    package let tryAgain: String
    package let notConfigured: String
    package let notConfiguredHint: String
    package let mouseIndicator: String
    package let noMouse: String
    package let advanced: String
    package let relayURL: String
    package let clientID: String
    package let watchedRepositories: String
    package let noRepositories: String
    package let watchlistLater: String
    /// `%@` is the relay's host (design spec §6 row 1).
    package let relayUnreachableFormat: String
    /// The relay's host, then the `error` it answered with.
    package let relayRefusedFormat: String
    package let stateMismatch: String
    package let denied: String
    package let badCallback: String
    package let browserFailed: String
    package let codeExpired: String
    package let gitHubUnreachable: String
    /// `%@` is the HTTP status code.
    package let gitHubRefusedFormat: String
    /// `%@` is the Keychain's OSStatus.
    package let keychainFormat: String
    /// `%@` is GitHub's `error` value, such as `device_flow_disabled`.
    package let deviceFlowFormat: String
    package let invalidRelayURL: String

    package func connectedAs(_ login: String) -> String {
        String(format: connectedAsFormat, locale: Locale.current, login)
    }

    /// What Settings says about a sign-in that did not finish.
    package func message(for error: GitHubAuthError) -> String {
        switch error {
        case .notConfigured: return notConfiguredHint
        case .invalidRelayURL: return invalidRelayURL
        case .relayUnreachable(let host):
            return String(format: relayUnreachableFormat, locale: Locale.current, host)
        case .relayRefused(let host, let reason):
            return String(format: relayRefusedFormat, locale: Locale.current, host, reason)
        case .callback(.stateMismatch): return stateMismatch
        case .callback(.denied), .deviceFlow(.denied): return denied
        case .callback: return badCallback
        case .browserFailed: return browserFailed
        case .deviceFlow(.expired): return codeExpired
        case .deviceFlow(.other(let reason)):
            return String(format: deviceFlowFormat, locale: Locale.current, reason)
        case .gitHubUnreachable: return gitHubUnreachable
        case .gitHubRefused(let status):
            return String(format: gitHubRefusedFormat, locale: Locale.current, String(status))
        case .keychain(let status):
            return String(format: keychainFormat, locale: Locale.current, String(status))
        }
    }
}

extension FeatureStrings {
    package static func notchGitHub(_ language: AppLanguage) -> NotchGitHubStrings {
        switch language {
        case .enUS: return NotchGitHubStrings(
            title: "GitHub",
            description: "Shows whether main is green on the repositories you watch and where your pull requests stand.",
            notConnected: "Not connected",
            connecting: "Connecting…",
            connectedAsFormat: "Connected as @%@",
            connect: "Connect GitHub",
            useCode: "Use a code instead",
            codeHint: "Enter this code on GitHub to finish connecting.",
            copy: "Copy",
            openDevicePage: "Open github.com/login/device",
            disconnect: "Disconnect",
            cancel: "Cancel",
            tryAgain: "Try Again",
            notConfigured: "GitHub App not configured",
            notConfiguredHint: "Add the GitHub App’s client ID under Advanced to connect.",
            mouseIndicator: "Show status on the GravaStar mouse",
            noMouse: "No GravaStar mouse found",
            advanced: "Advanced",
            relayURL: "Relay URL",
            clientID: "Client ID",
            watchedRepositories: "Watched repositories",
            noRepositories: "No repositories are watched.",
            watchlistLater: "Choosing repositories arrives in a later update.",
            relayUnreachableFormat: "Couldn’t reach the sign-in relay at %@. Use a code instead to connect without it.",
            relayRefusedFormat: "The sign-in relay at %@ refused the sign-in (%@).",
            stateMismatch: "The reply from GitHub didn’t belong to this sign-in, so it was ignored. Try again.",
            denied: "GitHub access wasn’t allowed.",
            badCallback: "GitHub sent back an unexpected reply. Try again.",
            browserFailed: "The sign-in window couldn’t open.",
            codeExpired: "The code expired. Ask for a new one.",
            gitHubUnreachable: "Couldn’t reach GitHub. Check your connection and try again.",
            gitHubRefusedFormat: "GitHub refused the request (HTTP %@).",
            keychainFormat: "The Keychain couldn’t keep the sign-in (error %@).",
            deviceFlowFormat: "GitHub couldn’t start the code sign-in (%@).",
            invalidRelayURL: "The relay URL under Advanced isn’t a valid web address.")
        case .ptBR: return NotchGitHubStrings(
            title: "GitHub",
            description: "Mostra se a main está verde nos repositórios que você acompanha e em que pé estão seus pull requests.",
            notConnected: "Não conectado",
            connecting: "Conectando…",
            connectedAsFormat: "Conectado como @%@",
            connect: "Conectar GitHub",
            useCode: "Usar um código",
            codeHint: "Digite este código no GitHub para concluir a conexão.",
            copy: "Copiar",
            openDevicePage: "Abrir github.com/login/device",
            disconnect: "Desconectar",
            cancel: "Cancelar",
            tryAgain: "Tentar de Novo",
            notConfigured: "App do GitHub não configurado",
            notConfiguredHint: "Adicione o client ID do App do GitHub em Avançado para conectar.",
            mouseIndicator: "Mostrar o status no mouse GravaStar",
            noMouse: "Nenhum mouse GravaStar encontrado",
            advanced: "Avançado",
            relayURL: "URL do relay",
            clientID: "Client ID",
            watchedRepositories: "Repositórios acompanhados",
            noRepositories: "Nenhum repositório acompanhado.",
            watchlistLater: "A escolha de repositórios chega em uma próxima atualização.",
            relayUnreachableFormat: "Não foi possível acessar o relay de login em %@. Use um código para conectar sem ele.",
            relayRefusedFormat: "O relay de login em %@ recusou o login (%@).",
            stateMismatch: "A resposta do GitHub não era deste login, então foi ignorada. Tente de novo.",
            denied: "O acesso ao GitHub não foi permitido.",
            badCallback: "O GitHub enviou uma resposta inesperada. Tente de novo.",
            browserFailed: "A janela de login não abriu.",
            codeExpired: "O código expirou. Peça um novo.",
            gitHubUnreachable: "Não foi possível acessar o GitHub. Verifique sua conexão e tente de novo.",
            gitHubRefusedFormat: "O GitHub recusou o pedido (HTTP %@).",
            keychainFormat: "O Keychain não conseguiu guardar o login (erro %@).",
            deviceFlowFormat: "O GitHub não conseguiu iniciar o login por código (%@).",
            invalidRelayURL: "A URL do relay em Avançado não é um endereço web válido.")
        case .es: return NotchGitHubStrings(
            title: "GitHub",
            description: "Muestra si main está en verde en los repositorios que sigues y en qué punto están tus pull requests.",
            notConnected: "No conectado",
            connecting: "Conectando…",
            connectedAsFormat: "Conectado como @%@",
            connect: "Conectar GitHub",
            useCode: "Usar un código",
            codeHint: "Introduce este código en GitHub para terminar de conectar.",
            copy: "Copiar",
            openDevicePage: "Abrir github.com/login/device",
            disconnect: "Desconectar",
            cancel: "Cancelar",
            tryAgain: "Reintentar",
            notConfigured: "App de GitHub sin configurar",
            notConfiguredHint: "Añade el client ID de la App de GitHub en Avanzado para conectar.",
            mouseIndicator: "Mostrar el estado en el ratón GravaStar",
            noMouse: "No se encontró ningún ratón GravaStar",
            advanced: "Avanzado",
            relayURL: "URL del relay",
            clientID: "Client ID",
            watchedRepositories: "Repositorios seguidos",
            noRepositories: "No sigues ningún repositorio.",
            watchlistLater: "La elección de repositorios llegará en una próxima actualización.",
            relayUnreachableFormat: "No se pudo contactar con el relay de inicio de sesión en %@. Usa un código para conectar sin él.",
            relayRefusedFormat: "El relay de inicio de sesión en %@ rechazó el inicio de sesión (%@).",
            stateMismatch: "La respuesta de GitHub no correspondía a este inicio de sesión, así que se ignoró. Inténtalo de nuevo.",
            denied: "No se permitió el acceso a GitHub.",
            badCallback: "GitHub devolvió una respuesta inesperada. Inténtalo de nuevo.",
            browserFailed: "No se pudo abrir la ventana de inicio de sesión.",
            codeExpired: "El código caducó. Pide uno nuevo.",
            gitHubUnreachable: "No se pudo contactar con GitHub. Revisa tu conexión e inténtalo de nuevo.",
            gitHubRefusedFormat: "GitHub rechazó la solicitud (HTTP %@).",
            keychainFormat: "El llavero no pudo guardar el inicio de sesión (error %@).",
            deviceFlowFormat: "GitHub no pudo iniciar el inicio de sesión con código (%@).",
            invalidRelayURL: "La URL del relay en Avanzado no es una dirección web válida.")
        case .sk: return NotchGitHubStrings(
            title: "GitHub",
            description: "Ukazuje, či je main zelená v repozitároch, ktoré sledujete, a ako sú na tom vaše pull requesty.",
            notConnected: "Nepripojené",
            connecting: "Pripája sa…",
            connectedAsFormat: "Pripojené ako @%@",
            connect: "Pripojiť GitHub",
            useCode: "Použiť kód",
            codeHint: "Zadajte tento kód na GitHube a dokončite pripojenie.",
            copy: "Kopírovať",
            openDevicePage: "Otvoriť github.com/login/device",
            disconnect: "Odpojiť",
            cancel: "Zrušiť",
            tryAgain: "Skúsiť znova",
            notConfigured: "Aplikácia GitHub nie je nastavená",
            notConfiguredHint: "Pre pripojenie pridajte client ID aplikácie GitHub v časti Pokročilé.",
            mouseIndicator: "Zobraziť stav na myši GravaStar",
            noMouse: "Nenašla sa žiadna myš GravaStar",
            advanced: "Pokročilé",
            relayURL: "URL relay",
            clientID: "Client ID",
            watchedRepositories: "Sledované repozitáre",
            noRepositories: "Nesledujete žiadny repozitár.",
            watchlistLater: "Výber repozitárov príde v niektorej z ďalších aktualizácií.",
            relayUnreachableFormat: "Prihlasovací relay na %@ je nedostupný. Použite kód a pripojte sa bez neho.",
            relayRefusedFormat: "Prihlasovací relay na %@ odmietol prihlásenie (%@).",
            stateMismatch: "Odpoveď z GitHubu nepatrila k tomuto prihláseniu, preto bola ignorovaná. Skúste to znova.",
            denied: "Prístup ku GitHubu nebol povolený.",
            badCallback: "GitHub poslal neočakávanú odpoveď. Skúste to znova.",
            browserFailed: "Prihlasovacie okno sa nepodarilo otvoriť.",
            codeExpired: "Platnosť kódu vypršala. Vyžiadajte si nový.",
            gitHubUnreachable: "GitHub je nedostupný. Skontrolujte pripojenie a skúste to znova.",
            gitHubRefusedFormat: "GitHub odmietol požiadavku (HTTP %@).",
            keychainFormat: "Kľúčenka nedokázala uložiť prihlásenie (chyba %@).",
            deviceFlowFormat: "GitHub nedokázal spustiť prihlásenie kódom (%@).",
            invalidRelayURL: "URL relay v časti Pokročilé nie je platná webová adresa.")
        case .de: return NotchGitHubStrings(
            title: "GitHub",
            description: "Zeigt, ob main in den beobachteten Repositorys grün ist und wo deine Pull Requests stehen.",
            notConnected: "Nicht verbunden",
            connecting: "Verbinden …",
            connectedAsFormat: "Verbunden als @%@",
            connect: "GitHub verbinden",
            useCode: "Stattdessen einen Code verwenden",
            codeHint: "Gib diesen Code auf GitHub ein, um die Verbindung abzuschließen.",
            copy: "Kopieren",
            openDevicePage: "github.com/login/device öffnen",
            disconnect: "Trennen",
            cancel: "Abbrechen",
            tryAgain: "Erneut versuchen",
            notConfigured: "GitHub-App nicht eingerichtet",
            notConfiguredHint: "Trage unter „Erweitert“ die Client-ID der GitHub-App ein, um zu verbinden.",
            mouseIndicator: "Status auf der GravaStar-Maus zeigen",
            noMouse: "Keine GravaStar-Maus gefunden",
            advanced: "Erweitert",
            relayURL: "Relay-URL",
            clientID: "Client-ID",
            watchedRepositories: "Beobachtete Repositorys",
            noRepositories: "Es werden keine Repositorys beobachtet.",
            watchlistLater: "Die Auswahl der Repositorys kommt mit einem späteren Update.",
            relayUnreachableFormat: "Das Anmelde-Relay unter %@ ist nicht erreichbar. Verwende einen Code, um ohne es zu verbinden.",
            relayRefusedFormat: "Das Anmelde-Relay unter %@ hat die Anmeldung abgelehnt (%@).",
            stateMismatch: "Die Antwort von GitHub gehörte nicht zu dieser Anmeldung und wurde ignoriert. Versuche es erneut.",
            denied: "Der Zugriff auf GitHub wurde nicht erlaubt.",
            badCallback: "GitHub hat eine unerwartete Antwort gesendet. Versuche es erneut.",
            browserFailed: "Das Anmeldefenster konnte nicht geöffnet werden.",
            codeExpired: "Der Code ist abgelaufen. Fordere einen neuen an.",
            gitHubUnreachable: "GitHub ist nicht erreichbar. Prüfe deine Verbindung und versuche es erneut.",
            gitHubRefusedFormat: "GitHub hat die Anfrage abgelehnt (HTTP %@).",
            keychainFormat: "Der Schlüsselbund konnte die Anmeldung nicht speichern (Fehler %@).",
            deviceFlowFormat: "GitHub konnte die Anmeldung per Code nicht starten (%@).",
            invalidRelayURL: "Die Relay-URL unter „Erweitert“ ist keine gültige Webadresse.")
        case .fr: return NotchGitHubStrings(
            title: "GitHub",
            description: "Indique si main est au vert dans les dépôts que vous suivez et où en sont vos pull requests.",
            notConnected: "Non connecté",
            connecting: "Connexion…",
            connectedAsFormat: "Connecté en tant que @%@",
            connect: "Connecter GitHub",
            useCode: "Utiliser un code",
            codeHint: "Saisissez ce code sur GitHub pour terminer la connexion.",
            copy: "Copier",
            openDevicePage: "Ouvrir github.com/login/device",
            disconnect: "Déconnecter",
            cancel: "Annuler",
            tryAgain: "Réessayer",
            notConfigured: "App GitHub non configurée",
            notConfiguredHint: "Ajoutez le client ID de l’app GitHub dans Avancé pour vous connecter.",
            mouseIndicator: "Afficher l’état sur la souris GravaStar",
            noMouse: "Aucune souris GravaStar trouvée",
            advanced: "Avancé",
            relayURL: "URL du relais",
            clientID: "Client ID",
            watchedRepositories: "Dépôts suivis",
            noRepositories: "Aucun dépôt n’est suivi.",
            watchlistLater: "Le choix des dépôts arrivera dans une prochaine mise à jour.",
            relayUnreachableFormat: "Impossible de joindre le relais de connexion sur %@. Utilisez un code pour vous connecter sans lui.",
            relayRefusedFormat: "Le relais de connexion sur %@ a refusé la connexion (%@).",
            stateMismatch: "La réponse de GitHub ne correspondait pas à cette connexion, elle a donc été ignorée. Réessayez.",
            denied: "L’accès à GitHub n’a pas été autorisé.",
            badCallback: "GitHub a renvoyé une réponse inattendue. Réessayez.",
            browserFailed: "La fenêtre de connexion n’a pas pu s’ouvrir.",
            codeExpired: "Le code a expiré. Demandez-en un nouveau.",
            gitHubUnreachable: "Impossible de joindre GitHub. Vérifiez votre connexion et réessayez.",
            gitHubRefusedFormat: "GitHub a refusé la requête (HTTP %@).",
            keychainFormat: "Le trousseau n’a pas pu conserver la connexion (erreur %@).",
            deviceFlowFormat: "GitHub n’a pas pu lancer la connexion par code (%@).",
            invalidRelayURL: "L’URL du relais dans Avancé n’est pas une adresse web valide.")
        case .it: return NotchGitHubStrings(
            title: "GitHub",
            description: "Mostra se main è verde nei repository che segui e a che punto sono le tue pull request.",
            notConnected: "Non connesso",
            connecting: "Connessione…",
            connectedAsFormat: "Connesso come @%@",
            connect: "Connetti GitHub",
            useCode: "Usa un codice",
            codeHint: "Inserisci questo codice su GitHub per completare la connessione.",
            copy: "Copia",
            openDevicePage: "Apri github.com/login/device",
            disconnect: "Disconnetti",
            cancel: "Annulla",
            tryAgain: "Riprova",
            notConfigured: "App GitHub non configurata",
            notConfiguredHint: "Aggiungi il client ID dell’app GitHub in Avanzate per connetterti.",
            mouseIndicator: "Mostra lo stato sul mouse GravaStar",
            noMouse: "Nessun mouse GravaStar trovato",
            advanced: "Avanzate",
            relayURL: "URL del relay",
            clientID: "Client ID",
            watchedRepositories: "Repository seguiti",
            noRepositories: "Nessun repository seguito.",
            watchlistLater: "La scelta dei repository arriverà con un prossimo aggiornamento.",
            relayUnreachableFormat: "Impossibile raggiungere il relay di accesso su %@. Usa un codice per connetterti senza.",
            relayRefusedFormat: "Il relay di accesso su %@ ha rifiutato l’accesso (%@).",
            stateMismatch: "La risposta di GitHub non apparteneva a questo accesso, quindi è stata ignorata. Riprova.",
            denied: "L’accesso a GitHub non è stato consentito.",
            badCallback: "GitHub ha inviato una risposta inattesa. Riprova.",
            browserFailed: "Impossibile aprire la finestra di accesso.",
            codeExpired: "Il codice è scaduto. Richiedine uno nuovo.",
            gitHubUnreachable: "Impossibile raggiungere GitHub. Controlla la connessione e riprova.",
            gitHubRefusedFormat: "GitHub ha rifiutato la richiesta (HTTP %@).",
            keychainFormat: "Il portachiavi non è riuscito a conservare l’accesso (errore %@).",
            deviceFlowFormat: "GitHub non è riuscito ad avviare l’accesso con codice (%@).",
            invalidRelayURL: "L’URL del relay in Avanzate non è un indirizzo web valido.")
        case .ru: return NotchGitHubStrings(
            title: "GitHub",
            description: "Показывает, зелёная ли main в отслеживаемых репозиториях и в каком состоянии ваши pull request.",
            notConnected: "Не подключено",
            connecting: "Подключение…",
            connectedAsFormat: "Подключено как @%@",
            connect: "Подключить GitHub",
            useCode: "Войти по коду",
            codeHint: "Введите этот код на GitHub, чтобы завершить подключение.",
            copy: "Скопировать",
            openDevicePage: "Открыть github.com/login/device",
            disconnect: "Отключить",
            cancel: "Отменить",
            tryAgain: "Повторить",
            notConfigured: "Приложение GitHub не настроено",
            notConfiguredHint: "Чтобы подключиться, укажите client ID приложения GitHub в разделе «Дополнительно».",
            mouseIndicator: "Показывать статус на мыши GravaStar",
            noMouse: "Мышь GravaStar не найдена",
            advanced: "Дополнительно",
            relayURL: "URL ретранслятора",
            clientID: "Client ID",
            watchedRepositories: "Отслеживаемые репозитории",
            noRepositories: "Нет отслеживаемых репозиториев.",
            watchlistLater: "Выбор репозиториев появится в одном из следующих обновлений.",
            relayUnreachableFormat: "Не удалось связаться с ретранслятором входа %@. Войдите по коду, чтобы подключиться без него.",
            relayRefusedFormat: "Ретранслятор входа %@ отклонил вход (%@).",
            stateMismatch: "Ответ GitHub не относился к этому входу и был проигнорирован. Попробуйте снова.",
            denied: "Доступ к GitHub не разрешён.",
            badCallback: "GitHub прислал неожиданный ответ. Попробуйте снова.",
            browserFailed: "Не удалось открыть окно входа.",
            codeExpired: "Срок действия кода истёк. Запросите новый.",
            gitHubUnreachable: "Не удалось связаться с GitHub. Проверьте подключение и попробуйте снова.",
            gitHubRefusedFormat: "GitHub отклонил запрос (HTTP %@).",
            keychainFormat: "Связке ключей не удалось сохранить вход (ошибка %@).",
            deviceFlowFormat: "GitHub не смог начать вход по коду (%@).",
            invalidRelayURL: "URL ретранслятора в разделе «Дополнительно» не является веб-адресом.")
        case .tr: return NotchGitHubStrings(
            title: "GitHub",
            description: "İzlediğiniz depolarda main’in yeşil olup olmadığını ve pull request’lerinizin durumunu gösterir.",
            notConnected: "Bağlı değil",
            connecting: "Bağlanıyor…",
            connectedAsFormat: "@%@ olarak bağlı",
            connect: "GitHub’a Bağlan",
            useCode: "Bunun yerine kod kullan",
            codeHint: "Bağlantıyı tamamlamak için bu kodu GitHub’a girin.",
            copy: "Kopyala",
            openDevicePage: "github.com/login/device’ı aç",
            disconnect: "Bağlantıyı Kes",
            cancel: "Vazgeç",
            tryAgain: "Yeniden Dene",
            notConfigured: "GitHub App yapılandırılmadı",
            notConfiguredHint: "Bağlanmak için GitHub App’in client ID’sini Gelişmiş bölümüne ekleyin.",
            mouseIndicator: "Durumu GravaStar farede göster",
            noMouse: "GravaStar fare bulunamadı",
            advanced: "Gelişmiş",
            relayURL: "Aktarıcı URL’si",
            clientID: "Client ID",
            watchedRepositories: "İzlenen depolar",
            noRepositories: "İzlenen depo yok.",
            watchlistLater: "Depo seçimi sonraki bir güncellemeyle gelecek.",
            relayUnreachableFormat: "%@ adresindeki oturum açma aktarıcısına ulaşılamadı. Onsuz bağlanmak için kod kullanın.",
            relayRefusedFormat: "%@ adresindeki oturum açma aktarıcısı oturum açmayı reddetti (%@).",
            stateMismatch: "GitHub’dan gelen yanıt bu oturum açmaya ait değildi, bu yüzden yok sayıldı. Yeniden deneyin.",
            denied: "GitHub erişimine izin verilmedi.",
            badCallback: "GitHub beklenmeyen bir yanıt gönderdi. Yeniden deneyin.",
            browserFailed: "Oturum açma penceresi açılamadı.",
            codeExpired: "Kodun süresi doldu. Yeni bir kod isteyin.",
            gitHubUnreachable: "GitHub’a ulaşılamadı. Bağlantınızı kontrol edip yeniden deneyin.",
            gitHubRefusedFormat: "GitHub isteği reddetti (HTTP %@).",
            keychainFormat: "Anahtar Zinciri oturum açmayı saklayamadı (hata %@).",
            deviceFlowFormat: "GitHub kodla oturum açmayı başlatamadı (%@).",
            invalidRelayURL: "Gelişmiş bölümündeki aktarıcı URL’si geçerli bir web adresi değil.")
        case .ja: return NotchGitHubStrings(
            title: "GitHub",
            description: "監視しているリポジトリで main がグリーンかどうかと、プルリクエストの状況を表示します。",
            notConnected: "未接続",
            connecting: "接続中…",
            connectedAsFormat: "@%@ として接続済み",
            connect: "GitHub に接続",
            useCode: "代わりにコードを使う",
            codeHint: "接続を完了するには、このコードを GitHub に入力してください。",
            copy: "コピー",
            openDevicePage: "github.com/login/device を開く",
            disconnect: "接続解除",
            cancel: "キャンセル",
            tryAgain: "再試行",
            notConfigured: "GitHub App が未設定です",
            notConfiguredHint: "接続するには、「詳細」に GitHub App のクライアント ID を追加してください。",
            mouseIndicator: "GravaStar マウスに状態を表示",
            noMouse: "GravaStar マウスが見つかりません",
            advanced: "詳細",
            relayURL: "リレー URL",
            clientID: "クライアント ID",
            watchedRepositories: "監視中のリポジトリ",
            noRepositories: "監視中のリポジトリはありません。",
            watchlistLater: "リポジトリの選択は今後のアップデートで追加されます。",
            relayUnreachableFormat: "%@ のサインインリレーに接続できませんでした。リレーなしで接続するにはコードを使ってください。",
            relayRefusedFormat: "%@ のサインインリレーがサインインを拒否しました（%@）。",
            stateMismatch: "GitHub からの応答はこのサインインのものではなかったため無視しました。もう一度お試しください。",
            denied: "GitHub へのアクセスは許可されませんでした。",
            badCallback: "GitHub から予期しない応答がありました。もう一度お試しください。",
            browserFailed: "サインインウインドウを開けませんでした。",
            codeExpired: "コードの有効期限が切れました。新しいコードを取得してください。",
            gitHubUnreachable: "GitHub に接続できませんでした。接続を確認してもう一度お試しください。",
            gitHubRefusedFormat: "GitHub がリクエストを拒否しました（HTTP %@）。",
            keychainFormat: "キーチェーンにサインイン情報を保存できませんでした（エラー %@）。",
            deviceFlowFormat: "GitHub はコードによるサインインを開始できませんでした（%@）。",
            invalidRelayURL: "「詳細」のリレー URL が有効な Web アドレスではありません。")
        case .ko: return NotchGitHubStrings(
            title: "GitHub",
            description: "지켜보는 저장소에서 main이 초록색인지, 내 풀 리퀘스트가 어디까지 왔는지 보여 줍니다.",
            notConnected: "연결되지 않음",
            connecting: "연결 중…",
            connectedAsFormat: "@%@(으)로 연결됨",
            connect: "GitHub 연결",
            useCode: "대신 코드 사용",
            codeHint: "연결을 마치려면 GitHub에 이 코드를 입력하세요.",
            copy: "복사",
            openDevicePage: "github.com/login/device 열기",
            disconnect: "연결 해제",
            cancel: "취소",
            tryAgain: "다시 시도",
            notConfigured: "GitHub 앱이 설정되지 않음",
            notConfiguredHint: "연결하려면 고급에 GitHub 앱의 클라이언트 ID를 추가하세요.",
            mouseIndicator: "GravaStar 마우스에 상태 표시",
            noMouse: "GravaStar 마우스를 찾을 수 없음",
            advanced: "고급",
            relayURL: "릴레이 URL",
            clientID: "클라이언트 ID",
            watchedRepositories: "지켜보는 저장소",
            noRepositories: "지켜보는 저장소가 없습니다.",
            watchlistLater: "저장소 선택은 이후 업데이트에서 제공됩니다.",
            relayUnreachableFormat: "%@의 로그인 릴레이에 연결할 수 없습니다. 릴레이 없이 연결하려면 코드를 사용하세요.",
            relayRefusedFormat: "%@의 로그인 릴레이가 로그인을 거부했습니다(%@).",
            stateMismatch: "GitHub의 응답이 이 로그인에 해당하지 않아 무시했습니다. 다시 시도하세요.",
            denied: "GitHub 접근이 허용되지 않았습니다.",
            badCallback: "GitHub에서 예상치 못한 응답을 보냈습니다. 다시 시도하세요.",
            browserFailed: "로그인 윈도우를 열 수 없습니다.",
            codeExpired: "코드가 만료되었습니다. 새 코드를 요청하세요.",
            gitHubUnreachable: "GitHub에 연결할 수 없습니다. 연결 상태를 확인하고 다시 시도하세요.",
            gitHubRefusedFormat: "GitHub가 요청을 거부했습니다(HTTP %@).",
            keychainFormat: "키체인에 로그인 정보를 보관하지 못했습니다(오류 %@).",
            deviceFlowFormat: "GitHub가 코드 로그인을 시작하지 못했습니다(%@).",
            invalidRelayURL: "고급의 릴레이 URL이 올바른 웹 주소가 아닙니다.")
        case .uk: return NotchGitHubStrings(
            title: "GitHub",
            description: "Показує, чи зелена main у репозиторіях, за якими ви стежите, і на якому етапі ваші pull request.",
            notConnected: "Не під’єднано",
            connecting: "Під’єднання…",
            connectedAsFormat: "Під’єднано як @%@",
            connect: "Під’єднати GitHub",
            useCode: "Увійти за кодом",
            codeHint: "Введіть цей код на GitHub, щоб завершити під’єднання.",
            copy: "Скопіювати",
            openDevicePage: "Відкрити github.com/login/device",
            disconnect: "Від’єднати",
            cancel: "Скасувати",
            tryAgain: "Повторити",
            notConfigured: "Застосунок GitHub не налаштовано",
            notConfiguredHint: "Щоб під’єднатися, додайте client ID застосунку GitHub у розділі «Додатково».",
            mouseIndicator: "Показувати стан на миші GravaStar",
            noMouse: "Мишу GravaStar не знайдено",
            advanced: "Додатково",
            relayURL: "URL ретранслятора",
            clientID: "Client ID",
            watchedRepositories: "Відстежувані репозиторії",
            noRepositories: "Немає відстежуваних репозиторіїв.",
            watchlistLater: "Вибір репозиторіїв з’явиться в одному з наступних оновлень.",
            relayUnreachableFormat: "Не вдалося зв’язатися з ретранслятором входу %@. Увійдіть за кодом, щоб під’єднатися без нього.",
            relayRefusedFormat: "Ретранслятор входу %@ відхилив вхід (%@).",
            stateMismatch: "Відповідь GitHub не стосувалася цього входу, тому її проігноровано. Спробуйте ще раз.",
            denied: "Доступ до GitHub не дозволено.",
            badCallback: "GitHub надіслав неочікувану відповідь. Спробуйте ще раз.",
            browserFailed: "Не вдалося відкрити вікно входу.",
            codeExpired: "Термін дії коду минув. Запросіть новий.",
            gitHubUnreachable: "Не вдалося зв’язатися з GitHub. Перевірте з’єднання і спробуйте ще раз.",
            gitHubRefusedFormat: "GitHub відхилив запит (HTTP %@).",
            keychainFormat: "Звʼязці ключів не вдалося зберегти вхід (помилка %@).",
            deviceFlowFormat: "GitHub не зміг почати вхід за кодом (%@).",
            invalidRelayURL: "URL ретранслятора в розділі «Додатково» не є вебадресою.")
        case .zhHans: return NotchGitHubStrings(
            title: "GitHub",
            description: "显示你关注的仓库中 main 是否为绿色，以及你的拉取请求进展如何。",
            notConnected: "未连接",
            connecting: "正在连接…",
            connectedAsFormat: "已连接为 @%@",
            connect: "连接 GitHub",
            useCode: "改用代码",
            codeHint: "在 GitHub 上输入此代码以完成连接。",
            copy: "拷贝",
            openDevicePage: "打开 github.com/login/device",
            disconnect: "断开连接",
            cancel: "取消",
            tryAgain: "重试",
            notConfigured: "GitHub App 尚未配置",
            notConfiguredHint: "要连接，请在“高级”中添加 GitHub App 的客户端 ID。",
            mouseIndicator: "在 GravaStar 鼠标上显示状态",
            noMouse: "未找到 GravaStar 鼠标",
            advanced: "高级",
            relayURL: "中继 URL",
            clientID: "客户端 ID",
            watchedRepositories: "关注的仓库",
            noRepositories: "未关注任何仓库。",
            watchlistLater: "选择仓库将在后续更新中推出。",
            relayUnreachableFormat: "无法连接 %@ 上的登录中继。改用代码即可不经中继连接。",
            relayRefusedFormat: "%@ 上的登录中继拒绝了登录（%@）。",
            stateMismatch: "GitHub 的回复不属于这次登录，已忽略。请重试。",
            denied: "未允许访问 GitHub。",
            badCallback: "GitHub 返回了意外的回复。请重试。",
            browserFailed: "无法打开登录窗口。",
            codeExpired: "代码已过期。请获取新代码。",
            gitHubUnreachable: "无法连接 GitHub。请检查网络连接后重试。",
            gitHubRefusedFormat: "GitHub 拒绝了请求（HTTP %@）。",
            keychainFormat: "钥匙串无法保存登录信息（错误 %@）。",
            deviceFlowFormat: "GitHub 无法开始代码登录（%@）。",
            invalidRelayURL: "“高级”中的中继 URL 不是有效的网址。")
        case .zhTW: return NotchGitHubStrings(
            title: "GitHub",
            description: "顯示你關注的儲存庫中 main 是否為綠色，以及你的拉取要求進度如何。",
            notConnected: "未連線",
            connecting: "正在連線…",
            connectedAsFormat: "已連線為 @%@",
            connect: "連線 GitHub",
            useCode: "改用代碼",
            codeHint: "在 GitHub 上輸入此代碼以完成連線。",
            copy: "拷貝",
            openDevicePage: "打開 github.com/login/device",
            disconnect: "中斷連線",
            cancel: "取消",
            tryAgain: "重試",
            notConfigured: "GitHub App 尚未設定",
            notConfiguredHint: "若要連線，請在「進階」中加入 GitHub App 的用戶端 ID。",
            mouseIndicator: "在 GravaStar 滑鼠上顯示狀態",
            noMouse: "找不到 GravaStar 滑鼠",
            advanced: "進階",
            relayURL: "中繼 URL",
            clientID: "用戶端 ID",
            watchedRepositories: "關注的儲存庫",
            noRepositories: "未關注任何儲存庫。",
            watchlistLater: "選擇儲存庫將在之後的更新中推出。",
            relayUnreachableFormat: "無法連線至 %@ 上的登入中繼。改用代碼即可不經中繼連線。",
            relayRefusedFormat: "%@ 上的登入中繼拒絕了登入（%@）。",
            stateMismatch: "GitHub 的回覆不屬於這次登入，已忽略。請重試。",
            denied: "未允許存取 GitHub。",
            badCallback: "GitHub 傳回了非預期的回覆。請重試。",
            browserFailed: "無法打開登入視窗。",
            codeExpired: "代碼已過期。請取得新代碼。",
            gitHubUnreachable: "無法連線至 GitHub。請檢查網路連線後重試。",
            gitHubRefusedFormat: "GitHub 拒絕了要求（HTTP %@）。",
            keychainFormat: "鑰匙圈無法儲存登入資訊（錯誤 %@）。",
            deviceFlowFormat: "GitHub 無法開始代碼登入（%@）。",
            invalidRelayURL: "「進階」中的中繼 URL 不是有效的網址。")
        case .zhHK: return NotchGitHubStrings(
            title: "GitHub",
            description: "顯示你關注的儲存庫中 main 是否為綠色，以及你的拉取要求進度如何。",
            notConnected: "未連線",
            connecting: "正在連線…",
            connectedAsFormat: "已連線為 @%@",
            connect: "連線 GitHub",
            useCode: "改用代碼",
            codeHint: "在 GitHub 上輸入此代碼以完成連線。",
            copy: "拷貝",
            openDevicePage: "打開 github.com/login/device",
            disconnect: "中斷連線",
            cancel: "取消",
            tryAgain: "重試",
            notConfigured: "GitHub App 尚未設定",
            notConfiguredHint: "如要連線，請在「進階」中加入 GitHub App 的用戶端 ID。",
            mouseIndicator: "在 GravaStar 滑鼠上顯示狀態",
            noMouse: "找不到 GravaStar 滑鼠",
            advanced: "進階",
            relayURL: "中繼 URL",
            clientID: "用戶端 ID",
            watchedRepositories: "關注的儲存庫",
            noRepositories: "未關注任何儲存庫。",
            watchlistLater: "選擇儲存庫將在之後的更新中推出。",
            relayUnreachableFormat: "無法連線至 %@ 上的登入中繼。改用代碼即可不經中繼連線。",
            relayRefusedFormat: "%@ 上的登入中繼拒絕了登入（%@）。",
            stateMismatch: "GitHub 的回覆不屬於這次登入，已忽略。請重試。",
            denied: "未允許存取 GitHub。",
            badCallback: "GitHub 傳回了非預期的回覆。請重試。",
            browserFailed: "無法打開登入視窗。",
            codeExpired: "代碼已過期。請取得新代碼。",
            gitHubUnreachable: "無法連線至 GitHub。請檢查網絡連線後重試。",
            gitHubRefusedFormat: "GitHub 拒絕了要求（HTTP %@）。",
            keychainFormat: "鑰匙圈無法儲存登入資訊（錯誤 %@）。",
            deviceFlowFormat: "GitHub 無法開始代碼登入（%@）。",
            invalidRelayURL: "「進階」中的中繼 URL 不是有效的網址。")
        }
    }
}
