// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 VitruvianSoftware

import Foundation

/// The preferences declared with their defaults (see `Preference`). Every
/// default `Defaults.registeredDefaults` registers comes from here, so a view
/// or a service that reads a preference through it starts from the same one
/// (REFACTOR.md step 6).
package enum Preferences {
    /// Owner's call: compact by default in 3.1.8.
    package static let menuBarMetricSpacing = Preference(DefaultsKey.menuBarMetricSpacing, default: "compact")
    package static let menuBarMetricOrder = Preference(
        DefaultsKey.menuBarMetricOrder, default: Defaults.defaultMenuBarMetricOrder.joined(separator: ","))
    /// Owner's call: on by default in 3.1.8. The badge only shows while the
    /// microphone is muted.
    package static let micMuteMenuBarIndicator = Preference(DefaultsKey.micMuteMenuBarIndicator, default: true)
    package static let screenshotPreviewPosition = Preference(
        DefaultsKey.screenshotPreviewPosition, default: ScreenshotSupport.QuickPreviewPosition.automatic.rawValue)
    package static let windowLayoutShortcutsEnabled = Preference(DefaultsKey.windowLayoutShortcutsEnabled, default: false)

    // MARK: Switches

    package static let liquidGlassEnabled = Preference(DefaultsKey.liquidGlassEnabled, default: false)
    package static let notchLiquidGlassEnabled = Preference(DefaultsKey.notchLiquidGlassEnabled, default: false)
    package static let clamshellPreferred = Preference(DefaultsKey.clamshellPreferred, default: false)
    package static let dimScreenOnLidClose = Preference(DefaultsKey.dimScreenOnLidClose, default: false)
    package static let keepAwakeAutoStart = Preference(DefaultsKey.keepAwakeAutoStart, default: false)
    package static let keepAwakeRightClickToggle = Preference(DefaultsKey.keepAwakeRightClickToggle, default: false)
    package static let keepAwakeAllowDisplaySleep = Preference(DefaultsKey.keepAwakeAllowDisplaySleep, default: false)
    package static let keepAwakeExternalDisplay = Preference(DefaultsKey.keepAwakeExternalDisplay, default: false)
    package static let keepAwakeConnectedToPower = Preference(DefaultsKey.keepAwakeConnectedToPower, default: false)
    package static let keepAwakeRunningApps = Preference(DefaultsKey.keepAwakeRunningApps, default: false)
    package static let keepAwakeAutomationRequireAll = Preference(DefaultsKey.keepAwakeAutomationRequireAll, default: false)
    package static let keepAwakePauseWhenLocked = Preference(DefaultsKey.keepAwakePauseWhenLocked, default: false)
    package static let keepAwakeSwitchUsesUntil = Preference(DefaultsKey.keepAwakeSwitchUsesUntil, default: false)
    package static let keepAwakeMouseJiggleEnabled = Preference(DefaultsKey.keepAwakeMouseJiggleEnabled, default: false)
    package static let hotkeyEnabled = Preference(DefaultsKey.hotkeyEnabled, default: true)
    package static let launchAtLoginWanted = Preference(DefaultsKey.launchAtLoginWanted, default: false)
    package static let showCountdown = Preference(DefaultsKey.showCountdown, default: false)
    package static let scrollInverterEnabled = Preference(DefaultsKey.scrollInverterEnabled, default: false)
    package static let scrollInverterHorizontalEnabled = Preference(DefaultsKey.scrollInverterHorizontalEnabled, default: false)
    package static let scrollHorizontalEnabled = Preference(DefaultsKey.scrollHorizontalEnabled, default: false)
    package static let focusFollowsMouseEnabled = Preference(DefaultsKey.focusFollowsMouseEnabled, default: false)
    package static let linearScrollEnabled = Preference(DefaultsKey.linearScrollEnabled, default: false)
    package static let mouseAccelerationDisabled = Preference(DefaultsKey.mouseAccelerationDisabled, default: false)
    package static let mouseNavigationEnabled = Preference(DefaultsKey.mouseNavigationEnabled, default: false)
    package static let mouseSpacesGestureFollowsDrag = Preference(DefaultsKey.mouseSpacesGestureFollowsDrag, default: false)
    package static let mouseClickDebounceEnabled = Preference(DefaultsKey.mouseClickDebounceEnabled, default: false)
    package static let superKeyEnabled = Preference(DefaultsKey.superKeyEnabled, default: false)
    package static let switcherEnabled = Preference(DefaultsKey.switcherEnabled, default: true)
    package static let switcherTakeOverSystemShortcuts = Preference(DefaultsKey.switcherTakeOverSystemShortcuts, default: false)
    package static let switcherIconRowMode = Preference(DefaultsKey.switcherIconRowMode, default: false)
    package static let switcherSimpleMode = Preference(DefaultsKey.switcherSimpleMode, default: false)
    package static let switcherMergeTabs = Preference(DefaultsKey.switcherMergeTabs, default: false)
    package static let switcherShowWindowlessFinder = Preference(DefaultsKey.switcherShowWindowlessFinder, default: true)
    package static let switcherShowFullscreenWindows = Preference(DefaultsKey.switcherShowFullscreenWindows, default: true)
    package static let switcherCurrentSpaceOnly = Preference(DefaultsKey.switcherCurrentSpaceOnly, default: false)
    package static let switcherSearchPinEnabled = Preference(DefaultsKey.switcherSearchPinEnabled, default: false)
    package static let switcherShowShortcutHints = Preference(DefaultsKey.switcherShowShortcutHints, default: true)
    package static let switcherInstantSelection = Preference(DefaultsKey.switcherInstantSelection, default: false)
    package static let switcherCurrentDisplayOnly = Preference(DefaultsKey.switcherCurrentDisplayOnly, default: false)
    package static let minimalWindowPreviews = Preference(DefaultsKey.minimalWindowPreviews, default: false)
    package static let dockPreviewEnabled = Preference(DefaultsKey.dockPreviewEnabled, default: false)
    package static let dockPreviewCurrentSpaceOnly = Preference(DefaultsKey.dockPreviewCurrentSpaceOnly, default: false)
    package static let dockPreviewKeepDockVisible = Preference(DefaultsKey.dockPreviewKeepDockVisible, default: false)
    package static let dockPreviewQuitAppOnClose = Preference(DefaultsKey.dockPreviewQuitAppOnClose, default: false)
    package static let dockPreviewOrderByCreation = Preference(DefaultsKey.dockPreviewOrderByCreation, default: false)
    package static let dockClickMinimize = Preference(DefaultsKey.dockClickMinimize, default: false)
    package static let dockClickHide = Preference(DefaultsKey.dockClickHide, default: false)
    package static let dockClickCycleWindows = Preference(DefaultsKey.dockClickCycleWindows, default: false)
    package static let spacesOrderEnabled = Preference(DefaultsKey.spacesOrderEnabled, default: false)
    package static let middleClickEnabled = Preference(DefaultsKey.middleClickEnabled, default: false)
    package static let autoCheckUpdates = Preference(DefaultsKey.autoCheckUpdates, default: true)
    package static let releaseNotesOnUpdate = Preference(DefaultsKey.releaseNotesOnUpdate, default: true)
    package static let mixerShowFinder = Preference(DefaultsKey.mixerShowFinder, default: true)
    package static let mixerHideInactiveApps = Preference(DefaultsKey.mixerHideInactiveApps, default: false)
    package static let mixerLowerVolumeOnHeadphonesDisconnect = Preference(DefaultsKey.mixerLowerVolumeOnHeadphonesDisconnect, default: false)
    package static let preciseVolumeRollerEnabled = Preference(DefaultsKey.preciseVolumeRollerEnabled, default: false)
    package static let soundOutputSwitcherEnabled = Preference(DefaultsKey.soundOutputSwitcherEnabled, default: false)
    package static let audioPriorityOutputEnabled = Preference(DefaultsKey.audioPriorityOutputEnabled, default: true)
    package static let audioPriorityInputEnabled = Preference(DefaultsKey.audioPriorityInputEnabled, default: true)
    package static let quitProtectionQuitEnabled = Preference(DefaultsKey.quitProtectionQuitEnabled, default: false)
    package static let quitProtectionQuitShowFeedback = Preference(DefaultsKey.quitProtectionQuitShowFeedback, default: true)
    package static let quitProtectionCloseEnabled = Preference(DefaultsKey.quitProtectionCloseEnabled, default: false)
    package static let quitProtectionCloseShowFeedback = Preference(DefaultsKey.quitProtectionCloseShowFeedback, default: true)
    package static let shelfShortcutEnabled = Preference(DefaultsKey.shelfShortcutEnabled, default: true)
    package static let shelfShakeToOpen = Preference(DefaultsKey.shelfShakeToOpen, default: true)
    package static let shelfDropZoneEnabled = Preference(DefaultsKey.shelfDropZoneEnabled, default: true)
    package static let shelfEdgeDragEnabled = Preference(DefaultsKey.shelfEdgeDragEnabled, default: false)
    package static let shelfCloseAfterDrop = Preference(DefaultsKey.shelfCloseAfterDrop, default: false)
    package static let shelfRemoveAfterDrop = Preference(DefaultsKey.shelfRemoveAfterDrop, default: true)
    package static let shelfShortcutAddsFinderSelection = Preference(DefaultsKey.shelfShortcutAddsFinderSelection, default: false)
    package static let extraBrightnessEnabled = Preference(DefaultsKey.extraBrightnessEnabled, default: false)
    package static let brightnessControlEnabled = Preference(DefaultsKey.brightnessControlEnabled, default: false)
    package static let brightnessKeysEnabled = Preference(DefaultsKey.brightnessKeysEnabled, default: false)
    package static let brightnessOSDEnabled = Preference(DefaultsKey.brightnessOSDEnabled, default: false)
    package static let displayBrightnessShortcutsEnabled = Preference(DefaultsKey.displayBrightnessShortcutsEnabled, default: false)
    package static let keyboardBrightnessShortcutsEnabled = Preference(DefaultsKey.keyboardBrightnessShortcutsEnabled, default: false)
    package static let bluetoothSleepEnabled = Preference(DefaultsKey.bluetoothSleepEnabled, default: false)
    package static let bluetoothSleepRestoreOnWake = Preference(DefaultsKey.bluetoothSleepRestoreOnWake, default: true)
    package static let bluetoothSleepRestorePending = Preference(DefaultsKey.bluetoothSleepRestorePending, default: false)
    package static let musicBlockEnabled = Preference(DefaultsKey.musicBlockEnabled, default: false)
    package static let musicBlockPlayReplacement = Preference(DefaultsKey.musicBlockPlayReplacement, default: true)
    package static let cleanerScheduleNotify = Preference(DefaultsKey.cleanerScheduleNotify, default: true)
    package static let whatsAppDownloadsEnabled = Preference(DefaultsKey.whatsAppDownloadsEnabled, default: false)
    package static let whatsAppDownloadsAutomaticEnabled = Preference(DefaultsKey.whatsAppDownloadsAutomaticEnabled, default: false)
    package static let whatsAppDownloadsNotify = Preference(DefaultsKey.whatsAppDownloadsNotify, default: true)
    package static let whatsAppDownloadsIncludeExisting = Preference(DefaultsKey.whatsAppDownloadsIncludeExisting, default: false)
    package static let whatsAppDownloadsLastCleanupAutomatic = Preference(DefaultsKey.whatsAppDownloadsLastCleanupAutomatic, default: false)
    package static let whatsAppDownloadsAccessConfirmed = Preference(DefaultsKey.whatsAppDownloadsAccessConfirmed, default: false)
    package static let whatsAppOrganizerEnabled = Preference(DefaultsKey.whatsAppOrganizerEnabled, default: false)
    package static let urlCleanerEnabled = Preference(DefaultsKey.urlCleanerEnabled, default: false)
    package static let textSnippetsEnabled = Preference(DefaultsKey.textSnippetsEnabled, default: false)
    package static let snippetLibraryEnabled = Preference(DefaultsKey.snippetLibraryEnabled, default: false)
    package static let snippetSoundEnabled = Preference(DefaultsKey.snippetSoundEnabled, default: false)
    package static let notchShowPlayingMusic = Preference(DefaultsKey.notchShowPlayingMusic, default: true)
    package static let notchIncludeOtherPlayers = Preference(DefaultsKey.notchIncludeOtherPlayers, default: true)
    package static let notchScratchpadControlHidden = Preference(DefaultsKey.notchScratchpadControlHidden, default: false)
    package static let notchKeyboardLightControlHidden = Preference(DefaultsKey.notchKeyboardLightControlHidden, default: false)
    package static let notchOutlineEnabled = Preference(DefaultsKey.notchOutlineEnabled, default: false)
    package static let notchHapticFeedback = Preference(DefaultsKey.notchHapticFeedback, default: true)
    package static let notchTranslucentBackground = Preference(DefaultsKey.notchTranslucentBackground, default: false)
    package static let notchShelf = Preference(DefaultsKey.notchShelf, default: true)
    package static let notchDragReveal = Preference(DefaultsKey.notchDragReveal, default: true)
    package static let notchCaptureControls = Preference(DefaultsKey.notchCaptureControls, default: true)
    package static let notchQuickPanel = Preference(DefaultsKey.notchQuickPanel, default: true)
    package static let notchAppPanel = Preference(DefaultsKey.notchAppPanel, default: false)
    package static let notchKeepAwakeActivity = Preference(DefaultsKey.notchKeepAwakeActivity, default: false)
    package static let notchScratchpad = Preference(DefaultsKey.notchScratchpad, default: true)
    package static let notchHoverExpands = Preference(DefaultsKey.notchHoverExpands, default: true)
    package static let notchGesturesEnabled = Preference(DefaultsKey.notchGesturesEnabled, default: true)
    package static let notchKeyboardLight = Preference(DefaultsKey.notchKeyboardLight, default: true)
    package static let notchNotificationsEnabled = Preference(DefaultsKey.notchNotificationsEnabled, default: true)
    package static let notchDismissNativeNotifications = Preference(DefaultsKey.notchDismissNativeNotifications, default: false)
    package static let notchTimerEnabled = Preference(DefaultsKey.notchTimerEnabled, default: true)
    package static let notchTimerSoundEnabled = Preference(DefaultsKey.notchTimerSoundEnabled, default: true)
    package static let notchHideTimerCountdown = Preference(DefaultsKey.notchHideTimerCountdown, default: false)
    package static let notchCameraEnabled = Preference(DefaultsKey.notchCameraEnabled, default: true)
    package static let notchAccessoriesEnabled = Preference(DefaultsKey.notchAccessoriesEnabled, default: true)
    package static let notchCalendarEnabled = Preference(DefaultsKey.notchCalendarEnabled, default: true)
    package static let notchCalendarCountdown = Preference(DefaultsKey.notchCalendarCountdown, default: false)
    package static let notchCalendarTimeLeft = Preference(DefaultsKey.notchCalendarTimeLeft, default: false)
    package static let notchCalendarWeekNumbers = Preference(DefaultsKey.notchCalendarWeekNumbers, default: false)
    package static let notchAgentsEnabled = Preference(DefaultsKey.notchAgentsEnabled, default: true)
    package static let notchAgentsClaude = Preference(DefaultsKey.notchAgentsClaude, default: true)
    package static let notchAgentsCodex = Preference(DefaultsKey.notchAgentsCodex, default: true)
    package static let notchAgentsOpenCode = Preference(DefaultsKey.notchAgentsOpenCode, default: true)
    package static let notchAgentsCopilot = Preference(DefaultsKey.notchAgentsCopilot, default: true)
    package static let notchAgentsAntigravity = Preference(DefaultsKey.notchAgentsAntigravity, default: true)
    package static let notchAgentsLiveActivity = Preference(DefaultsKey.notchAgentsLiveActivity, default: true)
    package static let notchAgentsFinishAlert = Preference(DefaultsKey.notchAgentsFinishAlert, default: true)
    package static let notchAgentsLimitAlert = Preference(DefaultsKey.notchAgentsLimitAlert, default: true)
    package static let notchAgentsPriceUpdates = Preference(DefaultsKey.notchAgentsPriceUpdates, default: true)
    package static let notchLyricsEnabled = Preference(DefaultsKey.notchLyricsEnabled, default: true)
    package static let notchLyricsOnline = Preference(DefaultsKey.notchLyricsOnline, default: false)
    package static let notchLiveEqualizer = Preference(DefaultsKey.notchLiveEqualizer, default: false)
    package static let notchQueueEnabled = Preference(DefaultsKey.notchQueueEnabled, default: true)
    package static let notchDownloadsEnabled = Preference(DefaultsKey.notchDownloadsEnabled, default: true)
    package static let notchWatchEnabled = Preference(DefaultsKey.notchWatchEnabled, default: true)
    package static let notchWatchSound = Preference(DefaultsKey.notchWatchSound, default: true)
    package static let notchEnabled = Preference(DefaultsKey.notchEnabled, default: false)
    package static let notchOpenOnHover = Preference(DefaultsKey.notchOpenOnHover, default: false)
    package static let notchHideInFullscreen = Preference(DefaultsKey.notchHideInFullscreen, default: false)
    package static let notchHideUntilHover = Preference(DefaultsKey.notchHideUntilHover, default: false)
    package static let notchCoversMenus = Preference(DefaultsKey.notchCoversMenus, default: true)
    package static let notchReturnHome = Preference(DefaultsKey.notchReturnHome, default: false)
    package static let notchOpensActivity = Preference(DefaultsKey.notchOpensActivity, default: true)
    package static let notchVolume = Preference(DefaultsKey.notchVolume, default: true)
    package static let notchMicrophone = Preference(DefaultsKey.notchMicrophone, default: true)
    package static let notchBrightness = Preference(DefaultsKey.notchBrightness, default: true)
    package static let notchBattery = Preference(DefaultsKey.notchBattery, default: true)
    package static let notchClipboard = Preference(DefaultsKey.notchClipboard, default: true)
    package static let notchClipboardWindow = Preference(DefaultsKey.notchClipboardWindow, default: true)
    package static let notchCapture = Preference(DefaultsKey.notchCapture, default: true)
    package static let notchTrackChange = Preference(DefaultsKey.notchTrackChange, default: true)
    package static let notchMusicActivity = Preference(DefaultsKey.notchMusicActivity, default: false)
    package static let notchShowInCaptures = Preference(DefaultsKey.notchShowInCaptures, default: true)
    package static let notchLockScreen = Preference(DefaultsKey.notchLockScreen, default: false)
    package static let notchLockSounds = Preference(DefaultsKey.notchLockSounds, default: false)
    package static let notchMascotEnabled = Preference(DefaultsKey.notchMascotEnabled, default: false)
    package static let notchMascotVisits = Preference(DefaultsKey.notchMascotVisits, default: true)
    package static let notchMascotReactions = Preference(DefaultsKey.notchMascotReactions, default: true)
    package static let notchCommandBar = Preference(DefaultsKey.notchCommandBar, default: true)
    package static let notchHideInCaptures = Preference(DefaultsKey.notchHideInCaptures, default: false)
    package static let panelControlNotch = Preference(DefaultsKey.panelControlNotch, default: true)
    package static let radialMenuEnabled = Preference(DefaultsKey.radialMenuEnabled, default: false)
    package static let radialMenuAtPointer = Preference(DefaultsKey.radialMenuAtPointer, default: true)
    package static let windowMaximizeEnabled = Preference(DefaultsKey.windowMaximizeEnabled, default: false)
    package static let keyboardDebounceEnabled = Preference(DefaultsKey.keyboardDebounceEnabled, default: false)
    package static let panelUtilityCleaning = Preference(DefaultsKey.panelUtilityCleaning, default: true)
    package static let cleaningModeKeepScreenVisible = Preference(DefaultsKey.cleaningModeKeepScreenVisible, default: false)
    package static let panelUtilityURLCleaner = Preference(DefaultsKey.panelUtilityURLCleaner, default: true)
    package static let panelUtilityUninstaller = Preference(DefaultsKey.panelUtilityUninstaller, default: true)
    package static let uninstallerCommandBarEnabled = Preference(DefaultsKey.uninstallerCommandBarEnabled, default: false)
    package static let killProcessCommandBarEnabled = Preference(DefaultsKey.killProcessCommandBarEnabled, default: true)
    package static let killProcessGroupRelated = Preference(DefaultsKey.killProcessGroupRelated, default: true)
    package static let killProcessSortAscending = Preference(DefaultsKey.killProcessSortAscending, default: false)
    package static let panelUtilityCleaner = Preference(DefaultsKey.panelUtilityCleaner, default: true)
    package static let panelUtilityHomebrew = Preference(DefaultsKey.panelUtilityHomebrew, default: true)
    package static let homebrewGroupDependencies = Preference(DefaultsKey.homebrewGroupDependencies, default: true)
    package static let panelUtilityAppUpdates = Preference(DefaultsKey.panelUtilityAppUpdates, default: true)
    package static let appUpdatesIncludeHomebrewApps = Preference(DefaultsKey.appUpdatesIncludeHomebrewApps, default: true)
    package static let appUpdatesIncludeAppStore = Preference(DefaultsKey.appUpdatesIncludeAppStore, default: true)
    package static let appUpdatesIncludeOnlineCatalog = Preference(DefaultsKey.appUpdatesIncludeOnlineCatalog, default: true)
    package static let appUpdatesNotify = Preference(DefaultsKey.appUpdatesNotify, default: true)
    package static let panelUtilityMedia = Preference(DefaultsKey.panelUtilityMedia, default: true)
    package static let panelUtilityClipboard = Preference(DefaultsKey.panelUtilityClipboard, default: true)
    package static let panelUtilityWindowLayout = Preference(DefaultsKey.panelUtilityWindowLayout, default: true)
    package static let panelControlMouseScroll = Preference(DefaultsKey.panelControlMouseScroll, default: true)
    package static let panelControlFocusFollowsMouse = Preference(DefaultsKey.panelControlFocusFollowsMouse, default: true)
    package static let panelControlMouseNavigation = Preference(DefaultsKey.panelControlMouseNavigation, default: true)
    package static let panelControlSwitcher = Preference(DefaultsKey.panelControlSwitcher, default: true)
    package static let panelControlDockPreview = Preference(DefaultsKey.panelControlDockPreview, default: true)
    package static let panelControlCutPaste = Preference(DefaultsKey.panelControlCutPaste, default: true)
    package static let panelControlAutoQuit = Preference(DefaultsKey.panelControlAutoQuit, default: true)
    package static let panelControlShelf = Preference(DefaultsKey.panelControlShelf, default: true)
    package static let panelControlWindowMaximize = Preference(DefaultsKey.panelControlWindowMaximize, default: true)
    package static let panelControlKeyDebounce = Preference(DefaultsKey.panelControlKeyDebounce, default: true)
    package static let panelControlDockClick = Preference(DefaultsKey.panelControlDockClick, default: true)
    package static let panelControlDockClickHide = Preference(DefaultsKey.panelControlDockClickHide, default: true)
    package static let panelControlDockClickCycle = Preference(DefaultsKey.panelControlDockClickCycle, default: true)
    package static let panelControlMiddleClick = Preference(DefaultsKey.panelControlMiddleClick, default: true)
    package static let panelControlTextSnippets = Preference(DefaultsKey.panelControlTextSnippets, default: true)
    package static let panelControlSuperKey = Preference(DefaultsKey.panelControlSuperKey, default: true)
    package static let panelControlRadialMenu = Preference(DefaultsKey.panelControlRadialMenu, default: true)
    package static let panelControlMouseButtonShortcuts = Preference(DefaultsKey.panelControlMouseButtonShortcuts, default: true)
    package static let panelControlMouseAcceleration = Preference(DefaultsKey.panelControlMouseAcceleration, default: true)
    package static let panelControlLinearScroll = Preference(DefaultsKey.panelControlLinearScroll, default: true)
    package static let panelControlMouseClickDebounce = Preference(DefaultsKey.panelControlMouseClickDebounce, default: true)
    package static let panelControlSpacesOrder = Preference(DefaultsKey.panelControlSpacesOrder, default: true)
    package static let panelControlWindowsExpanded = Preference(DefaultsKey.panelControlWindowsExpanded, default: false)
    package static let panelControlInputExpanded = Preference(DefaultsKey.panelControlInputExpanded, default: false)
    package static let panelControlFilesExpanded = Preference(DefaultsKey.panelControlFilesExpanded, default: false)
    package static let panelShowKeepAwake = Preference(DefaultsKey.panelShowKeepAwake, default: true)
    package static let panelShowBrightness = Preference(DefaultsKey.panelShowBrightness, default: true)
    package static let panelShowUtilities = Preference(DefaultsKey.panelShowUtilities, default: true)
    package static let panelShowControls = Preference(DefaultsKey.panelShowControls, default: true)
    package static let panelShowToggles = Preference(DefaultsKey.panelShowToggles, default: true)
    package static let panelShowWallpaper = Preference(DefaultsKey.panelShowWallpaper, default: true)
    package static let panelToggleDarkMode = Preference(DefaultsKey.panelToggleDarkMode, default: true)
    package static let panelToggleKeyboardLight = Preference(DefaultsKey.panelToggleKeyboardLight, default: true)
    package static let panelToggleMicMute = Preference(DefaultsKey.panelToggleMicMute, default: true)
    package static let panelToggleEmptyTrash = Preference(DefaultsKey.panelToggleEmptyTrash, default: true)
    package static let panelToggleEjectDisks = Preference(DefaultsKey.panelToggleEjectDisks, default: true)
    package static let panelToggleHiddenFiles = Preference(DefaultsKey.panelToggleHiddenFiles, default: true)
    package static let panelToggleDesktopIcons = Preference(DefaultsKey.panelToggleDesktopIcons, default: true)
    package static let panelToggleLockScreen = Preference(DefaultsKey.panelToggleLockScreen, default: true)
    package static let panelToggleDisplayOff = Preference(DefaultsKey.panelToggleDisplayOff, default: true)
    package static let panelToggleScreenSaver = Preference(DefaultsKey.panelToggleScreenSaver, default: true)
    package static let menuBarCPUTemperature = Preference(DefaultsKey.menuBarCPUTemperature, default: false)
    package static let menuBarGPUTemperature = Preference(DefaultsKey.menuBarGPUTemperature, default: false)
    package static let menuBarBatteryTemperature = Preference(DefaultsKey.menuBarBatteryTemperature, default: false)
    package static let menuBarBatteryTime = Preference(DefaultsKey.menuBarBatteryTime, default: false)
    package static let menuBarDiskUsage = Preference(DefaultsKey.menuBarDiskUsage, default: false)
    package static let menuBarDiskActivity = Preference(DefaultsKey.menuBarDiskActivity, default: false)
    package static let menuBarPeripheralBattery = Preference(DefaultsKey.menuBarPeripheralBattery, default: false)
    package static let menuBarConnectedDevices = Preference(DefaultsKey.menuBarConnectedDevices, default: false)
    package static let menuBarFanSpeed = Preference(DefaultsKey.menuBarFanSpeed, default: false)
    package static let menuBarCombineTemperatures = Preference(DefaultsKey.menuBarCombineTemperatures, default: true)
    package static let menuBarSeparateMetrics = Preference(DefaultsKey.menuBarSeparateMetrics, default: false)
    package static let menuBarNetworkUploadFirst = Preference(DefaultsKey.menuBarNetworkUploadFirst, default: false)
    package static let monitorShowSystem = Preference(DefaultsKey.monitorShowSystem, default: true)
    package static let monitorShowNetwork = Preference(DefaultsKey.monitorShowNetwork, default: true)
    package static let monitorShowDisk = Preference(DefaultsKey.monitorShowDisk, default: true)
    package static let monitorShowPower = Preference(DefaultsKey.monitorShowPower, default: true)
    package static let monitorShowMixer = Preference(DefaultsKey.monitorShowMixer, default: true)
    package static let panelShowFanControl = Preference(DefaultsKey.panelShowFanControl, default: true)
    package static let fanControlResume = Preference(DefaultsKey.fanControlResume, default: false)
    package static let fanControlRecoveryNeeded = Preference(DefaultsKey.fanControlRecoveryNeeded, default: false)
    package static let panelNavigationEnabled = Preference(DefaultsKey.panelNavigationEnabled, default: true)
    package static let monitorGraphCPU = Preference(DefaultsKey.monitorGraphCPU, default: true)
    package static let monitorGraphGPU = Preference(DefaultsKey.monitorGraphGPU, default: true)
    package static let monitorGraphMemory = Preference(DefaultsKey.monitorGraphMemory, default: true)
    package static let monitorGraphNetwork = Preference(DefaultsKey.monitorGraphNetwork, default: true)
    package static let monitorGraphDisk = Preference(DefaultsKey.monitorGraphDisk, default: true)
    package static let monitorGraphPower = Preference(DefaultsKey.monitorGraphPower, default: true)
    package static let monitorGraphBattery = Preference(DefaultsKey.monitorGraphBattery, default: true)
    package static let monitorGraphScale = Preference(DefaultsKey.monitorGraphScale, default: true)
    package static let monitorSysTemps = Preference(DefaultsKey.monitorSysTemps, default: true)
    package static let monitorSysCPU = Preference(DefaultsKey.monitorSysCPU, default: true)
    package static let monitorSysGPU = Preference(DefaultsKey.monitorSysGPU, default: true)
    package static let monitorSysBattery = Preference(DefaultsKey.monitorSysBattery, default: true)
    package static let monitorSysMemory = Preference(DefaultsKey.monitorSysMemory, default: true)
    package static let monitorSysAlerts = Preference(DefaultsKey.monitorSysAlerts, default: true)
    package static let monitorSysUptime = Preference(DefaultsKey.monitorSysUptime, default: true)
    package static let monitorSysConnectedDevices = Preference(DefaultsKey.monitorSysConnectedDevices, default: true)
    package static let monitorNetSpeed = Preference(DefaultsKey.monitorNetSpeed, default: true)
    package static let monitorNetApps = Preference(DefaultsKey.monitorNetApps, default: true)
    package static let monitorNetTotals = Preference(DefaultsKey.monitorNetTotals, default: true)
    package static let monitorNetAddresses = Preference(DefaultsKey.monitorNetAddresses, default: true)
    package static let monitorNetTest = Preference(DefaultsKey.monitorNetTest, default: true)
    package static let monitorDiskUsage = Preference(DefaultsKey.monitorDiskUsage, default: true)
    package static let monitorDiskActivity = Preference(DefaultsKey.monitorDiskActivity, default: true)
    package static let monitorDiskSMART = Preference(DefaultsKey.monitorDiskSMART, default: true)
    package static let monitorDiskProtection = Preference(DefaultsKey.monitorDiskProtection, default: true)
    package static let monitorDiskTools = Preference(DefaultsKey.monitorDiskTools, default: true)
    package static let monitorPwrTemperature = Preference(DefaultsKey.monitorPwrTemperature, default: true)
    package static let monitorPwrSystem = Preference(DefaultsKey.monitorPwrSystem, default: true)
    package static let monitorPwrAdapter = Preference(DefaultsKey.monitorPwrAdapter, default: true)
    package static let monitorPwrBattery = Preference(DefaultsKey.monitorPwrBattery, default: true)
    package static let monitorPwrTimeRemaining = Preference(DefaultsKey.monitorPwrTimeRemaining, default: true)
    package static let monitorPwrHealth = Preference(DefaultsKey.monitorPwrHealth, default: true)
    package static let monitorAlertCPU = Preference(DefaultsKey.monitorAlertCPU, default: false)
    package static let monitorAlertCPUTemperature = Preference(DefaultsKey.monitorAlertCPUTemperature, default: false)
    package static let monitorAlertBatteryTemperature = Preference(DefaultsKey.monitorAlertBatteryTemperature, default: false)
    package static let monitorAlertMemory = Preference(DefaultsKey.monitorAlertMemory, default: false)
    package static let monitorAlertDisk = Preference(DefaultsKey.monitorAlertDisk, default: false)
    package static let monitorAlertBattery = Preference(DefaultsKey.monitorAlertBattery, default: false)
    package static let mediaVideoKeepAudio = Preference(DefaultsKey.mediaVideoKeepAudio, default: true)
    package static let mediaGIFLoops = Preference(DefaultsKey.mediaGIFLoops, default: true)
    package static let mediaImageStripMetadata = Preference(DefaultsKey.mediaImageStripMetadata, default: true)
    package static let mediaImagePreserveModificationDate = Preference(DefaultsKey.mediaImagePreserveModificationDate, default: false)
    package static let mediaImageSaveInSubfolder = Preference(DefaultsKey.mediaImageSaveInSubfolder, default: false)
    package static let mediaTextAccurate = Preference(DefaultsKey.mediaTextAccurate, default: true)
    package static let mediaTextLanguageCorrection = Preference(DefaultsKey.mediaTextLanguageCorrection, default: true)
    package static let clipboardHistorySkipSensitive = Preference(DefaultsKey.clipboardHistorySkipSensitive, default: true)
    package static let clipboardHistoryIncludeImagesFiles = Preference(DefaultsKey.clipboardHistoryIncludeImagesFiles, default: true)
    package static let clipboardHistoryQuickPreview = Preference(DefaultsKey.clipboardHistoryQuickPreview, default: false)
    package static let clipboardHistoryMenuBarPreview = Preference(DefaultsKey.clipboardHistoryMenuBarPreview, default: false)
    package static let clipboardAutoClearOnDelay = Preference(DefaultsKey.clipboardAutoClearOnDelay, default: false)
    package static let clipboardAutoClearOnSleep = Preference(DefaultsKey.clipboardAutoClearOnSleep, default: false)
    package static let clipboardAutoClearOnDisplaySleep = Preference(DefaultsKey.clipboardAutoClearOnDisplaySleep, default: false)
    package static let clipboardAutoClearOnScreenLock = Preference(DefaultsKey.clipboardAutoClearOnScreenLock, default: false)
    package static let finderCutPasteShowHUD = Preference(DefaultsKey.finderCutPasteShowHUD, default: true)
    package static let finderPasteImageAsFile = Preference(DefaultsKey.finderPasteImageAsFile, default: false)
    package static let pastePlainEnabled = Preference(DefaultsKey.pastePlainEnabled, default: false)
    package static let finderRenameEnabled = Preference(DefaultsKey.finderRenameEnabled, default: false)
    package static let diskImageInstallerUseUserApplications = Preference(DefaultsKey.diskImageInstallerUseUserApplications, default: false)
    package static let diskImageInstallerTrashesDownload = Preference(DefaultsKey.diskImageInstallerTrashesDownload, default: true)
    package static let diskImageInstallerRevealsApp = Preference(DefaultsKey.diskImageInstallerRevealsApp, default: false)
    package static let colorPickerShortcutEnabled = Preference(DefaultsKey.colorPickerShortcutEnabled, default: false)
    package static let colorPickerBareHex = Preference(DefaultsKey.colorPickerBareHex, default: false)
    package static let screenOCRShortcutEnabled = Preference(DefaultsKey.screenOCRShortcutEnabled, default: false)
    package static let screenOCRRemoveLineBreaks = Preference(DefaultsKey.screenOCRRemoveLineBreaks, default: false)
    package static let screenOCRDetectQRCodes = Preference(DefaultsKey.screenOCRDetectQRCodes, default: true)
    package static let micMuteShortcutEnabled = Preference(DefaultsKey.micMuteShortcutEnabled, default: false)
    package static let cameraPreviewShortcutEnabled = Preference(DefaultsKey.cameraPreviewShortcutEnabled, default: false)
    package static let wallpaperApplyAllDisplays = Preference(DefaultsKey.wallpaperApplyAllDisplays, default: true)
    package static let scratchpadShortcutEnabled = Preference(DefaultsKey.scratchpadShortcutEnabled, default: false)
    package static let commandBarShortcutEnabled = Preference(DefaultsKey.commandBarShortcutEnabled, default: false)
    package static let commandBarCompactMode = Preference(DefaultsKey.commandBarCompactMode, default: false)
    package static let panelUtilityCommandBar = Preference(DefaultsKey.panelUtilityCommandBar, default: true)
    package static let scratchpadCloseOnClickOutside = Preference(DefaultsKey.scratchpadCloseOnClickOutside, default: true)
    package static let micMuteActive = Preference(DefaultsKey.micMuteActive, default: false)
    package static let quickLauncherShortcutEnabled = Preference(DefaultsKey.quickLauncherShortcutEnabled, default: true)
    package static let panelUtilityQuickLauncher = Preference(DefaultsKey.panelUtilityQuickLauncher, default: true)
    package static let panelUtilityColorPicker = Preference(DefaultsKey.panelUtilityColorPicker, default: true)
    package static let panelUtilityScreenOCR = Preference(DefaultsKey.panelUtilityScreenOCR, default: true)
    package static let panelUtilityCameraPreview = Preference(DefaultsKey.panelUtilityCameraPreview, default: true)
    package static let panelUtilityScratchpad = Preference(DefaultsKey.panelUtilityScratchpad, default: true)
    package static let clipboardHistoryShortcutEnabled = Preference(DefaultsKey.clipboardHistoryShortcutEnabled, default: true)
    package static let recorderShortcutEnabled = Preference(DefaultsKey.recorderShortcutEnabled, default: false)
    package static let recorderSystemAudio = Preference(DefaultsKey.recorderSystemAudio, default: true)
    package static let recorderMicrophone = Preference(DefaultsKey.recorderMicrophone, default: false)
    package static let recorderOpenEditor = Preference(DefaultsKey.recorderOpenEditor, default: true)
    package static let recorderAutomaticZoom = Preference(DefaultsKey.recorderAutomaticZoom, default: true)
    package static let recorderSharingEnabled = Preference(DefaultsKey.recorderSharingEnabled, default: true)
    package static let panelUtilityScreenRecorder = Preference(DefaultsKey.panelUtilityScreenRecorder, default: true)
    package static let panelUtilityPortManager = Preference(DefaultsKey.panelUtilityPortManager, default: true)
    package static let nexusAgentShortcutEnabled = Preference(DefaultsKey.nexusAgentShortcutEnabled, default: false)
    package static let nexusAgentAutoStart = Preference(DefaultsKey.nexusAgentAutoStart, default: false)
    package static let nexusAgentPlanMode = Preference(DefaultsKey.nexusAgentPlanMode, default: false)
    /// Empty means the bot's standard home, `~/.config/nexus-agent`.
    package static let nexusAgentBotDirectory = Preference(DefaultsKey.nexusAgentBotDirectory, default: "")
    package static let panelUtilityNexusAgent = Preference(DefaultsKey.panelUtilityNexusAgent, default: true)
    package static let screenshotShowCaptureMenuOnShortcut = Preference(DefaultsKey.screenshotShowCaptureMenuOnShortcut, default: true)
    package static let recorderShowCaptureMenuOnShortcut = Preference(DefaultsKey.recorderShowCaptureMenuOnShortcut, default: true)
    package static let screenOCRShowCaptureMenuOnShortcut = Preference(DefaultsKey.screenOCRShowCaptureMenuOnShortcut, default: true)
    package static let colorPickerShowCaptureMenuOnShortcut = Preference(DefaultsKey.colorPickerShowCaptureMenuOnShortcut, default: true)
    package static let screenshotShortcutEnabled = Preference(DefaultsKey.screenshotShortcutEnabled, default: false)
    package static let unifiedScreenCaptureShortcutMigrated = Preference(DefaultsKey.unifiedScreenCaptureShortcutMigrated, default: false)
    package static let restoredScreenCaptureShortcutsMigrated = Preference(DefaultsKey.restoredScreenCaptureShortcutsMigrated, default: false)
    package static let screenshotFullScreenShortcutEnabled = Preference(DefaultsKey.screenshotFullScreenShortcutEnabled, default: false)
    package static let screenshotLastCaptureShortcutEnabled = Preference(DefaultsKey.screenshotLastCaptureShortcutEnabled, default: false)
    package static let recentCapturesShortcutEnabled = Preference(DefaultsKey.recentCapturesShortcutEnabled, default: false)
    package static let screenshotClipboardShortcutEnabled = Preference(DefaultsKey.screenshotClipboardShortcutEnabled, default: false)
    package static let screenshotFreeze = Preference(DefaultsKey.screenshotFreeze, default: true)
    package static let screenshotHideVitruvianWindows = Preference(DefaultsKey.screenshotHideVitruvianWindows, default: true)
    package static let screenshotIncludePointer = Preference(DefaultsKey.screenshotIncludePointer, default: false)
    package static let screenshotShowLastRegion = Preference(DefaultsKey.screenshotShowLastRegion, default: true)
    package static let screenshotLoupeStartsOn = Preference(DefaultsKey.screenshotLoupeStartsOn, default: false)
    package static let screenshotLoupeRememberZoom = Preference(DefaultsKey.screenshotLoupeRememberZoom, default: false)
    package static let screenshotLoupeSteppedZoomByDefault = Preference(DefaultsKey.screenshotLoupeSteppedZoomByDefault, default: false)
    package static let screenshotDownscale = Preference(DefaultsKey.screenshotDownscale, default: false)
    package static let screenshotAnnotationShadows = Preference(DefaultsKey.screenshotAnnotationShadows, default: false)
    package static let screenshotToolShortcutsEnabled = Preference(DefaultsKey.screenshotToolShortcutsEnabled, default: true)
    package static let screenshotOpenEditorDirectly = Preference(DefaultsKey.screenshotOpenEditorDirectly, default: false)
    package static let screenshotCopyToClipboard = Preference(DefaultsKey.screenshotCopyToClipboard, default: false)
    package static let screenshotPreviewTakesFocus = Preference(DefaultsKey.screenshotPreviewTakesFocus, default: true)
    package static let screenshotUploadShortcutEnabled = Preference(DefaultsKey.screenshotUploadShortcutEnabled, default: false)
    package static let screenshotPreviewEnabled = Preference(DefaultsKey.screenshotPreviewEnabled, default: true)
    package static let screenshotSharingEnabled = Preference(DefaultsKey.screenshotSharingEnabled, default: true)
    package static let panelUtilityScreenshot = Preference(DefaultsKey.panelUtilityScreenshot, default: true)
    package static let windowDirectionalEnabled = Preference(DefaultsKey.windowDirectionalEnabled, default: false)
    package static let pointerDisplayEnabled = Preference(DefaultsKey.pointerDisplayEnabled, default: false)
    package static let windowEdgeSnapEnabled = Preference(DefaultsKey.windowEdgeSnapEnabled, default: false)
    package static let windowGestureEnabled = Preference(DefaultsKey.windowGestureEnabled, default: false)
    package static let windowGestureRaiseWindow = Preference(DefaultsKey.windowGestureRaiseWindow, default: false)
    package static let smoothScrollEnabled = Preference(DefaultsKey.smoothScrollEnabled, default: false)
    package static let mouseButtonShortcutsEnabled = Preference(DefaultsKey.mouseButtonShortcutsEnabled, default: false)
    package static let mouseSpacesGestureEnabled = Preference(DefaultsKey.mouseSpacesGestureEnabled, default: false)
    package static let switcherTreatHiddenAppsLikeMinimized = Preference(
        DefaultsKey.switcherTreatHiddenAppsLikeMinimized, default: true)
    package static let includeBetaUpdates = Preference(DefaultsKey.includeBetaUpdates, default: false)
    package static let shelfClearOnClose = Preference(DefaultsKey.shelfClearOnClose, default: false)
    package static let notchHidesMenuBarIcon = Preference(DefaultsKey.notchHidesMenuBarIcon, default: false)
    package static let menuBarHideIconWithMetrics = Preference(DefaultsKey.menuBarHideIconWithMetrics, default: false)
    package static let windowLayoutSideRepeatCyclesThirds = Preference(
        DefaultsKey.windowLayoutSideRepeatCyclesThirds, default: false)
    package static let clipboardHistoryEnabled = Preference(DefaultsKey.clipboardHistoryEnabled, default: false)
    package static let commandBarASCIILayoutEnabled = Preference(
        DefaultsKey.commandBarASCIILayoutEnabled, default: false)

    // MARK: Numbers

    package static let defaultDuration = Preference(DefaultsKey.defaultDuration, default: 0)
    package static let batteryLimit = Preference(DefaultsKey.batteryLimit, default: 10)
    package static let keepAwakeMouseJiggleInterval = Preference(DefaultsKey.keepAwakeMouseJiggleInterval, default: 5)
    package static let mouseSpacesGestureButton = Preference(DefaultsKey.mouseSpacesGestureButton, default: 0)
    package static let middleClickTapFingers = Preference(DefaultsKey.middleClickTapFingers, default: 0)
    package static let extraBrightnessLevel = Preference(DefaultsKey.extraBrightnessLevel, default: 100)
    package static let cleanerScheduleHour = Preference(DefaultsKey.cleanerScheduleHour, default: 9)
    package static let cleanerScheduleMinute = Preference(DefaultsKey.cleanerScheduleMinute, default: 0)
    package static let cleanerScheduleWeekday = Preference(DefaultsKey.cleanerScheduleWeekday, default: 2)
    package static let cleanerLastAutoFreed = Preference(DefaultsKey.cleanerLastAutoFreed, default: 0)
    package static let cleanerLastAutoFailed = Preference(DefaultsKey.cleanerLastAutoFailed, default: 0)
    package static let whatsAppDownloadsRetentionDays = Preference(DefaultsKey.whatsAppDownloadsRetentionDays, default: 7)
    package static let whatsAppDownloadsLastCleanupCount = Preference(DefaultsKey.whatsAppDownloadsLastCleanupCount, default: 0)
    package static let whatsAppDownloadsLastCleanupBytes = Preference(DefaultsKey.whatsAppDownloadsLastCleanupBytes, default: 0)
    package static let whatsAppDownloadsLastCleanupFailed = Preference(DefaultsKey.whatsAppDownloadsLastCleanupFailed, default: 0)
    package static let whatsAppOrganizerDelayMinutes = Preference(DefaultsKey.whatsAppOrganizerDelayMinutes, default: 5)
    package static let whatsAppOrganizerLastMoved = Preference(DefaultsKey.whatsAppOrganizerLastMoved, default: 0)
    package static let whatsAppOrganizerLastDuplicates = Preference(DefaultsKey.whatsAppOrganizerLastDuplicates, default: 0)
    package static let whatsAppOrganizerLastFailed = Preference(DefaultsKey.whatsAppOrganizerLastFailed, default: 0)
    package static let notchTimerMinutes = Preference(DefaultsKey.notchTimerMinutes, default: 15)
    package static let notchPomodoroFocusMinutes = Preference(DefaultsKey.notchPomodoroFocusMinutes, default: 25)
    package static let notchPomodoroShortBreakMinutes = Preference(DefaultsKey.notchPomodoroShortBreakMinutes, default: 5)
    package static let notchPomodoroLongBreakMinutes = Preference(DefaultsKey.notchPomodoroLongBreakMinutes, default: 15)
    package static let notchPomodoroLongBreakInterval = Preference(DefaultsKey.notchPomodoroLongBreakInterval, default: 4)
    package static let notchPomodoroTotalSessions = Preference(DefaultsKey.notchPomodoroTotalSessions, default: 4)
    package static let appUpdatesLastCount = Preference(DefaultsKey.appUpdatesLastCount, default: 0)
    package static let monitorInterval = Preference(DefaultsKey.monitorInterval, default: 2)
    package static let windowLayoutWindowGap = Preference(DefaultsKey.windowLayoutWindowGap, default: 0)
    package static let windowLayoutScreenGap = Preference(DefaultsKey.windowLayoutScreenGap, default: 0)
    package static let windowLayoutMarginPercent = Preference(DefaultsKey.windowLayoutMarginPercent,
                                                              default: WindowLayoutMargin.defaultPercent)
    package static let monitorAlertCPUThreshold = Preference(DefaultsKey.monitorAlertCPUThreshold, default: 90)
    package static let monitorAlertCPUTemperatureThreshold = Preference(DefaultsKey.monitorAlertCPUTemperatureThreshold, default: 90)
    package static let monitorAlertBatteryTemperatureThreshold = Preference(DefaultsKey.monitorAlertBatteryTemperatureThreshold, default: 40)
    package static let monitorAlertDiskFreePercent = Preference(DefaultsKey.monitorAlertDiskFreePercent, default: 10)
    package static let monitorAlertBatteryPercent = Preference(DefaultsKey.monitorAlertBatteryPercent, default: 15)
    package static let monitorAlertCooldownMinutes = Preference(DefaultsKey.monitorAlertCooldownMinutes, default: 15)
    package static let mediaVideoMaxDimension = Preference(DefaultsKey.mediaVideoMaxDimension, default: 1280)
    package static let mediaVideoTargetMegabytes = Preference(DefaultsKey.mediaVideoTargetMegabytes, default: 20)
    package static let mediaGIFWidth = Preference(DefaultsKey.mediaGIFWidth, default: 720)
    package static let mediaGIFTargetMegabytes = Preference(DefaultsKey.mediaGIFTargetMegabytes, default: 10)
    package static let mediaImageMaxDimension = Preference(DefaultsKey.mediaImageMaxDimension, default: 1600)
    package static let mediaImageResizeWidth = Preference(DefaultsKey.mediaImageResizeWidth, default: 1600)
    package static let mediaImageResizeHeight = Preference(DefaultsKey.mediaImageResizeHeight, default: 1200)
    package static let mediaImageWatermarkMargin = Preference(DefaultsKey.mediaImageWatermarkMargin, default: 32)
    package static let clipboardHistoryLimit = Preference(DefaultsKey.clipboardHistoryLimit, default: 50)
    package static let recorderCountdown = Preference(DefaultsKey.recorderCountdown, default: 3)
    package static let recorderFrameRate = Preference(DefaultsKey.recorderFrameRate, default: 60)
    package static let recorderGIFFrameRate = Preference(DefaultsKey.recorderGIFFrameRate, default: 12)
    package static let screenshotFileNumberStart = Preference(DefaultsKey.screenshotFileNumberStart, default: 1)
    package static let screenshotFileNumberNext = Preference(DefaultsKey.screenshotFileNumberNext, default: 1)
    package static let screenshotDelay = Preference(DefaultsKey.screenshotDelay, default: 0)

    // MARK: Fractions

    package static let keepAwakeUntilTime = Preference(DefaultsKey.keepAwakeUntilTime, default: 0.0)
    package static let dockPreviewBackgroundOpacity = Preference(DefaultsKey.dockPreviewBackgroundOpacity, default: 1.0)
    package static let cleanerLastAutoRun = Preference(DefaultsKey.cleanerLastAutoRun, default: 0.0)
    package static let whatsAppDownloadsAutomaticStartDate = Preference(DefaultsKey.whatsAppDownloadsAutomaticStartDate, default: 0.0)
    package static let whatsAppDownloadsLastAutoRun = Preference(DefaultsKey.whatsAppDownloadsLastAutoRun, default: 0.0)
    package static let whatsAppDownloadsLastCleanup = Preference(DefaultsKey.whatsAppDownloadsLastCleanup, default: 0.0)
    package static let whatsAppOrganizerLastRun = Preference(DefaultsKey.whatsAppOrganizerLastRun, default: 0.0)
    package static let notchCameraFitWidth = Preference(DefaultsKey.notchCameraFitWidth, default: 0.0)
    package static let notchCameraFitHeight = Preference(DefaultsKey.notchCameraFitHeight, default: 0.0)
    package static let notchAgentsDailyBudget = Preference(DefaultsKey.notchAgentsDailyBudget, default: 0.0)
    package static let notchCapsuleFitWidth = Preference(DefaultsKey.notchCapsuleFitWidth, default: 0.0)
    package static let notchCapsuleFitHeight = Preference(DefaultsKey.notchCapsuleFitHeight, default: 0.0)
    package static let notchCapsuleFitDrop = Preference(DefaultsKey.notchCapsuleFitDrop, default: 0.0)
    package static let appUpdatesLastCheck = Preference(DefaultsKey.appUpdatesLastCheck, default: 0.0)
    package static let mediaVideoStart = Preference(DefaultsKey.mediaVideoStart, default: 0.0)
    package static let mediaVideoEnd = Preference(DefaultsKey.mediaVideoEnd, default: 0.0)
    package static let mediaVideoQuality = Preference(DefaultsKey.mediaVideoQuality, default: 0.68)
    package static let mediaVideoFPS = Preference(DefaultsKey.mediaVideoFPS, default: 30.0)
    package static let mediaGIFStart = Preference(DefaultsKey.mediaGIFStart, default: 0.0)
    package static let mediaGIFEnd = Preference(DefaultsKey.mediaGIFEnd, default: 0.0)
    package static let mediaGIFQuality = Preference(DefaultsKey.mediaGIFQuality, default: 0.74)
    package static let mediaGIFFPS = Preference(DefaultsKey.mediaGIFFPS, default: 12.0)
    package static let mediaImageQuality = Preference(DefaultsKey.mediaImageQuality, default: 0.72)
    package static let mediaImageWatermarkOpacity = Preference(DefaultsKey.mediaImageWatermarkOpacity, default: 0.45)
    package static let mediaImageWatermarkScale = Preference(DefaultsKey.mediaImageWatermarkScale, default: 0.18)
    package static let scratchpadBackgroundOpacity = Preference(DefaultsKey.scratchpadBackgroundOpacity, default: 0.0)
    package static let micMuteSavedVolume = Preference(DefaultsKey.micMuteSavedVolume, default: 0.75)
    package static let screenshotLoupeDefaultZoom = Preference(DefaultsKey.screenshotLoupeDefaultZoom, default: 1.0)
    package static let screenshotLoupeLastZoom = Preference(DefaultsKey.screenshotLoupeLastZoom, default: 1.0)

    // MARK: Text

    package static let keepAwakeShortcut = Preference(DefaultsKey.keepAwakeShortcut, default: "control+option+command:40")
    package static let updateShowcaseIntroVersion = Preference(DefaultsKey.updateShowcaseIntroVersion, default: "")
    package static let updateShowcaseMediaOverride = Preference(DefaultsKey.updateShowcaseMediaOverride, default: "")
    package static let mixerAppArrangement = Preference(DefaultsKey.mixerAppArrangement, default: "")
    package static let shelfShortcut = Preference(DefaultsKey.shelfShortcut, default: "control+option+command:2")
    package static let displayBrightnessDecreaseShortcut = Preference(DefaultsKey.displayBrightnessDecreaseShortcut, default: "shift+command:27")
    package static let displayBrightnessIncreaseShortcut = Preference(DefaultsKey.displayBrightnessIncreaseShortcut, default: "shift+command:24")
    package static let keyboardBrightnessDecreaseShortcut = Preference(DefaultsKey.keyboardBrightnessDecreaseShortcut, default: "option+command:27")
    package static let keyboardBrightnessIncreaseShortcut = Preference(DefaultsKey.keyboardBrightnessIncreaseShortcut, default: "option+command:24")
    package static let musicBlockReplacementPath = Preference(DefaultsKey.musicBlockReplacementPath, default: "")
    package static let cleanerScheduleFrequency = Preference(DefaultsKey.cleanerScheduleFrequency, default: "off")
    package static let whatsAppDownloadsCategories = Preference(DefaultsKey.whatsAppDownloadsCategories, default: "image,video,audio")
    package static let whatsAppOrganizerDestinationPath = Preference(DefaultsKey.whatsAppOrganizerDestinationPath, default: "")
    package static let whatsAppOrganizerCategories = Preference(DefaultsKey.whatsAppOrganizerCategories, default: "image,video,audio,document,archive,other")
    package static let whatsAppOrganizerLayout = Preference(DefaultsKey.whatsAppOrganizerLayout, default: "flat")
    package static let whatsAppOrganizerDuplicateAction = Preference(DefaultsKey.whatsAppOrganizerDuplicateAction, default: "trashNew")
    package static let urlCleanerCustomParameters = Preference(DefaultsKey.urlCleanerCustomParameters, default: "")
    package static let urlCleanerSiteParameters = Preference(DefaultsKey.urlCleanerSiteParameters, default: "")
    package static let urlCleanerDisabledParameters = Preference(DefaultsKey.urlCleanerDisabledParameters, default: "")
    package static let killProcessSortBy = Preference(DefaultsKey.killProcessSortBy, default: "cpu")
    package static let appUpdatesRules = Preference(DefaultsKey.appUpdatesRules, default: "[]")
    package static let menuBarPreset = Preference(DefaultsKey.menuBarPreset, default: "dense")
    package static let menuBarMetricAppearance = Preference(DefaultsKey.menuBarMetricAppearance, default: "values")
    package static let menuBarIconSymbol = Preference(DefaultsKey.menuBarIconSymbol, default: "")
    package static let windowLayoutHiddenActions = Preference(DefaultsKey.windowLayoutHiddenActions, default: "")
    package static let menuBarLabelStyle = Preference(DefaultsKey.menuBarLabelStyle, default: "compact")
    package static let menuBarMemoryStyle = Preference(DefaultsKey.menuBarMemoryStyle, default: "percent")
    package static let menuBarDiskStyle = Preference(DefaultsKey.menuBarDiskStyle, default: "percent")
    package static let monitorMemoryMetric = Preference(DefaultsKey.monitorMemoryMetric, default: "used")
    package static let fanControlResumeConfiguration = Preference(DefaultsKey.fanControlResumeConfiguration, default: "")
    package static let fanControlHelperVersion = Preference(DefaultsKey.fanControlHelperVersion, default: "")
    package static let mediaImageWatermarkText = Preference(DefaultsKey.mediaImageWatermarkText, default: "")
    package static let mediaImageWatermarkLogoPath = Preference(DefaultsKey.mediaImageWatermarkLogoPath, default: "")
    package static let mediaImageRenamePattern = Preference(DefaultsKey.mediaImageRenamePattern, default: "")
    package static let mediaImageProfiles = Preference(DefaultsKey.mediaImageProfiles, default: "[]")
    package static let mediaImageSelectedProfileID = Preference(DefaultsKey.mediaImageSelectedProfileID, default: "")
    package static let colorPickerFormat = Preference(DefaultsKey.colorPickerFormat, default: "hex")
    package static let wallpaperFilter = Preference(DefaultsKey.wallpaperFilter, default: "all")
    package static let commandBarAliases = Preference(DefaultsKey.commandBarAliases, default: "")
    package static let commandBarPins = Preference(DefaultsKey.commandBarPins, default: "")
    package static let commandBarHidden = Preference(DefaultsKey.commandBarHidden, default: "")
    package static let commandBarFileScopes = Preference(DefaultsKey.commandBarFileScopes, default: "")
    package static let commandBarFileIgnores = Preference(DefaultsKey.commandBarFileIgnores, default: "")
    package static let commandBarPositionOffset = Preference(DefaultsKey.commandBarPositionOffset, default: "")
    package static let commandBarEmojiSkinTone = Preference(DefaultsKey.commandBarEmojiSkinTone, default: "")
    package static let quickLauncherHiddenItems = Preference(DefaultsKey.quickLauncherHiddenItems, default: "")
    package static let recorderSaveFolder = Preference(DefaultsKey.recorderSaveFolder, default: "")
    package static let screenshotSaveFolder = Preference(DefaultsKey.screenshotSaveFolder, default: "")
    package static let screenshotSaveSubfolder = Preference(DefaultsKey.screenshotSaveSubfolder, default: "")
    package static let screenshotFileNamePattern = Preference(DefaultsKey.screenshotFileNamePattern, default: "")
    package static let screenshotDefaultAction = Preference(DefaultsKey.screenshotDefaultAction, default: "")
    package static let screenshotLastTool = Preference(DefaultsKey.screenshotLastTool, default: "arrow")
    package static let screenshotLastColor = Preference(DefaultsKey.screenshotLastColor, default: "red")
    package static let screenshotLastStroke = Preference(DefaultsKey.screenshotLastStroke, default: "medium")
    package static let screenshotLastArrowStyle = Preference(DefaultsKey.screenshotLastArrowStyle, default: "filled")
    package static let screenshotLastSticker = Preference(DefaultsKey.screenshotLastSticker, default: "check")
    package static let screenshotToolShortcuts = Preference(DefaultsKey.screenshotToolShortcuts, default: "")
    package static let screenshotBackdropStyle = Preference(DefaultsKey.screenshotBackdropStyle, default: "")
    package static let screenshotBackdropPresets = Preference(DefaultsKey.screenshotBackdropPresets, default: "[]")
    package static let screenshotWatermarkStyle = Preference(DefaultsKey.screenshotWatermarkStyle, default: "")
    package static let screenshotWatermarkPresets = Preference(DefaultsKey.screenshotWatermarkPresets, default: "[]")
    package static let previewSize = Preference(DefaultsKey.previewSize, default: "normal")
    package static let switcherPreviewSize = Preference(DefaultsKey.switcherPreviewSize, default: "normal")
    package static let notchControlOrder = Preference(DefaultsKey.notchControlOrder, default: "")
    package static let notchAgentsCardOrder = Preference(DefaultsKey.notchAgentsCardOrder, default: "")
    package static let notchAgentsHiddenCards = Preference(DefaultsKey.notchAgentsHiddenCards, default: "")
    package static let notchHiddenModules = Preference(DefaultsKey.notchHiddenModules, default: "")
    package static let notchModuleOrder = Preference(DefaultsKey.notchModuleOrder, default: "")
    package static let keyboardDebounceKeyWindows = Preference(DefaultsKey.keyboardDebounceKeyWindows, default: "")
    package static let commandBarDisabledSources = Preference(DefaultsKey.commandBarDisabledSources, default: "")
    package static let windowEdgeSnapDisabledZones = Preference(DefaultsKey.windowEdgeSnapDisabledZones, default: "")

    // MARK: Lists and tables

    package static let keepAwakeRunningAppBundleIDs = Preference(
        DefaultsKey.keepAwakeRunningAppBundleIDs, default: [String]())
    package static let mouseButtonShortcuts = Preference(DefaultsKey.mouseButtonShortcuts, default: [String: String]())
    package static let smoothScrollExceptions = Preference(DefaultsKey.smoothScrollExceptions, default: [String]())
    package static let linearScrollExceptions = Preference(DefaultsKey.linearScrollExceptions, default: [String]())
    package static let scrollInverterExceptions = Preference(DefaultsKey.scrollInverterExceptions, default: [String]())
    package static let focusFollowsMouseExceptions = Preference(
        DefaultsKey.focusFollowsMouseExceptions, default: [String]())
    package static let mouseNavigationExceptions = Preference(
        DefaultsKey.mouseNavigationExceptions, default: [String]())
    package static let mouseButtonExceptions = Preference(DefaultsKey.mouseButtonExceptions, default: [String]())
    package static let middleClickExceptions = Preference(DefaultsKey.middleClickExceptions, default: [String]())
    package static let superKeyExceptions = Preference(DefaultsKey.superKeyExceptions, default: [String]())
    package static let switcherAppRules = Preference(DefaultsKey.switcherAppRules, default: [String: String]())
    package static let audioPriorityOutputUIDs = Preference(DefaultsKey.audioPriorityOutputUIDs, default: [String]())
    package static let audioPriorityInputUIDs = Preference(DefaultsKey.audioPriorityInputUIDs, default: [String]())
    package static let audioPriorityDeviceNames = Preference(
        DefaultsKey.audioPriorityDeviceNames, default: [String: String]())
    package static let quitProtectionQuitExceptions = Preference(
        DefaultsKey.quitProtectionQuitExceptions, default: [String]())
    package static let quitProtectionCloseExceptions = Preference(
        DefaultsKey.quitProtectionCloseExceptions, default: [String]())
    package static let shelfAutomaticExclusions = Preference(DefaultsKey.shelfAutomaticExclusions, default: [String]())
    package static let whatsAppDownloadsExclusions = Preference(
        DefaultsKey.whatsAppDownloadsExclusions, default: [String]())
    package static let notchCalendarExcluded = Preference(DefaultsKey.notchCalendarExcluded, default: [String]())
    package static let windowMaximizeExcludedApps = Preference(
        DefaultsKey.windowMaximizeExcludedApps, default: [String]())
    package static let appUpdatesNotifiedIDs = Preference(DefaultsKey.appUpdatesNotifiedIDs, default: [String]())
    package static let clipboardHistoryIgnoredApps = Preference(
        DefaultsKey.clipboardHistoryIgnoredApps, default: [String]())
    package static let windowLayoutIgnoredApps = Preference(DefaultsKey.windowLayoutIgnoredApps, default: [String]())
    package static let windowPreviewExcludedApps = Preference(
        DefaultsKey.windowPreviewExcludedApps, default: [String]())
    package static let switcherPreviewExcludedApps = Preference(
        DefaultsKey.switcherPreviewExcludedApps, default: [String]())
    package static let diskEjectExcludedVolumes = Preference(DefaultsKey.diskEjectExcludedVolumes, default: [String]())

    // MARK: Computed defaults

    package static let keepAwakeIconTint = Preference(DefaultsKey.keepAwakeIconTint, default: KeepAwakeIconTint.orange.rawValue)
    package static let keepAwakeActiveIcon = Preference(DefaultsKey.keepAwakeActiveIcon, default: KeepAwakeActiveIcon.vitruvian.rawValue)
    package static let focusFollowsMouseRaise = Preference(DefaultsKey.focusFollowsMouseRaise, default: true)
    package static let focusFollowsMouseWaitForStop = Preference(DefaultsKey.focusFollowsMouseWaitForStop, default: true)
    package static let focusFollowsMouseDelay = Preference(DefaultsKey.focusFollowsMouseDelay, default: FocusFollowsMouseSupport.defaultDelayMilliseconds)
    package static let linearScrollLines = Preference(DefaultsKey.linearScrollLines, default: ScrollWheelSupport.defaultLinesPerNotch)
    package static let smoothScrollResponse = Preference(DefaultsKey.smoothScrollResponse, default: SmoothScrollSupport.defaultResponse)
    package static let smoothScrollCoast = Preference(DefaultsKey.smoothScrollCoast, default: SmoothScrollSupport.defaultCoast)
    package static let superKeySource = Preference(DefaultsKey.superKeySource, default: SuperKeySource.capsLock.rawValue)
    package static let superKeyModifiers = Preference(DefaultsKey.superKeyModifiers, default: SuperKeySupport.defaultModifierStorageValue)
    package static let superKeySoloAction = Preference(DefaultsKey.superKeySoloAction, default: SuperKeySoloAction.none.rawValue)
    package static let switcherWindowlessApps = Preference(DefaultsKey.switcherWindowlessApps, default: SwitcherWindowlessApps.fallback.rawValue)
    package static let switcherMinimizedPlacement = Preference(DefaultsKey.switcherMinimizedPlacement, default: WindowSwitchMinimizedPlacement.normal.rawValue)
    package static let switcherAppearanceDelay = Preference(DefaultsKey.switcherAppearanceDelay, default: SwitcherSupport.defaultAppearanceDelayMilliseconds)
    package static let switcherScreenPlacement = Preference(DefaultsKey.switcherScreenPlacement, default: SwitcherScreenPlacement.fallback.rawValue)
    package static let dockPreviewOpenDelay = Preference(DefaultsKey.dockPreviewOpenDelay, default: DockPreviewSupport.defaultOpenDelayMilliseconds)
    package static let quitProtectionQuitMode = Preference(DefaultsKey.quitProtectionQuitMode, default: QuitProtectionMode.hold.rawValue)
    package static let quitProtectionQuitHoldDurationMs = Preference(DefaultsKey.quitProtectionQuitHoldDurationMs, default: QuitProtectionSupport.defaultHoldDurationMilliseconds)
    package static let quitProtectionQuitDoubleIntervalMs = Preference(DefaultsKey.quitProtectionQuitDoubleIntervalMs, default: QuitProtectionSupport.defaultDoublePressIntervalMilliseconds)
    package static let quitProtectionQuitExtraModifier = Preference(DefaultsKey.quitProtectionQuitExtraModifier, default: QuitProtectionExtraModifier.shift.rawValue)
    package static let quitProtectionQuitScope = Preference(DefaultsKey.quitProtectionQuitScope, default: QuitProtectionScope.all.rawValue)
    package static let quitProtectionCloseMode = Preference(DefaultsKey.quitProtectionCloseMode, default: QuitProtectionMode.hold.rawValue)
    package static let quitProtectionCloseHoldDurationMs = Preference(DefaultsKey.quitProtectionCloseHoldDurationMs, default: QuitProtectionSupport.defaultHoldDurationMilliseconds)
    package static let quitProtectionCloseDoubleIntervalMs = Preference(DefaultsKey.quitProtectionCloseDoubleIntervalMs, default: QuitProtectionSupport.defaultDoublePressIntervalMilliseconds)
    package static let quitProtectionCloseExtraModifier = Preference(DefaultsKey.quitProtectionCloseExtraModifier, default: QuitProtectionExtraModifier.shift.rawValue)
    package static let quitProtectionCloseScope = Preference(DefaultsKey.quitProtectionCloseScope, default: QuitProtectionScope.all.rawValue)
    package static let brightnessKeyStep = Preference(DefaultsKey.brightnessKeyStep, default: BrightnessSupport.KeyStep.standard.rawValue)
    package static let cleanerScreenshotAgeDays = Preference(DefaultsKey.cleanerScreenshotAgeDays, default: CleanerPolicy.defaultScreenshotAgeDays)
    package static let notchSize = Preference(DefaultsKey.notchSize, default: NotchSize.spacious.rawValue)
    package static let notchCustomWidth = Preference(DefaultsKey.notchCustomWidth, default: NotchSize.defaultWidth)
    package static let notchCustomHeight = Preference(DefaultsKey.notchCustomHeight, default: NotchSize.defaultHeight)
    package static let notchAgentsPeriod = Preference(DefaultsKey.notchAgentsPeriod, default: AgentPeriod.today.rawValue)
    package static let notchAgentsLimitDisplay = Preference(DefaultsKey.notchAgentsLimitDisplay, default: NotchAgentLimitDisplay.remaining.rawValue)
    package static let notchAgentsReadout = Preference(DefaultsKey.notchAgentsReadout, default: NotchAgentReadout.elapsed.rawValue)
    package static let notchAgentsFinishMinimum = Preference(DefaultsKey.notchAgentsFinishMinimum, default: NotchAgentSupport.defaultFinishMinimum)
    package static let notchAgentsLimitThreshold = Preference(DefaultsKey.notchAgentsLimitThreshold, default: NotchAgentSupport.defaultLimitThreshold)
    package static let notchDisplay = Preference(DefaultsKey.notchDisplay, default: NotchDisplay.automatic.rawValue)
    package static let notchHoverDelay = Preference(DefaultsKey.notchHoverDelay, default: NotchSupport.defaultHoverDelay)
    package static let notchQuickAccessLayout = Preference(DefaultsKey.notchQuickAccessLayout, default: Data())
    package static let radialMenuActivationMode = Preference(DefaultsKey.radialMenuActivationMode, default: RadialMenuActivationMode.pressOrHold.rawValue)
    package static let appUpdatesCheckFrequency = Preference(DefaultsKey.appUpdatesCheckFrequency, default: AppUpdatesSupport.CheckFrequency.off.rawValue)
    package static let temperatureUnit = Preference(DefaultsKey.temperatureUnit, default: TemperatureUnit.celsius.rawValue)
    package static let networkSpeedUnit = Preference(DefaultsKey.networkSpeedUnit, default: NetworkSpeedUnit.bytes.rawValue)
    package static let fanControlMode = Preference(DefaultsKey.fanControlMode, default: FanControlMode.system.rawValue)
    package static let fanControlCoolingLevel = Preference(DefaultsKey.fanControlCoolingLevel, default: FanControlPolicy.defaultCoolingLevel)
    package static let fanControlCurves = Preference(DefaultsKey.fanControlCurves, default: FanControlConfiguration.defaultCurvesStorage)
    package static let mediaLastTool = Preference(DefaultsKey.mediaLastTool, default: MediaTool.videoCompressor.rawValue)
    package static let mediaVideoSizing = Preference(DefaultsKey.mediaVideoSizing, default: MediaSizingMode.resolution.rawValue)
    package static let mediaGIFSizing = Preference(DefaultsKey.mediaGIFSizing, default: MediaSizingMode.resolution.rawValue)
    package static let mediaImageFormat = Preference(DefaultsKey.mediaImageFormat, default: MediaImageFormat.jpeg.rawValue)
    package static let mediaImageResizeKind = Preference(DefaultsKey.mediaImageResizeKind, default: MediaImageResizeKind.maxDimension.rawValue)
    package static let mediaImageExactResizeMode = Preference(DefaultsKey.mediaImageExactResizeMode, default: MediaImageExactResizeMode.stretch.rawValue)
    package static let mediaImageWatermarkKind = Preference(DefaultsKey.mediaImageWatermarkKind, default: MediaImageWatermarkKind.off.rawValue)
    package static let mediaImageWatermarkPosition = Preference(DefaultsKey.mediaImageWatermarkPosition, default: MediaImageWatermarkPosition.bottomRight.rawValue)
    package static let mediaImageBackground = Preference(DefaultsKey.mediaImageBackground, default: MediaImageBackground.transparent.rawValue)
    package static let clipboardHistoryMenuBarPreviewLength = Preference(DefaultsKey.clipboardHistoryMenuBarPreviewLength, default: Defaults.defaultClipboardMenuBarPreviewLength)
    package static let clipboardAutoClearDelay = Preference(DefaultsKey.clipboardAutoClearDelay, default: Defaults.defaultClipboardAutoClearDelay)
    package static let finderRenameShortcut = Preference(DefaultsKey.finderRenameShortcut, default: GlobalShortcut.finderRenameDefault.storageValue)
    package static let scratchpadRetention = Preference(DefaultsKey.scratchpadRetention, default: ScratchpadRetention.never.rawValue)
    package static let scratchpadTextSize = Preference(DefaultsKey.scratchpadTextSize, default: ScratchpadSupport.defaultTextSize)
    package static let recorderQuality = Preference(DefaultsKey.recorderQuality, default: RecorderSupport.Quality.balanced.rawValue)
    package static let recorderGIFSize = Preference(DefaultsKey.recorderGIFSize, default: RecorderSupport.GIFSize.medium.rawValue)
    package static let screenshotToolOrder = Preference(DefaultsKey.screenshotToolOrder, default: ScreenshotSupport.Tool.defaultOrderStorage)
    package static let screenshotUploadDuration = Preference(DefaultsKey.screenshotUploadDuration, default: ScreenshotShareDuration.oneHour.rawValue)
    package static let windowDirectionalShortcut = Preference(DefaultsKey.windowDirectionalShortcut, default: GlobalShortcut.windowDirectionalDefault.storageValue)
    package static let windowGestureModifiers = Preference(DefaultsKey.windowGestureModifiers, default: WindowGestureSupport.defaultModifierStorageValue)
    package static let appearance = Preference(DefaultsKey.appearance, default: AppAppearance.fallback.rawValue)
    package static let scrollHorizontalModifier = Preference(
        DefaultsKey.scrollHorizontalModifier, default: ScrollHorizontalModifier.shift.rawValue)
    package static let mouseClickDebounceWindowMs = Preference(
        DefaultsKey.mouseClickDebounceWindowMs, default: Defaults.defaultMouseClickDebounceWindowMs)
    package static let switcherWindowShortcut = Preference(
        DefaultsKey.switcherWindowShortcut, default: GlobalShortcut.switcherWindowDefault.storageValue)
    package static let mixerHeadphonesDisconnectVolumePercent = Preference(
        DefaultsKey.mixerHeadphonesDisconnectVolumePercent, default: Defaults.defaultMixerHeadphonesDisconnectVolumePercent)
    package static let soundOutputSwitcherShortcut = Preference(
        DefaultsKey.soundOutputSwitcherShortcut, default: GlobalShortcut.soundOutputSwitcherDefault.storageValue)
    package static let autoQuitExceptions = Preference(
        DefaultsKey.autoQuitExceptions, default: Defaults.mandatoryAutoQuitExceptionBundleIDs)
    package static let shelfDockPlacement = Preference(
        DefaultsKey.shelfDockPlacement, default: ShelfDockPlacement.menuBar.rawValue)
    package static let whatsAppOrganizerRecords = Preference(DefaultsKey.whatsAppOrganizerRecords, default: Data())
    package static let whatsAppOrganizerUndoTransaction = Preference(
        DefaultsKey.whatsAppOrganizerUndoTransaction, default: Data())
    package static let snippetLibraryShortcut = Preference(
        DefaultsKey.snippetLibraryShortcut, default: GlobalShortcut.snippetLibraryDefault.storageValue)
    package static let snippetSoundName = Preference(
        DefaultsKey.snippetSoundName, default: Defaults.defaultSnippetSoundName)
    package static let notchIdleContent = Preference(
        DefaultsKey.notchIdleContent, default: NotchIdleContent.music.rawValue)
    package static let notchHiddenControls = Preference(
        DefaultsKey.notchHiddenControls, default: NotchControlItem.defaultHidden)
    package static let notchTimerMode = Preference(DefaultsKey.notchTimerMode, default: NotchTimerMode.timer.rawValue)
    package static let notchAgentsLimitFocus = Preference(
        DefaultsKey.notchAgentsLimitFocus, default: NotchAgentLimitFocus.mostUsed.rawValue)
    package static let notchWatchCondition = Preference(
        DefaultsKey.notchWatchCondition, default: NotchWatchCondition.changes.rawValue)
    package static let notchSilhouette = Preference(
        DefaultsKey.notchSilhouette, default: NotchSilhouette.capsule.rawValue)
    package static let notchMascotStyle = Preference(
        DefaultsKey.notchMascotStyle, default: NotchMascotStyle.minimal.rawValue)
    package static let notchMascotShape = Preference(
        DefaultsKey.notchMascotShape, default: NotchMascotShape.ball.rawValue)
    package static let notchMascotPalette = Preference(
        DefaultsKey.notchMascotPalette, default: NotchMascotPalette.pearl.rawValue)
    package static let notchMascotSide = Preference(
        DefaultsKey.notchMascotSide, default: NotchMascotSide.left.rawValue)
    package static let notchMascotVisitFrequency = Preference(
        DefaultsKey.notchMascotVisitFrequency, default: NotchMascotVisitFrequency.normal.rawValue)
    package static let notchCommandBarStyle = Preference(
        DefaultsKey.notchCommandBarStyle, default: NotchCommandBarStyle.droplet.rawValue)
    package static let notchHomeModule = Preference(DefaultsKey.notchHomeModule, default: NotchModule.controls.rawValue)
    package static let radialMenuShortcut = Preference(
        DefaultsKey.radialMenuShortcut, default: GlobalShortcut.radialMenuDefault.storageValue)
    package static let radialMenuMouseButton = Preference(
        DefaultsKey.radialMenuMouseButton, default: RadialMenuMouseTrigger.off.rawValue)
    package static let keyboardDebounceWindowMs = Preference(
        DefaultsKey.keyboardDebounceWindowMs, default: Defaults.defaultKeyboardDebounceWindowMs)
    package static let mediaVideoCodec = Preference(DefaultsKey.mediaVideoCodec, default: MediaVideoCodec.h264.rawValue)
    package static let pastePlainShortcut = Preference(
        DefaultsKey.pastePlainShortcut, default: GlobalShortcut.pastePlainDefault.storageValue)
    package static let colorPickerShortcut = Preference(
        DefaultsKey.colorPickerShortcut, default: GlobalShortcut.colorPickerDefault.storageValue)
    package static let screenOCRShortcut = Preference(
        DefaultsKey.screenOCRShortcut, default: GlobalShortcut.screenOCRDefault.storageValue)
    package static let micMuteShortcut = Preference(
        DefaultsKey.micMuteShortcut, default: GlobalShortcut.micMuteDefault.storageValue)
    package static let cameraPreviewShortcut = Preference(
        DefaultsKey.cameraPreviewShortcut, default: GlobalShortcut.cameraPreviewDefault.storageValue)
    package static let scratchpadShortcut = Preference(
        DefaultsKey.scratchpadShortcut, default: GlobalShortcut.scratchpadDefault.storageValue)
    package static let nexusAgentShortcut = Preference(
        DefaultsKey.nexusAgentShortcut, default: GlobalShortcut.nexusAgentDefault.storageValue)
    package static let commandBarShortcut = Preference(
        DefaultsKey.commandBarShortcut, default: GlobalShortcut.commandBarDefault.storageValue)
    package static let quickLauncherShortcut = Preference(
        DefaultsKey.quickLauncherShortcut, default: GlobalShortcut.quickLauncherDefault.storageValue)
    package static let clipboardHistoryShortcut = Preference(
        DefaultsKey.clipboardHistoryShortcut, default: GlobalShortcut.clipboardDefault.storageValue)
    package static let recorderShortcut = Preference(
        DefaultsKey.recorderShortcut, default: GlobalShortcut.screenRecorderDefault.storageValue)
    package static let recorderEditorPresets = Preference(DefaultsKey.recorderEditorPresets, default: Data())
    package static let screenshotShortcut = Preference(
        DefaultsKey.screenshotShortcut, default: GlobalShortcut.screenshotDefault.storageValue)
    package static let screenshotFullScreenShortcut = Preference(
        DefaultsKey.screenshotFullScreenShortcut, default: GlobalShortcut.screenshotFullScreenDefault.storageValue)
    package static let screenshotLastCaptureShortcut = Preference(
        DefaultsKey.screenshotLastCaptureShortcut, default: GlobalShortcut.screenshotLastCaptureDefault.storageValue)
    package static let recentCapturesShortcut = Preference(
        DefaultsKey.recentCapturesShortcut, default: GlobalShortcut.recentCapturesDefault.storageValue)
    package static let screenshotClipboardShortcut = Preference(
        DefaultsKey.screenshotClipboardShortcut, default: GlobalShortcut.screenshotClipboardDefault.storageValue)
    package static let screenshotLastTextSize = Preference(
        DefaultsKey.screenshotLastTextSize, default: ScreenshotSupport.defaultTextSize)
    package static let screenshotLastBlurLevel = Preference(
        DefaultsKey.screenshotLastBlurLevel, default: ScreenshotSupport.BlurStrength.defaultLevel)
    package static let screenshotLastBlurStyle = Preference(
        DefaultsKey.screenshotLastBlurStyle, default: ScreenshotSupport.BlurStyleID.pixelate.rawValue)
    package static let screenshotLastBlurTextOnly = Preference(DefaultsKey.screenshotLastBlurTextOnly, default: false)
    package static let screenshotUploadShortcut = Preference(
        DefaultsKey.screenshotUploadShortcut, default: GlobalShortcut.screenshotUploadDefault.storageValue)
    package static let screenshotPreviewDuration = Preference(
        DefaultsKey.screenshotPreviewDuration, default: ScreenshotSupport.defaultConfirmationPreviewDuration)
    package static let pointerDisplayShortcut = Preference(
        DefaultsKey.pointerDisplayShortcut, default: GlobalShortcut.pointerNextDisplayDefault.storageValue)
    package static let windowLayoutShortcutLeft = Preference(
        DefaultsKey.windowLayoutShortcutLeft, default: GlobalShortcut.windowLayoutLeftDefault.storageValue)
    package static let windowLayoutShortcutRight = Preference(
        DefaultsKey.windowLayoutShortcutRight, default: GlobalShortcut.windowLayoutRightDefault.storageValue)
    package static let windowLayoutShortcutTop = Preference(
        DefaultsKey.windowLayoutShortcutTop, default: GlobalShortcut.windowLayoutTopDefault.storageValue)
    package static let windowLayoutShortcutBottom = Preference(
        DefaultsKey.windowLayoutShortcutBottom, default: GlobalShortcut.windowLayoutBottomDefault.storageValue)
    package static let windowLayoutShortcutCenterHalf = Preference(
        DefaultsKey.windowLayoutShortcutCenterHalf, default: WindowLayoutAction.clearedShortcutStorageValue)
    package static let windowLayoutShortcutTopLeft = Preference(
        DefaultsKey.windowLayoutShortcutTopLeft, default: GlobalShortcut.windowLayoutTopLeftDefault.storageValue)
    package static let windowLayoutShortcutTopRight = Preference(
        DefaultsKey.windowLayoutShortcutTopRight, default: GlobalShortcut.windowLayoutTopRightDefault.storageValue)
    package static let windowLayoutShortcutBottomLeft = Preference(
        DefaultsKey.windowLayoutShortcutBottomLeft, default: GlobalShortcut.windowLayoutBottomLeftDefault.storageValue)
    package static let windowLayoutShortcutBottomRight = Preference(
        DefaultsKey.windowLayoutShortcutBottomRight, default: GlobalShortcut.windowLayoutBottomRightDefault.storageValue)
    package static let windowLayoutShortcutMaximize = Preference(
        DefaultsKey.windowLayoutShortcutMaximize, default: GlobalShortcut.windowLayoutMaximizeDefault.storageValue)
    package static let windowLayoutShortcutMarginMaximize = Preference(
        DefaultsKey.windowLayoutShortcutMarginMaximize, default: WindowLayoutAction.clearedShortcutStorageValue)
    package static let windowLayoutShortcutCenter = Preference(
        DefaultsKey.windowLayoutShortcutCenter, default: GlobalShortcut.windowLayoutCenterDefault.storageValue)
    package static let windowLayoutShortcutRestore = Preference(
        DefaultsKey.windowLayoutShortcutRestore, default: GlobalShortcut.windowLayoutRestoreDefault.storageValue)
    package static let windowLayoutShortcutLeftThird = Preference(
        DefaultsKey.windowLayoutShortcutLeftThird, default: GlobalShortcut.windowLayoutLeftThirdDefault.storageValue)
    package static let windowLayoutShortcutCenterThird = Preference(
        DefaultsKey.windowLayoutShortcutCenterThird, default: GlobalShortcut.windowLayoutCenterThirdDefault.storageValue)
    package static let windowLayoutShortcutRightThird = Preference(
        DefaultsKey.windowLayoutShortcutRightThird, default: GlobalShortcut.windowLayoutRightThirdDefault.storageValue)
    package static let windowLayoutShortcutLeftTwoThirds = Preference(
        DefaultsKey.windowLayoutShortcutLeftTwoThirds, default: GlobalShortcut.windowLayoutLeftTwoThirdsDefault.storageValue)
    package static let windowLayoutShortcutRightTwoThirds = Preference(
        DefaultsKey.windowLayoutShortcutRightTwoThirds, default: GlobalShortcut.windowLayoutRightTwoThirdsDefault.storageValue)
    package static let windowLayoutShortcutCenterTwoThirds = Preference(
        DefaultsKey.windowLayoutShortcutCenterTwoThirds, default: WindowLayoutAction.clearedShortcutStorageValue)
    package static let windowLayoutShortcutTopThird = Preference(
        DefaultsKey.windowLayoutShortcutTopThird, default: WindowLayoutAction.clearedShortcutStorageValue)
    package static let windowLayoutShortcutMiddleThird = Preference(
        DefaultsKey.windowLayoutShortcutMiddleThird, default: WindowLayoutAction.clearedShortcutStorageValue)
    package static let windowLayoutShortcutBottomThird = Preference(
        DefaultsKey.windowLayoutShortcutBottomThird, default: WindowLayoutAction.clearedShortcutStorageValue)
    package static let windowLayoutShortcutTopTwoThirds = Preference(
        DefaultsKey.windowLayoutShortcutTopTwoThirds, default: WindowLayoutAction.clearedShortcutStorageValue)
    package static let windowLayoutShortcutBottomTwoThirds = Preference(
        DefaultsKey.windowLayoutShortcutBottomTwoThirds, default: WindowLayoutAction.clearedShortcutStorageValue)
    package static let windowLayoutShortcutTopQuarter = Preference(
        DefaultsKey.windowLayoutShortcutTopQuarter, default: WindowLayoutAction.clearedShortcutStorageValue)
    package static let windowLayoutShortcutUpperMiddleQuarter = Preference(
        DefaultsKey.windowLayoutShortcutUpperMiddleQuarter, default: WindowLayoutAction.clearedShortcutStorageValue)
    package static let windowLayoutShortcutLowerMiddleQuarter = Preference(
        DefaultsKey.windowLayoutShortcutLowerMiddleQuarter, default: WindowLayoutAction.clearedShortcutStorageValue)
    package static let windowLayoutShortcutBottomQuarter = Preference(
        DefaultsKey.windowLayoutShortcutBottomQuarter, default: WindowLayoutAction.clearedShortcutStorageValue)
    package static let windowLayoutShortcutLeftQuarter = Preference(
        DefaultsKey.windowLayoutShortcutLeftQuarter, default: WindowLayoutAction.clearedShortcutStorageValue)
    package static let windowLayoutShortcutLeftMiddleQuarter = Preference(
        DefaultsKey.windowLayoutShortcutLeftMiddleQuarter, default: WindowLayoutAction.clearedShortcutStorageValue)
    package static let windowLayoutShortcutRightMiddleQuarter = Preference(
        DefaultsKey.windowLayoutShortcutRightMiddleQuarter, default: WindowLayoutAction.clearedShortcutStorageValue)
    package static let windowLayoutShortcutRightQuarter = Preference(
        DefaultsKey.windowLayoutShortcutRightQuarter, default: WindowLayoutAction.clearedShortcutStorageValue)
    package static let windowLayoutShortcutPreviousDisplay = Preference(
        DefaultsKey.windowLayoutShortcutPreviousDisplay, default: WindowLayoutAction.clearedShortcutStorageValue)
    package static let windowLayoutShortcutNextDisplay = Preference(
        DefaultsKey.windowLayoutShortcutNextDisplay, default: GlobalShortcut.windowLayoutNextDisplayDefault.storageValue)
    package static let windowLayoutShortcutTopLeftSixth = Preference(
        DefaultsKey.windowLayoutShortcutTopLeftSixth, default: WindowLayoutAction.clearedShortcutStorageValue)
    package static let windowLayoutShortcutTopCenterSixth = Preference(
        DefaultsKey.windowLayoutShortcutTopCenterSixth, default: WindowLayoutAction.clearedShortcutStorageValue)
    package static let windowLayoutShortcutTopRightSixth = Preference(
        DefaultsKey.windowLayoutShortcutTopRightSixth, default: WindowLayoutAction.clearedShortcutStorageValue)
    package static let windowLayoutShortcutBottomLeftSixth = Preference(
        DefaultsKey.windowLayoutShortcutBottomLeftSixth, default: WindowLayoutAction.clearedShortcutStorageValue)
    package static let windowLayoutShortcutBottomCenterSixth = Preference(
        DefaultsKey.windowLayoutShortcutBottomCenterSixth, default: WindowLayoutAction.clearedShortcutStorageValue)
    package static let windowLayoutShortcutBottomRightSixth = Preference(
        DefaultsKey.windowLayoutShortcutBottomRightSixth, default: WindowLayoutAction.clearedShortcutStorageValue)
    package static let windowLayoutShortcutFullScreen = Preference(
        DefaultsKey.windowLayoutShortcutFullScreen, default: WindowLayoutAction.clearedShortcutStorageValue)
    package static let switcherShortcut = Preference(
        DefaultsKey.switcherShortcut, default: GlobalShortcut.switcherDefault.storageValue)
    package static let smoothScrollStep = Preference(
        DefaultsKey.smoothScrollStep, default: SmoothScrollSupport.defaultStep)
    package static let menuBarUsageBarNormalColor = Preference(
        DefaultsKey.menuBarUsageBarNormalColor, default: MenuBarUsageBarSupport.defaultNormalColor)
    package static let menuBarUsageBarElevatedColor = Preference(
        DefaultsKey.menuBarUsageBarElevatedColor, default: MenuBarUsageBarSupport.defaultElevatedColor)
    package static let menuBarUsageBarCriticalColor = Preference(
        DefaultsKey.menuBarUsageBarCriticalColor, default: MenuBarUsageBarSupport.defaultCriticalColor)
    package static let menuBarUsageBarMediumThreshold = Preference(
        DefaultsKey.menuBarUsageBarMediumThreshold, default: MenuBarUsageBarSupport.defaultMediumThreshold)
    package static let menuBarUsageBarHighThreshold = Preference(
        DefaultsKey.menuBarUsageBarHighThreshold, default: MenuBarUsageBarSupport.defaultHighThreshold)

    // MARK: Off, zero or empty until set

    /// Read as their type's empty value before these were registered, by
    /// views and services alike, so registering them changed no reading.
    package static let autoQuitEnabled = Preference(DefaultsKey.autoQuitEnabled, default: false)
    package static let finderCutPasteEnabled = Preference(DefaultsKey.finderCutPasteEnabled, default: false)
    package static let shelfEnabled = Preference(DefaultsKey.shelfEnabled, default: false)
    package static let menuBarCPU = Preference(DefaultsKey.menuBarCPU, default: false)
    package static let menuBarGPU = Preference(DefaultsKey.menuBarGPU, default: false)
    package static let menuBarMemory = Preference(DefaultsKey.menuBarMemory, default: false)
    package static let menuBarNetwork = Preference(DefaultsKey.menuBarNetwork, default: false)
    package static let menuBarBattery = Preference(DefaultsKey.menuBarBattery, default: false)
    package static let menuBarPower = Preference(DefaultsKey.menuBarPower, default: false)
    package static let onboardingStep = Preference(DefaultsKey.onboardingStep, default: 0)
    package static let commandBarLinks = Preference(DefaultsKey.commandBarLinks, default: Data())
    package static let commandBarRowShortcuts = Preference(DefaultsKey.commandBarRowShortcuts, default: "")

    // GitHub in the notch
    package static let githubWatchedRepositories = Preference(
        DefaultsKey.githubWatchedRepositories, default: GitHubWatchlist.defaultEncoded)
    package static let githubRelayURL = Preference(
        DefaultsKey.githubRelayURL, default: "https://github-relay.ipv1337.dev")
    package static let githubMouseIndicator = Preference(
        DefaultsKey.githubMouseIndicator, default: true)
}
