#!/usr/bin/env bash
# Copyright (c) 2026 VitruvianSoftware
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# td-lib.sh — the single pinned source for the target-determinator binary,
# sourced by tools/ci/affected-targets.sh (presubmit/merge-queue/postsubmit
# selection) and tools/ci/deploy-affected.sh (deploy gating), so the version +
# checksum can never drift between callers.
#
# WHY a prebuilt binary and NOT `go install`: target-determinator's Bazel proto
# bindings (third_party/protobuf/bazel/{analysis,build}) are generated by
# protoc *via Bazel* at build time and are .gitignore'd upstream, so the
# published Go module ships only empty `package analysis`/`package build`
# stubs — `go install` ALWAYS fails with "undefined: analysis.ConfiguredTarget"
# for every released version. Upstream's documented install path is the
# prebuilt GitHub release binary, fetched and checksum-pinned here (the same
# digest-pinning this repo applies to third-party GitHub Actions). The binary
# shells out to `--bazel bazel` (our bazelisk-resolved version), so the Bazel
# it was built against is irrelevant at runtime.
#
# Bump TD_VERSION and TD_SHA256 together; TD_SHA256 is the sha256 of the
# `target-determinator.linux.amd64` release asset for TD_VERSION.
TD_VERSION="v0.34.0"
TD_SHA256="115e1c63d39e2cd0d0b011c9fadc80f059f021176a4ae0de2232cdd83b1f8011"

# fetch_td — resolve a verified target-determinator binary.
#
# On success: sets TD to the executable path and returns 0.
# On failure: sets TD_FETCH_ERROR to a one-line reason and returns 1 — the
# CALLER decides its fail-safe (full sweep for CI selection; deploy anyway for
# the deploy gate). Never exits.
#
# TD_BIN (env) overrides the download entirely — the test hook that lets the
# gate scripts be exercised with a stub binary, and an escape hatch for hosts
# with a local build.
#
# shellcheck disable=SC2034  # TD / TD_FETCH_ERROR are consumed by the
#                            # sourcing scripts (affected-targets.sh,
#                            # deploy-affected.sh).
fetch_td() {
  TD_FETCH_ERROR=""
  if [ -n "${TD_BIN:-}" ]; then
    if [ -x "${TD_BIN}" ]; then
      TD="${TD_BIN}"
      echo "td-lib: using TD_BIN override at ${TD}"
      return 0
    fi
    TD_FETCH_ERROR="TD_BIN='${TD_BIN}' is not an executable"
    return 1
  fi

  # Only linux/amd64 has a pinned asset; any other host is a caller-side
  # fallback, not an error worth retrying.
  case "$(uname -s)/$(uname -m)" in
    Linux/x86_64) _td_asset="target-determinator.linux.amd64" ;;
    *)
      TD_FETCH_ERROR="no pinned target-determinator binary for $(uname -s)/$(uname -m)"
      return 1
      ;;
  esac

  TD="$(mktemp -d)/target-determinator"
  _td_url="https://github.com/bazel-contrib/target-determinator/releases/download/${TD_VERSION}/${_td_asset}"
  echo "td-lib: downloading target-determinator ${TD_VERSION} (${_td_asset})..."
  if ! curl -fsSL --retry 4 --retry-delay 2 --retry-all-errors -o "${TD}" "${_td_url}"; then
    TD_FETCH_ERROR="target-determinator download failed (${_td_url})"
    return 1
  fi
  echo "${TD_SHA256}  ${TD}" > "${TD}.sha256"
  if ! sha256sum --check --status "${TD}.sha256"; then
    TD_FETCH_ERROR="target-determinator checksum mismatch (expected ${TD_SHA256} for ${_td_asset})"
    return 1
  fi
  chmod +x "${TD}"
  return 0
}
