name: commitlint

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: "https://registry.npmjs.org"
          scope: "@vitruviansoftware"

      - name: Install commitlint
        run: |
          npm install -D @commitlint/cli @commitlint/config-conventional
          echo "module.exports = { extends: ['@commitlint/config-conventional'], rules: {'subject-case': [0], 'header-max-length': [0]} };" > commitlint.config.js

      - name: Validate PR title
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: 'echo "$TITLE" | npx commitlint --verbose'
