load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "sync",
    srcs = ["daemon.go"],
    importpath = "github.com/VitruvianSoftware/devx/internal/sync",
    visibility = ["//devx:__subpackages__"],
)
