load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "importsmoke",
    srcs = ["smoke.go"],
    importpath = "github.com/VitruvianSoftware/devx/internal/importsmoke",
    visibility = ["//devx:__subpackages__"],
)
