// Copyright (c) 2026 VitruvianSoftware
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

package bridge

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// GenerateEnvFile creates ~/.devx/bridge.env with BRIDGE_<SERVICE>_URL,
// BRIDGE_<SERVICE>_HOST, and BRIDGE_<SERVICE>_PORT variables for each
// active port-forward. This file is consumed by devx shell.
func GenerateEnvFile(entries []SessionEntry) error {
	envPath, err := EnvPath()
	if err != nil {
		return err
	}

	dir := filepath.Dir(envPath)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("creating %s: %w", dir, err)
	}

	var lines []string
	lines = append(lines, "# Auto-generated by devx bridge connect — do not edit manually")
	lines = append(lines, "# These variables map remote K8s services to their locally forwarded ports.")
	lines = append(lines, "")

	for _, e := range entries {
		prefix := envPrefix(e.Service)
		lines = append(lines,
			fmt.Sprintf("# %s/%s (remote :%d → local :%d)", e.Namespace, e.Service, e.RemotePort, e.LocalPort),
			fmt.Sprintf("%s_URL=http://127.0.0.1:%d", prefix, e.LocalPort),
			fmt.Sprintf("%s_HOST=127.0.0.1", prefix),
			fmt.Sprintf("%s_PORT=%d", prefix, e.LocalPort),
			"",
		)
	}

	content := strings.Join(lines, "\n")
	return os.WriteFile(envPath, []byte(content), 0o644)
}

// LoadEnvVars reads the bridge env file and returns the key-value pairs.
// Returns an empty map if the file does not exist.
func LoadEnvVars() (map[string]string, error) {
	envPath, err := EnvPath()
	if err != nil {
		return nil, err
	}

	data, err := os.ReadFile(envPath)
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("reading %s: %w", envPath, err)
	}

	vars := make(map[string]string)
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		parts := strings.SplitN(line, "=", 2)
		if len(parts) == 2 {
			vars[strings.TrimSpace(parts[0])] = strings.TrimSpace(parts[1])
		}
	}
	return vars, nil
}

// envPrefix normalizes a K8s service name into an env var prefix.
// e.g., "payments-api" → "BRIDGE_PAYMENTS_API"
func envPrefix(service string) string {
	upper := strings.ToUpper(service)
	// Replace common separator characters with underscores
	replacer := strings.NewReplacer("-", "_", ".", "_", "/", "_")
	return "BRIDGE_" + replacer.Replace(upper)
}
