load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "nuke",
    srcs = ["nuke.go"],
    importpath = "github.com/VitruvianSoftware/devx/internal/nuke",
    visibility = ["//devx:__subpackages__"],
    deps = ["//devx/internal/provider"],
)
