// Copyright (c) 2026 VitruvianSoftware
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

package usb

import (
	"encoding/base64"
	"fmt"
	"strings"
)

// DefaultTailscaleVersion is the pinned Tailscale static-binary version used when
// the spec does not override it. Pinned (not "latest") so first boot is
// offline-deterministic and golden-testable.
const DefaultTailscaleVersion = "1.98.4"

// FCOSStickName labels the FCOS boot entry's medium. coreos-installer writes a
// native GPT Fedora CoreOS disk (fetching the metal image from the stream
// itself), so this is a provenance label for the build plan/manifest, not a file
// devx places on the stick.
const FCOSStickName = "fedora-coreos.x86_64.gpt"

// FCOSRenderer packages the canonical join script as a Fedora CoreOS Ignition
// config (authored as Butane). This is the highest-reuse renderer — it rides the
// same FCOS/Ignition/butane stack devx already uses in internal/ignition.
type FCOSRenderer struct{}

// Name implements Renderer.
func (FCOSRenderer) Name() string { return "fcos" }

// Modes implements Renderer.
func (FCOSRenderer) Modes() []Mode { return []Mode{ModeEphemeral, ModeInstall} }

// Render implements Renderer. It emits a Butane file (.bu) that writes the join
// script and a oneshot systemd unit to run it. The build layer compiles the .bu
// to Ignition with butane (gated) and embeds it into the live ISO.
func (FCOSRenderer) Render(spec JoinSpec, m Mode, sink ArtifactSink) ([]BootEntry, error) {
	if !modeSupported(FCOSRenderer{}, m) {
		return nil, fmt.Errorf("fcos: unsupported mode %q", m)
	}
	spec.Mode = m

	script, err := RenderJoinScript(spec)
	if err != nil {
		return nil, fmt.Errorf("fcos: rendering join script: %w", err)
	}

	butane := fcosButane(spec, script)
	dir := fmt.Sprintf("fcos/%s", m)
	buPath := dir + "/devx-join.bu"
	if err := sink.Add(Artifact{Path: buPath, Contents: []byte(butane), Mode: 0o644}); err != nil {
		return nil, err
	}
	// Also drop the raw script for transparency/debugging.
	if err := sink.Add(Artifact{Path: dir + "/devx-join.sh", Contents: []byte(script), Mode: 0o755}); err != nil {
		return nil, err
	}

	notes := "coreos-installer writes a GPT Fedora CoreOS disk with this Ignition embedded; FCOS grows root to fill the stick on first boot."
	if m == ModeInstall {
		notes = "Live env runs coreos-installer to persist FCOS + this Ignition to the internal disk, then reboots."
	}

	return []BootEntry{{
		MenuTitle:     menuTitle("Fedora CoreOS", m),
		BaseImage:     FCOSStickName,
		Renderer:      "fcos",
		Mode:          m,
		InstallToDisk: m == ModeInstall,
		Injection: Injection{
			Kind:        InjectIgnition,
			PayloadPath: buPath,
			Notes:       notes,
		},
	}}, nil
}

// fcosButane returns a Butane (FCOS 1.5.0) document that writes the join script
// and, when Tailscale is enabled, provisions tailscaled from pinned static
// binaries (immutable FCOS cannot run install.sh) plus a oneshot that runs the
// join on first boot. Tailscale is a Wants — never a Requires — of the join, so a
// Tailscale failure can't block a LAN-reachable join.
func fcosButane(s JoinSpec, script string) string {
	tsEnabled := s.TailscaleAuthKey != ""
	tsVersion := s.TailscaleVersion
	if tsVersion == "" {
		tsVersion = DefaultTailscaleVersion
	}

	var doc strings.Builder
	doc.WriteString("variant: fcos\nversion: 1.5.0\n# GENERATED by devx cluster usb — do not edit by hand.\n")
	// FCOS defaults to SELinux Enforcing; k3s runs without the k3s-selinux policy
	// (skipped to avoid an rpm-ostree reboot), so keep the node Permissive across
	// reboots — the first-boot join also sets it at runtime via setenforce.
	doc.WriteString("kernel_arguments:\n  should_exist:\n    - enforcing=0\n")
	doc.WriteString("storage:\n  files:\n")
	doc.WriteString(fcosFileEntry("/usr/local/bin/devx-join.sh", "0755", script))
	if tsEnabled {
		env := "TS_AUTHKEY=" + s.TailscaleAuthKey + "\n"
		if s.WiFiPSK != "" {
			env += "WIFI_PSK=" + s.WiFiPSK + "\n"
		}
		doc.WriteString(fcosFileEntry("/etc/devx/join.env", "0600", env))
		doc.WriteString(fcosFileEntry("/usr/local/bin/devx-ts-install.sh", "0755", tsInstallScript(tsVersion)))
		doc.WriteString(fcosFileEntry("/usr/local/bin/devx-ts-up.sh", "0755", tsUpScript()))
		doc.WriteString("    - path: /etc/modules-load.d/devx-tun.conf\n      mode: 0644\n      overwrite: true\n      contents:\n        inline: |\n          tun\n")
	}

	doc.WriteString("systemd:\n  units:\n")
	if tsEnabled {
		doc.WriteString(fcosTailscaleUnits())
	}
	doc.WriteString(fcosJoinUnit(tsEnabled))
	return doc.String()
}

// fcosFileEntry renders one Butane storage.files entry with base64 contents.
func fcosFileEntry(path, mode, content string) string {
	b64 := base64.StdEncoding.EncodeToString([]byte(content))
	return fmt.Sprintf("    - path: %s\n      mode: %s\n      overwrite: true\n      contents:\n        source: \"data:text/plain;base64,%s\"\n", path, mode, b64)
}

// tsInstallScript fetches + installs the pinned Tailscale static binaries and
// relabels them so SELinux (Enforcing on FCOS) can exec them.
func tsInstallScript(tsVersion string) string {
	return `#!/usr/bin/env bash
# devx: fetch + install Tailscale static binaries on immutable FCOS.
set -euo pipefail
TS_VERSION=` + tsVersion + `
cd /tmp
curl -fL --retry 5 --retry-connrefused -o ts.tgz "https://pkgs.tailscale.com/stable/tailscale_${TS_VERSION}_amd64.tgz"
tar -xzf ts.tgz
d="tailscale_${TS_VERSION}_amd64"
install -m0755 "$d/tailscaled" /usr/local/bin/tailscaled
install -m0755 "$d/tailscale" /usr/local/bin/tailscale
# Without bin_t, SELinux Enforcing blocks init_t from exec-ing them (status=203/EXEC).
chcon -t bin_t /usr/local/bin/tailscaled /usr/local/bin/tailscale
`
}

// tsUpScript brings the tailnet up best-effort and publishes the tailnet IPv4 to
// /run/devx/tailnet-ip for the join script. It NEVER fails the unit: a Tailscale
// problem must not block a LAN-reachable join.
func tsUpScript() string {
	return `#!/usr/bin/env bash
# devx: bring up Tailscale (best-effort) and publish the tailnet IP for the join.
set -uo pipefail
for _ in $(seq 1 30); do /usr/local/bin/tailscale status >/dev/null 2>&1 && break; sleep 2; done
/usr/local/bin/tailscale up --authkey="${TS_AUTHKEY:-}" --accept-routes --hostname="$(cat /run/devx/node-name 2>/dev/null || hostname)" || exit 0
mkdir -p /run/devx
for _ in $(seq 1 30); do ip=$(/usr/local/bin/tailscale ip -4 2>/dev/null) && [ -n "$ip" ] && { echo "$ip" >/run/devx/tailnet-ip; break; }; sleep 2; done
`
}

// fcosTailscaleUnits renders the three units that provision Tailscale on
// immutable FCOS: fetch the static binaries, run tailscaled in kernel mode (so
// tailscale0 is a real host interface k3s --flannel-iface can bind), and bring
// the tailnet up while publishing the tailnet IP.
func fcosTailscaleUnits() string {
	return `    - name: devx-tailscaled-install.service
      enabled: true
      contents: |
        [Unit]
        Description=devx fetch Tailscale static binaries
        After=network-online.target
        Wants=network-online.target
        Before=tailscaled.service devx-join.service
        ConditionPathExists=!/usr/local/bin/tailscaled
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/usr/local/bin/devx-ts-install.sh
        [Install]
        WantedBy=multi-user.target
    - name: tailscaled.service
      enabled: true
      contents: |
        [Unit]
        Description=Tailscale node agent (devx static)
        Requires=devx-tailscaled-install.service
        After=devx-tailscaled-install.service network-pre.target
        Wants=network-pre.target
        Before=devx-join.service
        [Service]
        ExecStart=/usr/local/bin/tailscaled --state=/var/lib/tailscale/tailscaled.state --socket=/run/tailscale/tailscaled.sock --port=41641
        ExecStopPost=/usr/local/bin/tailscaled --cleanup
        Restart=on-failure
        RuntimeDirectory=tailscale
        StateDirectory=tailscale
        CacheDirectory=tailscale
        Type=notify
        [Install]
        WantedBy=multi-user.target
    - name: devx-tailscale-up.service
      enabled: true
      contents: |
        [Unit]
        Description=devx tailscale up and publish tailnet IP
        Requires=tailscaled.service
        After=tailscaled.service network-online.target time-sync.target
        Wants=network-online.target time-sync.target
        Before=devx-join.service
        ConditionPathExists=/etc/devx/join.env
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        EnvironmentFile=/etc/devx/join.env
        ExecStart=/usr/local/bin/devx-ts-up.sh
        [Install]
        WantedBy=multi-user.target
`
}

// fcosJoinUnit renders the devx-join oneshot. With Tailscale enabled it Wants
// (not Requires) devx-tailscale-up so the join still succeeds over LAN if
// Tailscale is down; the joined marker is written only once k3s is actually up.
func fcosJoinUnit(tsEnabled bool) string {
	tsDep := ""
	if tsEnabled {
		tsDep = " devx-tailscale-up.service"
	}
	return `    - name: devx-join.service
      enabled: true
      contents: |
        [Unit]
        Description=devx cluster node join
        After=network-online.target time-sync.target` + tsDep + `
        Wants=network-online.target time-sync.target` + tsDep + `
        ConditionPathExists=!/var/lib/devx/joined
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        EnvironmentFile=-/etc/devx/join.env
        ExecStartPre=/usr/bin/mkdir -p /var/lib/devx
        ExecStart=/usr/local/bin/devx-join.sh
        ExecStartPost=/usr/bin/bash -c 'if systemctl is-active --quiet k3s-agent || systemctl is-active --quiet k3s; then touch /var/lib/devx/joined; fi'
        [Install]
        WantedBy=multi-user.target
`
}
