// Copyright (c) 2026 VitruvianSoftware
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

package usb

import (
	"encoding/base64"
	"fmt"
)

// FCOSImage is the Fedora CoreOS live ISO filename the FCOS boot entries expect
// on the Ventoy stick. The operator supplies the actual ISO (it is hundreds of
// MB and not vendored).
const FCOSImage = "fedora-coreos-live.x86_64.iso"

// FCOSRenderer packages the canonical join script as a Fedora CoreOS Ignition
// config (authored as Butane). This is the highest-reuse renderer — it rides the
// same FCOS/Ignition/butane stack devx already uses in internal/ignition.
type FCOSRenderer struct{}

// Name implements Renderer.
func (FCOSRenderer) Name() string { return "fcos" }

// Modes implements Renderer.
func (FCOSRenderer) Modes() []Mode { return []Mode{ModeEphemeral, ModeInstall} }

// Render implements Renderer. It emits a Butane file (.bu) that writes the join
// script and a oneshot systemd unit to run it. The build layer compiles the .bu
// to Ignition with butane (gated) and embeds it into the live ISO.
func (FCOSRenderer) Render(spec JoinSpec, m Mode, sink ArtifactSink) ([]BootEntry, error) {
	if !modeSupported(FCOSRenderer{}, m) {
		return nil, fmt.Errorf("fcos: unsupported mode %q", m)
	}
	spec.Mode = m

	script, err := RenderJoinScript(spec)
	if err != nil {
		return nil, fmt.Errorf("fcos: rendering join script: %w", err)
	}

	butane := fcosButane(script, m)
	dir := fmt.Sprintf("fcos/%s", m)
	buPath := dir + "/devx-join.bu"
	if err := sink.Add(Artifact{Path: buPath, Contents: []byte(butane), Mode: 0o644}); err != nil {
		return nil, err
	}
	// Also drop the raw script for transparency/debugging.
	if err := sink.Add(Artifact{Path: dir + "/devx-join.sh", Contents: []byte(script), Mode: 0o755}); err != nil {
		return nil, err
	}

	notes := "Boot the FCOS live ISO with this Ignition embedded " +
		"(coreos-installer iso ignition embed) or injected via Ventoy."
	if m == ModeInstall {
		notes = "Live env runs coreos-installer to persist FCOS + this Ignition to the internal disk, then reboots."
	}

	return []BootEntry{{
		MenuTitle:     menuTitle("Fedora CoreOS", m),
		BaseImage:     FCOSImage,
		Renderer:      "fcos",
		Mode:          m,
		InstallToDisk: m == ModeInstall,
		Injection: Injection{
			Kind:        InjectIgnition,
			PayloadPath: buPath,
			Notes:       notes,
		},
	}}, nil
}

// fcosButane returns a Butane (FCOS 1.5.0) document that writes the join script
// and a oneshot unit to execute it on first boot. For install mode an extra unit
// persists the OS to disk before the join runs.
func fcosButane(script string, m Mode) string {
	b64 := base64.StdEncoding.EncodeToString([]byte(script))

	doc := `variant: fcos
version: 1.5.0
# GENERATED by devx cluster usb — do not edit by hand.
storage:
  files:
    - path: /usr/local/bin/devx-join.sh
      mode: 0755
      overwrite: true
      contents:
        source: "data:text/plain;base64,` + b64 + `"
systemd:
  units:
    - name: devx-join.service
      enabled: true
      contents: |
        [Unit]
        Description=devx cluster node join
        After=network-online.target
        Wants=network-online.target
        ConditionPathExists=!/var/lib/devx/joined
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStartPre=/usr/bin/mkdir -p /var/lib/devx
        ExecStart=/usr/local/bin/devx-join.sh
        ExecStartPost=/usr/bin/touch /var/lib/devx/joined
        [Install]
        WantedBy=multi-user.target
`
	if m == ModeInstall {
		// In install mode the live environment first writes FCOS (carrying this
		// same Ignition) to the internal disk, then reboots into the installed
		// system where devx-join runs. The target disk is auto-detected.
		doc += `    - name: devx-install.service
      enabled: true
      contents: |
        [Unit]
        Description=devx install FCOS to internal disk
        Before=devx-join.service
        ConditionKernelCommandLine=devx.install
        [Service]
        Type=oneshot
        ExecStart=/usr/local/bin/devx-fcos-install.sh
        [Install]
        WantedBy=multi-user.target
`
	}
	return doc
}
