// Copyright (c) 2026 VitruvianSoftware
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

package usb

import (
	"encoding/base64"
	"fmt"
)

// UbuntuImage is the Ubuntu live-server ISO the Ubuntu boot entries expect. The
// server ISO has first-class cloud-init/autoinstall support and the broadest
// laptop Wi-Fi/hardware coverage, making it the Wi-Fi-friendly renderer.
const UbuntuImage = "ubuntu-24.04-live-server-amd64.iso"

// UbuntuRenderer packages the canonical join script as a cloud-init NoCloud seed
// (ephemeral) or a subiquity autoinstall (install). Chosen when broad hardware
// support matters more than FCOS's immutability.
type UbuntuRenderer struct{}

// Name implements Renderer.
func (UbuntuRenderer) Name() string { return "ubuntu" }

// Modes implements Renderer.
func (UbuntuRenderer) Modes() []Mode { return []Mode{ModeEphemeral, ModeInstall} }

// Render implements Renderer. It emits a NoCloud seed (user-data + meta-data)
// and the raw join script. The build/assembler layer points the kernel's cloud-init
// datasource at the seed directory.
func (UbuntuRenderer) Render(spec JoinSpec, m Mode, sink ArtifactSink) ([]BootEntry, error) {
	if !modeSupported(UbuntuRenderer{}, m) {
		return nil, fmt.Errorf("ubuntu: unsupported mode %q", m)
	}
	spec.Mode = m

	script, err := RenderJoinScript(spec)
	if err != nil {
		return nil, fmt.Errorf("ubuntu: rendering join script: %w", err)
	}

	dir := fmt.Sprintf("ubuntu/%s", m)
	var userData string
	if m == ModeInstall {
		userData = ubuntuAutoinstall(script)
	} else {
		userData = ubuntuNoCloud(script)
	}

	for _, a := range []Artifact{
		{Path: dir + "/user-data", Contents: []byte(userData), Mode: 0o644},
		{Path: dir + "/meta-data", Contents: []byte("instance-id: devx-usb-node\n"), Mode: 0o644},
		{Path: dir + "/devx-join.sh", Contents: []byte(script), Mode: 0o755},
	} {
		if err := sink.Add(a); err != nil {
			return nil, err
		}
	}

	notes := "Boot the Ubuntu live-server ISO with autoinstall/ds=nocloud pointed at this seed dir."
	return []BootEntry{{
		MenuTitle:     menuTitle("Ubuntu (Wi-Fi friendly)", m),
		BaseImage:     UbuntuImage,
		Renderer:      "ubuntu",
		Mode:          m,
		InstallToDisk: m == ModeInstall,
		Injection: Injection{
			Kind:        InjectCloudInit,
			PayloadPath: dir + "/user-data",
			Notes:       notes,
		},
	}}, nil
}

// ubuntuNoCloud builds a cloud-init #cloud-config that writes the join script and
// runs it once — used for the live (ephemeral) session.
func ubuntuNoCloud(script string) string {
	b64 := base64.StdEncoding.EncodeToString([]byte(script))
	return `#cloud-config
# GENERATED by devx cluster usb — ephemeral live-boot join (NoCloud).
write_files:
  - path: /usr/local/bin/devx-join.sh
    permissions: '0755'
    encoding: b64
    content: ` + b64 + `
runcmd:
  - [ /usr/local/bin/devx-join.sh ]
`
}

// ubuntuAutoinstall builds a subiquity autoinstall user-data that installs Ubuntu
// to the internal disk (direct layout — destructive, the install intent) and
// installs the join script + a oneshot unit into the target so the node joins on
// first boot. Identity and storage are intentionally minimal and operator-tunable.
func ubuntuAutoinstall(script string) string {
	b64 := base64.StdEncoding.EncodeToString([]byte(script))
	unit := `[Unit]
Description=devx cluster node join
After=network-online.target
Wants=network-online.target
ConditionPathExists=!/var/lib/devx/joined
[Service]
Type=oneshot
RemainAfterExit=yes
ExecStartPre=/usr/bin/mkdir -p /var/lib/devx
ExecStart=/usr/local/bin/devx-join.sh
ExecStartPost=/usr/bin/touch /var/lib/devx/joined
[Install]
WantedBy=multi-user.target
`
	unitB64 := base64.StdEncoding.EncodeToString([]byte(unit))
	return `#cloud-config
# GENERATED by devx cluster usb — persistent install (subiquity autoinstall).
autoinstall:
  version: 1
  locale: en_US.UTF-8
  keyboard: { layout: us }
  identity:
    hostname: devx-node
    username: devx
    # Locked password; access is via Tailscale SSH / the cluster, not console.
    password: "!"
  ssh:
    install-server: true
  storage:
    layout: { name: direct }
  late-commands:
    - echo '` + b64 + `' | base64 -d > /target/usr/local/bin/devx-join.sh
    - chmod 0755 /target/usr/local/bin/devx-join.sh
    - echo '` + unitB64 + `' | base64 -d > /target/etc/systemd/system/devx-join.service
    - curtin in-target --target=/target -- systemctl enable devx-join.service
`
}
