// Copyright (c) 2026 VitruvianSoftware
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

package main

import (
	"bytes"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// OwnersNode represents a directory in the OWNERS tree.
type OwnersNode struct {
	RelPath   string
	Config    *Config
	Children  map[string]*OwnersNode
	Effective []string
}

// Engine encapsulates recursive discovery and CODEOWNERS generation.
type Engine struct {
	RootDir string
	Nodes   map[string]*OwnersNode
}

// NewEngine creates an Engine rooted at rootDir.
func NewEngine(rootDir string) *Engine {
	return &Engine{
		RootDir: rootDir,
		Nodes:   make(map[string]*OwnersNode),
	}
}

// Discover traverses rootDir to find and parse all OWNERS files.
func (e *Engine) Discover() error {
	ignoredDirs := map[string]bool{
		".git":           true,
		".aspect":        true,
		".agents":        true,
		"node_modules":   true,
		"bazel-bin":      true,
		"bazel-out":      true,
		"bazel-testlogs": true,
		"dist":           true,
		"bin":            true,
	}

	err := filepath.WalkDir(e.RootDir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			name := d.Name()
			if ignoredDirs[name] || strings.HasPrefix(name, "bazel-") {
				return filepath.SkipDir
			}
			return nil
		}

		if d.Name() == "OWNERS" || d.Name() == "OWNERS.yaml" || d.Name() == "OWNERS.yml" {
			rel, err := filepath.Rel(e.RootDir, filepath.Dir(path))
			if err != nil {
				return err
			}
			if rel == "." {
				rel = ""
			}

			data, err := os.ReadFile(path)
			if err != nil {
				return fmt.Errorf("reading %s: %w", path, err)
			}

			cfg, err := ParseConfig(data)
			if err != nil {
				return fmt.Errorf("parsing %s: %w", path, err)
			}

			if err := ValidateConfig(path, cfg); err != nil {
				return err
			}

			e.Nodes[rel] = &OwnersNode{
				RelPath:  rel,
				Config:   cfg,
				Children: make(map[string]*OwnersNode),
			}
		}
		return nil
	})
	if err != nil {
		return fmt.Errorf("discovering OWNERS: %w", err)
	}

	e.resolveInheritance()
	return nil
}

func (e *Engine) resolveInheritance() {
	var paths []string
	for p := range e.Nodes {
		paths = append(paths, p)
	}
	// Sort paths by depth (shallow to deep), then alphabetically
	sort.Slice(paths, func(i, j int) bool {
		di := strings.Count(paths[i], "/")
		dj := strings.Count(paths[j], "/")
		if paths[i] == "" {
			return true
		}
		if paths[j] == "" {
			return false
		}
		if di != dj {
			return di < dj
		}
		return paths[i] < paths[j]
	})

	for _, p := range paths {
		node := e.Nodes[p]
		currentApprovers := node.Config.EffectiveApprovers()

		if p == "" || node.Config.Options.NoParentOwners {
			node.Effective = currentApprovers
			continue
		}

		// Find closest parent node
		parentPath := p
		var parentNode *OwnersNode
		for {
			idx := strings.LastIndex(parentPath, "/")
			if idx == -1 {
				parentNode = e.Nodes[""]
				break
			}
			parentPath = parentPath[:idx]
			if pn, ok := e.Nodes[parentPath]; ok {
				parentNode = pn
				break
			}
		}

		if parentNode != nil {
			merged := make([]string, 0)
			seen := make(map[string]bool)
			for _, a := range currentApprovers {
				if !seen[a] {
					seen[a] = true
					merged = append(merged, a)
				}
			}
			for _, a := range parentNode.Effective {
				if !seen[a] {
					seen[a] = true
					merged = append(merged, a)
				}
			}
			node.Effective = merged
		} else {
			node.Effective = currentApprovers
		}
	}
}

// Compile generates the GitHub CODEOWNERS content.
func (e *Engine) Compile() (string, error) {
	var b bytes.Buffer
	b.WriteString("# VitruvianSoftware Monorepo CODEOWNERS\n")
	b.WriteString("#\n")
	b.WriteString("# Code generated by //tools/owners. DO NOT EDIT.\n")
	b.WriteString("# To update ownership, edit per-directory OWNERS files and run:\n")
	b.WriteString("#   bazel run //tools/owners -- --out .github/CODEOWNERS\n")
	b.WriteString("#\n")
	b.WriteString("# NOTE: CODEOWNERS uses \"last matching pattern wins\" ordering.\n\n")

	// 1. Root catch-all
	rootNode := e.Nodes[""]
	if rootNode != nil && len(rootNode.Effective) > 0 {
		b.WriteString("# Catch-all root default\n")
		b.WriteString(fmt.Sprintf("* %s\n\n", strings.Join(formatHandles(rootNode.Effective), " ")))
	} else {
		b.WriteString("# Catch-all root default\n")
		b.WriteString("* @VitruvianSoftware/platform-team\n\n")
	}

	// 2. Root configuration anchors
	b.WriteString("# Root configuration files\n")
	rootOwners := "@VitruvianSoftware/platform-team"
	if rootNode != nil && len(rootNode.Effective) > 0 {
		rootOwners = strings.Join(formatHandles(rootNode.Effective), " ")
	}
	rootAnchors := []string{
		"/.bazelrc",
		"/.bazelversion",
		"/MODULE.bazel",
		"/MODULE.bazel.lock",
		"/BUILD",
		"/.github/",
		"/githooks/",
	}
	for _, anchor := range rootAnchors {
		b.WriteString(fmt.Sprintf("%s %s\n", anchor, rootOwners))
	}
	b.WriteString("\n")

	// 3. Subtree directory rules
	var subpaths []string
	for p := range e.Nodes {
		if p != "" {
			subpaths = append(subpaths, p)
		}
	}

	// Sort subpaths: shallow first, then alphabetically
	sort.Slice(subpaths, func(i, j int) bool {
		di := strings.Count(subpaths[i], "/")
		dj := strings.Count(subpaths[j], "/")
		if di != dj {
			return di < dj
		}
		return subpaths[i] < subpaths[j]
	})

	b.WriteString("# Subtree Directory Ownership Rules\n")
	for _, p := range subpaths {
		node := e.Nodes[p]
		pattern := fmt.Sprintf("/%s/", p)
		ownersStr := strings.Join(formatHandles(node.Effective), " ")
		b.WriteString(fmt.Sprintf("%s %s\n", pattern, ownersStr))

		// Per-file rules under this subtree
		for _, pf := range node.Config.PerFile {
			approvers := pf.Approvers
			if len(approvers) == 0 {
				approvers = pf.Owners
			}
			if len(approvers) > 0 {
				pfPattern := fmt.Sprintf("/%s/%s", p, pf.Pattern)
				b.WriteString(fmt.Sprintf("%s %s\n", pfPattern, strings.Join(formatHandles(approvers), " ")))
			}
		}
	}

	return b.String(), nil
}

func formatHandles(handles []string) []string {
	var out []string
	for _, h := range handles {
		if !strings.HasPrefix(h, "@") && !strings.Contains(h, "@") {
			out = append(out, "@"+h)
		} else {
			out = append(out, h)
		}
	}
	return out
}
